//
// DisciplinaryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DisciplinaryAPI {

    /**
     Add investigation journal case note
     
     - parameter id: (path)  
     - parameter addJournalEntryRequest: (body)  
     - returns: IncidentJournalEntryItem
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addIncidentJournalEntry(id: UUID, addJournalEntryRequest: AddJournalEntryRequest) async throws -> IncidentJournalEntryItem {
        return try await addIncidentJournalEntryWithRequestBuilder(id: id, addJournalEntryRequest: addJournalEntryRequest).execute().body
    }

    /**
     Add investigation journal case note
     - POST /v1/disciplinary/incidents/{id}/journal
     - Appends a chronological entry to the incident investigation journal.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter addJournalEntryRequest: (body)  
     - returns: RequestBuilder<IncidentJournalEntryItem> 
     */
    open class func addIncidentJournalEntryWithRequestBuilder(id: UUID, addJournalEntryRequest: AddJournalEntryRequest) -> RequestBuilder<IncidentJournalEntryItem> {
        var localVariablePath = "/v1/disciplinary/incidents/{id}/journal"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addJournalEntryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IncidentJournalEntryItem>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     File appeal against corrective action
     
     - parameter id: (path)  
     - parameter disciplinaryAppealRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: DisciplinaryAppealItem
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func appealCorrectiveAction(id: UUID, disciplinaryAppealRequest: DisciplinaryAppealRequest, idempotencyKey: String? = nil) async throws -> DisciplinaryAppealItem {
        return try await appealCorrectiveActionWithRequestBuilder(id: id, disciplinaryAppealRequest: disciplinaryAppealRequest, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     File appeal against corrective action
     - POST /v1/disciplinary/actions/{id}/appeal
     - Lodges a formal appeal against an issued disciplinary penalty or action.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter disciplinaryAppealRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: RequestBuilder<DisciplinaryAppealItem> 
     */
    open class func appealCorrectiveActionWithRequestBuilder(id: UUID, disciplinaryAppealRequest: DisciplinaryAppealRequest, idempotencyKey: String? = nil) -> RequestBuilder<DisciplinaryAppealItem> {
        var localVariablePath = "/v1/disciplinary/actions/{id}/appeal"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: disciplinaryAppealRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisciplinaryAppealItem>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get disciplinary incident details
     
     - parameter id: (path)  
     - returns: DisciplinaryIncidentDetailResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDisciplinaryIncidentById(id: UUID) async throws -> DisciplinaryIncidentDetailResponse {
        return try await getDisciplinaryIncidentByIdWithRequestBuilder(id: id).execute().body
    }

    /**
     Get disciplinary incident details
     - GET /v1/disciplinary/incidents/{id}
     - Returns incident case particulars, investigation journal entries, corrective actions, and appeals.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<DisciplinaryIncidentDetailResponse> 
     */
    open class func getDisciplinaryIncidentByIdWithRequestBuilder(id: UUID) -> RequestBuilder<DisciplinaryIncidentDetailResponse> {
        var localVariablePath = "/v1/disciplinary/incidents/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisciplinaryIncidentDetailResponse>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List disciplinary incidents
     
     - parameter employeeId: (query)  (optional)
     - parameter status: (query)  (optional)
     - returns: DisciplinaryIncidentListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDisciplinaryIncidents(employeeId: UUID? = nil, status: String? = nil) async throws -> DisciplinaryIncidentListResponse {
        return try await getDisciplinaryIncidentsWithRequestBuilder(employeeId: employeeId, status: status).execute().body
    }

    /**
     List disciplinary incidents
     - GET /v1/disciplinary/incidents
     - Returns disciplinary incidents filtered by employee, severity, or status.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter employeeId: (query)  (optional)
     - parameter status: (query)  (optional)
     - returns: RequestBuilder<DisciplinaryIncidentListResponse> 
     */
    open class func getDisciplinaryIncidentsWithRequestBuilder(employeeId: UUID? = nil, status: String? = nil) -> RequestBuilder<DisciplinaryIncidentListResponse> {
        let localVariablePath = "/v1/disciplinary/incidents"
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "employeeId": (wrappedValue: employeeId?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisciplinaryIncidentListResponse>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List disciplinary incident types and subtypes
     
     - returns: IncidentTypesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getIncidentTypes() async throws -> IncidentTypesResponse {
        return try await getIncidentTypesWithRequestBuilder().execute().body
    }

    /**
     List disciplinary incident types and subtypes
     - GET /v1/disciplinary/types
     - Returns company-defined incident classifications and subcategories.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<IncidentTypesResponse> 
     */
    open class func getIncidentTypesWithRequestBuilder() -> RequestBuilder<IncidentTypesResponse> {
        let localVariablePath = "/v1/disciplinary/types"
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IncidentTypesResponse>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Issue progressive corrective action
     
     - parameter id: (path)  
     - parameter issueCorrectiveActionRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: CorrectiveActionItem
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func issueCorrectiveAction(id: UUID, issueCorrectiveActionRequest: IssueCorrectiveActionRequest, idempotencyKey: String? = nil) async throws -> CorrectiveActionItem {
        return try await issueCorrectiveActionWithRequestBuilder(id: id, issueCorrectiveActionRequest: issueCorrectiveActionRequest, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Issue progressive corrective action
     - POST /v1/disciplinary/incidents/{id}/actions
     - Issues a corrective action (Oral Warning, Written Warning, Show Cause Notice, Suspension, etc.) for an incident.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter issueCorrectiveActionRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: RequestBuilder<CorrectiveActionItem> 
     */
    open class func issueCorrectiveActionWithRequestBuilder(id: UUID, issueCorrectiveActionRequest: IssueCorrectiveActionRequest, idempotencyKey: String? = nil) -> RequestBuilder<CorrectiveActionItem> {
        var localVariablePath = "/v1/disciplinary/incidents/{id}/actions"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: issueCorrectiveActionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CorrectiveActionItem>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Report a disciplinary incident
     
     - parameter disciplinaryIncidentReportRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: DisciplinaryIncidentItem
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func reportDisciplinaryIncident(disciplinaryIncidentReportRequest: DisciplinaryIncidentReportRequest, idempotencyKey: String? = nil) async throws -> DisciplinaryIncidentItem {
        return try await reportDisciplinaryIncidentWithRequestBuilder(disciplinaryIncidentReportRequest: disciplinaryIncidentReportRequest, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Report a disciplinary incident
     - POST /v1/disciplinary/incidents
     - Creates an incident report with witness accounts and initial severity rating.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter disciplinaryIncidentReportRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: RequestBuilder<DisciplinaryIncidentItem> 
     */
    open class func reportDisciplinaryIncidentWithRequestBuilder(disciplinaryIncidentReportRequest: DisciplinaryIncidentReportRequest, idempotencyKey: String? = nil) -> RequestBuilder<DisciplinaryIncidentItem> {
        let localVariablePath = "/v1/disciplinary/incidents"
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: disciplinaryIncidentReportRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisciplinaryIncidentItem>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit employee response to corrective action
     
     - parameter id: (path)  
     - parameter correctiveActionResponseRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: CorrectiveActionItem
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func respondToCorrectiveAction(id: UUID, correctiveActionResponseRequest: CorrectiveActionResponseRequest, idempotencyKey: String? = nil) async throws -> CorrectiveActionItem {
        return try await respondToCorrectiveActionWithRequestBuilder(id: id, correctiveActionResponseRequest: correctiveActionResponseRequest, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Submit employee response to corrective action
     - POST /v1/disciplinary/actions/{id}/respond
     - Allows employee to submit a formal written response or explanation to a show cause notice or warning.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter correctiveActionResponseRequest: (body)  
     - parameter idempotencyKey: (header) Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result.  (optional)
     - returns: RequestBuilder<CorrectiveActionItem> 
     */
    open class func respondToCorrectiveActionWithRequestBuilder(id: UUID, correctiveActionResponseRequest: CorrectiveActionResponseRequest, idempotencyKey: String? = nil) -> RequestBuilder<CorrectiveActionItem> {
        var localVariablePath = "/v1/disciplinary/actions/{id}/respond"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: correctiveActionResponseRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CorrectiveActionItem>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
