//
// EmployeesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EmployeesAPI {

    /**
     The edit form for one employee, with permissions applied
     
     - parameter id: (path)  
     - parameter acceptLanguage: (header)  (optional)
     - returns: FormSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getEmployeeEditForm(id: UUID, acceptLanguage: String? = nil) async throws -> FormSchema {
        return try await getEmployeeEditFormWithRequestBuilder(id: id, acceptLanguage: acceptLanguage).execute().body
    }

    /**
     The edit form for one employee, with permissions applied
     - GET /v1/employees/{id}/form
     - The same schema as `/v1/forms/employee`, narrowed to this caller and this record: fields they may not see are absent, and fields they may see but not change arrive with `editable: false`.  Built from the same permission context as the payload and the update path, so what the client is offered and what the server will accept cannot drift apart. Deriving the form separately is how you end up with an input that saves nothing. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter acceptLanguage: (header)  (optional)
     - returns: RequestBuilder<FormSchema> 
     */
    open class func getEmployeeEditFormWithRequestBuilder(id: UUID, acceptLanguage: String? = nil) -> RequestBuilder<FormSchema> {
        var localVariablePath = "/v1/employees/{id}/form"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FormSchema>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     An employee profile
     
     - parameter id: (path)  
     - returns: EmployeeProfile
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getEmployeeProfile(id: UUID) async throws -> EmployeeProfile {
        return try await getEmployeeProfileWithRequestBuilder(id: id).execute().body
    }

    /**
     An employee profile
     - GET /v1/employees/{id}
     - Two independent checks decide what comes back.  **Whether you see the record at all.** Your own record always; anyone's with `employee.view.all` or `employee.manage`; your reporting line — at any depth — with `employee.view`. Otherwise `404`, deliberately not `403`: a `403` confirms the record exists, which turns this endpoint into an oracle for enumerating employee ids.  **Which of its fields.** Applied server-side. A field you may not see is **absent from the payload**, not null — a null would tell you the field exists and you are not allowed it, and would have clients rendering disabled inputs for values they should not know about. A masked field arrives redacted, and the true value never leaves the server.  Sensitive fields — date of birth, home address, personal email, salary grade — are hidden by default and require an explicit grant, **including** for callers who hold `employee.manage`. Maintaining records and handling identity documents are separable duties. Your own sensitive fields are always readable to you. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<EmployeeProfile> 
     */
    open class func getEmployeeProfileWithRequestBuilder(id: UUID) -> RequestBuilder<EmployeeProfile> {
        var localVariablePath = "/v1/employees/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmployeeProfile>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     The caller's own employee profile
     
     - returns: EmployeeProfile
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOwnEmployeeProfile() async throws -> EmployeeProfile {
        return try await getOwnEmployeeProfileWithRequestBuilder().execute().body
    }

    /**
     The caller's own employee profile
     - GET /v1/employees/me
     - A separate path from `/v1/employees/{id}` rather than making the client substitute its own id: the app opens this on launch, before it necessarily knows the employee id.  Returns `404 NO_EMPLOYEE_RECORD` for a user account that is not linked to an employee — a platform operator or an integration credential. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<EmployeeProfile> 
     */
    open class func getOwnEmployeeProfileWithRequestBuilder() -> RequestBuilder<EmployeeProfile> {
        let localVariablePath = "/v1/employees/me"
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmployeeProfile>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update an employee profile
     
     - parameter id: (path)  
     - parameter employeeUpdate: (body)  
     - parameter ifMatch: (header) The &#x60;version&#x60; from the profile you loaded, as a weak ETag. Omitted, the update is last-write-wins — two HR officers editing the same profile is common enough that omitting it loses one of them silently.  (optional)
     - returns: EmployeeProfile
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateEmployeeProfile(id: UUID, employeeUpdate: EmployeeUpdate, ifMatch: String? = nil) async throws -> EmployeeProfile {
        return try await updateEmployeeProfileWithRequestBuilder(id: id, employeeUpdate: employeeUpdate, ifMatch: ifMatch).execute().body
    }

    /**
     Update an employee profile
     - PATCH /v1/employees/{id}
     - PATCH rather than PUT because the caller may not be able to read every field. A PUT means \"here is the whole record\", which someone who cannot see the sensitive half is not in a position to send — they would have to echo back fields they never received, and the ones they omitted would be cleared.  A field the caller may not write is rejected with `403 FIELD_NOT_WRITABLE`, never silently dropped: a save that appears to succeed and quietly discards a change is worse than a refusal. Nothing is applied unless everything validates.  Writing is never the default. Without `employee.manage` you may change only your own contact details, preferred name and photo — not your name, date of birth or join date, which appear on statutory filings and change by request with evidence.  Send `If-Match` with the `version` you last read to avoid overwriting a concurrent edit. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter employeeUpdate: (body)  
     - parameter ifMatch: (header) The &#x60;version&#x60; from the profile you loaded, as a weak ETag. Omitted, the update is last-write-wins — two HR officers editing the same profile is common enough that omitting it loses one of them silently.  (optional)
     - returns: RequestBuilder<EmployeeProfile> 
     */
    open class func updateEmployeeProfileWithRequestBuilder(id: UUID, employeeUpdate: EmployeeUpdate, ifMatch: String? = nil) -> RequestBuilder<EmployeeProfile> {
        var localVariablePath = "/v1/employees/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HRClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: employeeUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "If-Match": ifMatch?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmployeeProfile>.Type = HRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
