/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApprovalDecisionResponse
 */
export interface ApprovalDecisionResponse {
    /**
     * 
     * @type {string}
     * @memberof ApprovalDecisionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalDecisionResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalDecisionResponse
     */
    decidedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ApprovalDecisionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ApprovalDecisionResponse interface.
 */
export function instanceOfApprovalDecisionResponse(value: object): value is ApprovalDecisionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('decidedAt' in value) || value['decidedAt'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApprovalDecisionResponseFromJSON(json: any): ApprovalDecisionResponse {
    return ApprovalDecisionResponseFromJSONTyped(json, false);
}

export function ApprovalDecisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalDecisionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'decidedAt': (new Date(json['decidedAt'])),
        'message': json['message'],
    };
}

export function ApprovalDecisionResponseToJSON(json: any): ApprovalDecisionResponse {
    return ApprovalDecisionResponseToJSONTyped(json, false);
}

export function ApprovalDecisionResponseToJSONTyped(value?: ApprovalDecisionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'decidedAt': ((value['decidedAt']).toISOString()),
        'message': value['message'],
    };
}

