/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttendanceApprovalDetails } from './AttendanceApprovalDetails';
import {
    AttendanceApprovalDetailsFromJSON,
    AttendanceApprovalDetailsFromJSONTyped,
    AttendanceApprovalDetailsToJSON,
    AttendanceApprovalDetailsToJSONTyped,
} from './AttendanceApprovalDetails';
import type { LeaveApprovalDetails } from './LeaveApprovalDetails';
import {
    LeaveApprovalDetailsFromJSON,
    LeaveApprovalDetailsFromJSONTyped,
    LeaveApprovalDetailsToJSON,
    LeaveApprovalDetailsToJSONTyped,
} from './LeaveApprovalDetails';

/**
 * 
 * @export
 * @interface ApprovalItem
 */
export interface ApprovalItem {
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    id: string;
    /**
     * LEAVE_APPLICATION or ATTENDANCE_REGULARISATION
     * @type {string}
     * @memberof ApprovalItem
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    requesterId: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    requesterName: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    requesterDesignation?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    requesterPhotoKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    departmentName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalItem
     */
    submittedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalItem
     */
    urgency: ApprovalItemUrgencyEnum;
    /**
     * 
     * @type {LeaveApprovalDetails}
     * @memberof ApprovalItem
     */
    leaveDetails?: LeaveApprovalDetails;
    /**
     * 
     * @type {AttendanceApprovalDetails}
     * @memberof ApprovalItem
     */
    attendanceDetails?: AttendanceApprovalDetails;
}


/**
 * @export
 */
export const ApprovalItemUrgencyEnum = {
    Normal: 'NORMAL',
    Urgent: 'URGENT',
    Overdue: 'OVERDUE'
} as const;
export type ApprovalItemUrgencyEnum = typeof ApprovalItemUrgencyEnum[keyof typeof ApprovalItemUrgencyEnum];


/**
 * Check if a given object implements the ApprovalItem interface.
 */
export function instanceOfApprovalItem(value: object): value is ApprovalItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('requesterId' in value) || value['requesterId'] === undefined) return false;
    if (!('requesterName' in value) || value['requesterName'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('urgency' in value) || value['urgency'] === undefined) return false;
    return true;
}

export function ApprovalItemFromJSON(json: any): ApprovalItem {
    return ApprovalItemFromJSONTyped(json, false);
}

export function ApprovalItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'requesterId': json['requesterId'],
        'requesterName': json['requesterName'],
        'requesterDesignation': json['requesterDesignation'] == null ? undefined : json['requesterDesignation'],
        'requesterPhotoKey': json['requesterPhotoKey'] == null ? undefined : json['requesterPhotoKey'],
        'departmentName': json['departmentName'] == null ? undefined : json['departmentName'],
        'submittedAt': (new Date(json['submittedAt'])),
        'title': json['title'],
        'summary': json['summary'],
        'status': json['status'],
        'urgency': json['urgency'],
        'leaveDetails': json['leaveDetails'] == null ? undefined : LeaveApprovalDetailsFromJSON(json['leaveDetails']),
        'attendanceDetails': json['attendanceDetails'] == null ? undefined : AttendanceApprovalDetailsFromJSON(json['attendanceDetails']),
    };
}

export function ApprovalItemToJSON(json: any): ApprovalItem {
    return ApprovalItemToJSONTyped(json, false);
}

export function ApprovalItemToJSONTyped(value?: ApprovalItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'requesterId': value['requesterId'],
        'requesterName': value['requesterName'],
        'requesterDesignation': value['requesterDesignation'],
        'requesterPhotoKey': value['requesterPhotoKey'],
        'departmentName': value['departmentName'],
        'submittedAt': ((value['submittedAt']).toISOString()),
        'title': value['title'],
        'summary': value['summary'],
        'status': value['status'],
        'urgency': value['urgency'],
        'leaveDetails': LeaveApprovalDetailsToJSON(value['leaveDetails']),
        'attendanceDetails': AttendanceApprovalDetailsToJSON(value['attendanceDetails']),
    };
}

