/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerTimelineEvent
 */
export interface CareerTimelineEvent {
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    movementId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    eventType: CareerTimelineEventEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof CareerTimelineEvent
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    departmentName?: string;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    designationName?: string;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    salaryGradeCode?: string;
    /**
     * 
     * @type {number}
     * @memberof CareerTimelineEvent
     */
    baseSalary?: number;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof CareerTimelineEvent
     */
    changePercentage?: number;
    /**
     * 
     * @type {string}
     * @memberof CareerTimelineEvent
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareerTimelineEvent
     */
    isMilestone: boolean;
}


/**
 * @export
 */
export const CareerTimelineEventEventTypeEnum = {
    Hire: 'HIRE',
    Confirmation: 'CONFIRMATION',
    Promotion: 'PROMOTION',
    LateralTransfer: 'LATERAL_TRANSFER',
    SalaryRevision: 'SALARY_REVISION',
    DesignationChange: 'DESIGNATION_CHANGE',
    Secondment: 'SECONDMENT',
    Demotion: 'DEMOTION'
} as const;
export type CareerTimelineEventEventTypeEnum = typeof CareerTimelineEventEventTypeEnum[keyof typeof CareerTimelineEventEventTypeEnum];


/**
 * Check if a given object implements the CareerTimelineEvent interface.
 */
export function instanceOfCareerTimelineEvent(value: object): value is CareerTimelineEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isMilestone' in value) || value['isMilestone'] === undefined) return false;
    return true;
}

export function CareerTimelineEventFromJSON(json: any): CareerTimelineEvent {
    return CareerTimelineEventFromJSONTyped(json, false);
}

export function CareerTimelineEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerTimelineEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'movementId': json['movementId'] == null ? undefined : json['movementId'],
        'eventType': json['eventType'],
        'title': json['title'],
        'date': (new Date(json['date'])),
        'departmentName': json['departmentName'] == null ? undefined : json['departmentName'],
        'designationName': json['designationName'] == null ? undefined : json['designationName'],
        'salaryGradeCode': json['salaryGradeCode'] == null ? undefined : json['salaryGradeCode'],
        'baseSalary': json['baseSalary'] == null ? undefined : json['baseSalary'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'changePercentage': json['changePercentage'] == null ? undefined : json['changePercentage'],
        'description': json['description'],
        'isMilestone': json['isMilestone'],
    };
}

export function CareerTimelineEventToJSON(json: any): CareerTimelineEvent {
    return CareerTimelineEventToJSONTyped(json, false);
}

export function CareerTimelineEventToJSONTyped(value?: CareerTimelineEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'movementId': value['movementId'],
        'eventType': value['eventType'],
        'title': value['title'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'departmentName': value['departmentName'],
        'designationName': value['designationName'],
        'salaryGradeCode': value['salaryGradeCode'],
        'baseSalary': value['baseSalary'],
        'currency': value['currency'],
        'changePercentage': value['changePercentage'],
        'description': value['description'],
        'isMilestone': value['isMilestone'],
    };
}

