/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CareerMovementItem } from './CareerMovementItem';
import {
    CareerMovementItemFromJSON,
    CareerMovementItemFromJSONTyped,
    CareerMovementItemToJSON,
    CareerMovementItemToJSONTyped,
} from './CareerMovementItem';

/**
 * 
 * @export
 * @interface CareerMovementListResponse
 */
export interface CareerMovementListResponse {
    /**
     * 
     * @type {number}
     * @memberof CareerMovementListResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CareerMovementItem>}
     * @memberof CareerMovementListResponse
     */
    movements: Array<CareerMovementItem>;
}

/**
 * Check if a given object implements the CareerMovementListResponse interface.
 */
export function instanceOfCareerMovementListResponse(value: object): value is CareerMovementListResponse {
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('movements' in value) || value['movements'] === undefined) return false;
    return true;
}

export function CareerMovementListResponseFromJSON(json: any): CareerMovementListResponse {
    return CareerMovementListResponseFromJSONTyped(json, false);
}

export function CareerMovementListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerMovementListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'movements': ((json['movements'] as Array<any>).map(CareerMovementItemFromJSON)),
    };
}

export function CareerMovementListResponseToJSON(json: any): CareerMovementListResponse {
    return CareerMovementListResponseToJSONTyped(json, false);
}

export function CareerMovementListResponseToJSONTyped(value?: CareerMovementListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'movements': ((value['movements'] as Array<any>).map(CareerMovementItemToJSON)),
    };
}

