/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationChannel } from './NotificationChannel';
import {
    NotificationChannelFromJSON,
    NotificationChannelFromJSONTyped,
    NotificationChannelToJSON,
    NotificationChannelToJSONTyped,
} from './NotificationChannel';

/**
 * 
 * @export
 * @interface ChannelPreference
 */
export interface ChannelPreference {
    /**
     * The event this applies to, e.g. `leave.approved`.
     * @type {string}
     * @memberof ChannelPreference
     */
    eventKey: string;
    /**
     * 
     * @type {NotificationChannel}
     * @memberof ChannelPreference
     */
    channel: NotificationChannel;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelPreference
     */
    enabled: boolean;
    /**
     * DIGEST batches the event into one daily summary. If any channel for an event is set to
     * digest, the whole event is digested — a summary cannot deliver one channel sooner than
     * another, so the stricter reading wins and nothing arrives more often than asked.
     * 
     * @type {string}
     * @memberof ChannelPreference
     */
    digestMode?: ChannelPreferenceDigestModeEnum;
}


/**
 * @export
 */
export const ChannelPreferenceDigestModeEnum = {
    Immediate: 'IMMEDIATE',
    Digest: 'DIGEST'
} as const;
export type ChannelPreferenceDigestModeEnum = typeof ChannelPreferenceDigestModeEnum[keyof typeof ChannelPreferenceDigestModeEnum];


/**
 * Check if a given object implements the ChannelPreference interface.
 */
export function instanceOfChannelPreference(value: object): value is ChannelPreference {
    if (!('eventKey' in value) || value['eventKey'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function ChannelPreferenceFromJSON(json: any): ChannelPreference {
    return ChannelPreferenceFromJSONTyped(json, false);
}

export function ChannelPreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelPreference {
    if (json == null) {
        return json;
    }
    return {
        
        'eventKey': json['eventKey'],
        'channel': NotificationChannelFromJSON(json['channel']),
        'enabled': json['enabled'],
        'digestMode': json['digestMode'] == null ? undefined : json['digestMode'],
    };
}

export function ChannelPreferenceToJSON(json: any): ChannelPreference {
    return ChannelPreferenceToJSONTyped(json, false);
}

export function ChannelPreferenceToJSONTyped(value?: ChannelPreference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventKey': value['eventKey'],
        'channel': NotificationChannelToJSON(value['channel']),
        'enabled': value['enabled'],
        'digestMode': value['digestMode'],
    };
}

