/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetencyItem
 */
export interface CompetencyItem {
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    groupName: string;
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompetencyItem
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CompetencyItem
     */
    targetLevel: number;
}

/**
 * Check if a given object implements the CompetencyItem interface.
 */
export function instanceOfCompetencyItem(value: object): value is CompetencyItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('groupName' in value) || value['groupName'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('targetLevel' in value) || value['targetLevel'] === undefined) return false;
    return true;
}

export function CompetencyItemFromJSON(json: any): CompetencyItem {
    return CompetencyItemFromJSONTyped(json, false);
}

export function CompetencyItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetencyItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'groupId': json['groupId'],
        'groupName': json['groupName'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'targetLevel': json['targetLevel'],
    };
}

export function CompetencyItemToJSON(json: any): CompetencyItem {
    return CompetencyItemToJSONTyped(json, false);
}

export function CompetencyItemToJSONTyped(value?: CompetencyItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'groupId': value['groupId'],
        'groupName': value['groupName'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'targetLevel': value['targetLevel'],
    };
}

