/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    platform: DevicePlatformEnum;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    osVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    appVersion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    biometricEnrolled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    attestationVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    trusted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    lastSeenAt?: Date;
    /**
     * True for the device making this request.
     * @type {boolean}
     * @memberof Device
     */
    current?: boolean;
}


/**
 * @export
 */
export const DevicePlatformEnum = {
    Android: 'ANDROID',
    Ios: 'IOS',
    Web: 'WEB',
    Kiosk: 'KIOSK'
} as const;
export type DevicePlatformEnum = typeof DevicePlatformEnum[keyof typeof DevicePlatformEnum];


/**
 * Check if a given object implements the Device interface.
 */
export function instanceOfDevice(value: object): value is Device {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('trusted' in value) || value['trusted'] === undefined) return false;
    return true;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Device {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'deviceId': json['deviceId'],
        'platform': json['platform'],
        'model': json['model'] == null ? undefined : json['model'],
        'osVersion': json['osVersion'] == null ? undefined : json['osVersion'],
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'biometricEnrolled': json['biometricEnrolled'] == null ? undefined : json['biometricEnrolled'],
        'attestationVerified': json['attestationVerified'] == null ? undefined : json['attestationVerified'],
        'trusted': json['trusted'],
        'lastSeenAt': json['lastSeenAt'] == null ? undefined : (new Date(json['lastSeenAt'])),
        'current': json['current'] == null ? undefined : json['current'],
    };
}

export function DeviceToJSON(json: any): Device {
    return DeviceToJSONTyped(json, false);
}

export function DeviceToJSONTyped(value?: Device | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'deviceId': value['deviceId'],
        'platform': value['platform'],
        'model': value['model'],
        'osVersion': value['osVersion'],
        'appVersion': value['appVersion'],
        'biometricEnrolled': value['biometricEnrolled'],
        'attestationVerified': value['attestationVerified'],
        'trusted': value['trusted'],
        'lastSeenAt': value['lastSeenAt'] == null ? undefined : ((value['lastSeenAt']).toISOString()),
        'current': value['current'],
    };
}

