/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeDocumentItem
 */
export interface EmployeeDocumentItem {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    id: string;
    /**
     * PASSPORT, VISA, WORK_PERMIT, LABOUR_CARD, DRIVING_LICENCE, NATIONAL_ID, OTHER
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    docType: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    docNumberMasked: string;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeDocumentItem
     */
    issueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeDocumentItem
     */
    expiryDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    issuingCountry?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeDocumentItem
     */
    daysRemaining?: number;
    /**
     * VALID, EXPIRING, EXPIRED, REPLACED
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeDocumentItem
     */
    hasAttachment: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDocumentItem
     */
    attachmentKey?: string;
}

/**
 * Check if a given object implements the EmployeeDocumentItem interface.
 */
export function instanceOfEmployeeDocumentItem(value: object): value is EmployeeDocumentItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('docType' in value) || value['docType'] === undefined) return false;
    if (!('docNumberMasked' in value) || value['docNumberMasked'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('hasAttachment' in value) || value['hasAttachment'] === undefined) return false;
    return true;
}

export function EmployeeDocumentItemFromJSON(json: any): EmployeeDocumentItem {
    return EmployeeDocumentItemFromJSONTyped(json, false);
}

export function EmployeeDocumentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeDocumentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'docType': json['docType'],
        'docNumberMasked': json['docNumberMasked'],
        'issueDate': json['issueDate'] == null ? undefined : (new Date(json['issueDate'])),
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'issuingCountry': json['issuingCountry'] == null ? undefined : json['issuingCountry'],
        'daysRemaining': json['daysRemaining'] == null ? undefined : json['daysRemaining'],
        'status': json['status'],
        'hasAttachment': json['hasAttachment'],
        'attachmentKey': json['attachmentKey'] == null ? undefined : json['attachmentKey'],
    };
}

export function EmployeeDocumentItemToJSON(json: any): EmployeeDocumentItem {
    return EmployeeDocumentItemToJSONTyped(json, false);
}

export function EmployeeDocumentItemToJSONTyped(value?: EmployeeDocumentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'docType': value['docType'],
        'docNumberMasked': value['docNumberMasked'],
        'issueDate': value['issueDate'] == null ? undefined : ((value['issueDate']).toISOString().substring(0,10)),
        'expiryDate': value['expiryDate'] == null ? undefined : ((value['expiryDate']).toISOString().substring(0,10)),
        'issuingCountry': value['issuingCountry'],
        'daysRemaining': value['daysRemaining'],
        'status': value['status'],
        'hasAttachment': value['hasAttachment'],
        'attachmentKey': value['attachmentKey'],
    };
}

