/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExitReasonItem } from './ExitReasonItem';
import {
    ExitReasonItemFromJSON,
    ExitReasonItemFromJSONTyped,
    ExitReasonItemToJSON,
    ExitReasonItemToJSONTyped,
} from './ExitReasonItem';

/**
 * 
 * @export
 * @interface ExitTypeItem
 */
export interface ExitTypeItem {
    /**
     * 
     * @type {string}
     * @memberof ExitTypeItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExitTypeItem
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ExitTypeItem
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExitTypeItem
     */
    voluntary: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExitTypeItem
     */
    noticeDays: number;
    /**
     * 
     * @type {boolean}
     * @memberof ExitTypeItem
     */
    requiresInterview: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExitTypeItem
     */
    requiresClearance: boolean;
    /**
     * 
     * @type {Array<ExitReasonItem>}
     * @memberof ExitTypeItem
     */
    reasons: Array<ExitReasonItem>;
}

/**
 * Check if a given object implements the ExitTypeItem interface.
 */
export function instanceOfExitTypeItem(value: object): value is ExitTypeItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('voluntary' in value) || value['voluntary'] === undefined) return false;
    if (!('noticeDays' in value) || value['noticeDays'] === undefined) return false;
    if (!('requiresInterview' in value) || value['requiresInterview'] === undefined) return false;
    if (!('requiresClearance' in value) || value['requiresClearance'] === undefined) return false;
    if (!('reasons' in value) || value['reasons'] === undefined) return false;
    return true;
}

export function ExitTypeItemFromJSON(json: any): ExitTypeItem {
    return ExitTypeItemFromJSONTyped(json, false);
}

export function ExitTypeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExitTypeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'voluntary': json['voluntary'],
        'noticeDays': json['noticeDays'],
        'requiresInterview': json['requiresInterview'],
        'requiresClearance': json['requiresClearance'],
        'reasons': ((json['reasons'] as Array<any>).map(ExitReasonItemFromJSON)),
    };
}

export function ExitTypeItemToJSON(json: any): ExitTypeItem {
    return ExitTypeItemToJSONTyped(json, false);
}

export function ExitTypeItemToJSONTyped(value?: ExitTypeItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'voluntary': value['voluntary'],
        'noticeDays': value['noticeDays'],
        'requiresInterview': value['requiresInterview'],
        'requiresClearance': value['requiresClearance'],
        'reasons': ((value['reasons'] as Array<any>).map(ExitReasonItemToJSON)),
    };
}

