/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseClaimLineInput
 */
export interface ExpenseClaimLineInput {
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimLineInput
     */
    categoryId: string;
    /**
     * 
     * @type {Date}
     * @memberof ExpenseClaimLineInput
     */
    expenseDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimLineInput
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimLineInput
     */
    merchantName?: string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseClaimLineInput
     */
    unitQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseClaimLineInput
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimLineInput
     */
    receiptKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimLineInput
     */
    receiptUrl?: string;
}

/**
 * Check if a given object implements the ExpenseClaimLineInput interface.
 */
export function instanceOfExpenseClaimLineInput(value: object): value is ExpenseClaimLineInput {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('expenseDate' in value) || value['expenseDate'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ExpenseClaimLineInputFromJSON(json: any): ExpenseClaimLineInput {
    return ExpenseClaimLineInputFromJSONTyped(json, false);
}

export function ExpenseClaimLineInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseClaimLineInput {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'expenseDate': (new Date(json['expenseDate'])),
        'description': json['description'],
        'merchantName': json['merchantName'] == null ? undefined : json['merchantName'],
        'unitQuantity': json['unitQuantity'] == null ? undefined : json['unitQuantity'],
        'amount': json['amount'],
        'receiptKey': json['receiptKey'] == null ? undefined : json['receiptKey'],
        'receiptUrl': json['receiptUrl'] == null ? undefined : json['receiptUrl'],
    };
}

export function ExpenseClaimLineInputToJSON(json: any): ExpenseClaimLineInput {
    return ExpenseClaimLineInputToJSONTyped(json, false);
}

export function ExpenseClaimLineInputToJSONTyped(value?: ExpenseClaimLineInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'expenseDate': ((value['expenseDate']).toISOString().substring(0,10)),
        'description': value['description'],
        'merchantName': value['merchantName'],
        'unitQuantity': value['unitQuantity'],
        'amount': value['amount'],
        'receiptKey': value['receiptKey'],
        'receiptUrl': value['receiptUrl'],
    };
}

