/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormSection } from './FormSection';
import {
    FormSectionFromJSON,
    FormSectionFromJSONTyped,
    FormSectionToJSON,
    FormSectionToJSONTyped,
} from './FormSection';

/**
 * 
 * @export
 * @interface FormSchema
 */
export interface FormSchema {
    /**
     * 
     * @type {string}
     * @memberof FormSchema
     */
    entityType: string;
    /**
     * A hash of the tenant's field definitions. Cache against it and skip re-rendering when
     * unchanged. Deliberately not a timestamp — two servers must agree for the same
     * configuration, or a client behind a load balancer sees the schema change on every
     * other request.
     * 
     * @type {string}
     * @memberof FormSchema
     */
    version: string;
    /**
     * 
     * @type {Array<FormSection>}
     * @memberof FormSchema
     */
    sections: Array<FormSection>;
}

/**
 * Check if a given object implements the FormSchema interface.
 */
export function instanceOfFormSchema(value: object): value is FormSchema {
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('sections' in value) || value['sections'] === undefined) return false;
    return true;
}

export function FormSchemaFromJSON(json: any): FormSchema {
    return FormSchemaFromJSONTyped(json, false);
}

export function FormSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'entityType': json['entityType'],
        'version': json['version'],
        'sections': ((json['sections'] as Array<any>).map(FormSectionFromJSON)),
    };
}

export function FormSchemaToJSON(json: any): FormSchema {
    return FormSchemaToJSONTyped(json, false);
}

export function FormSchemaToJSONTyped(value?: FormSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityType': value['entityType'],
        'version': value['version'],
        'sections': ((value['sections'] as Array<any>).map(FormSectionToJSON)),
    };
}

