/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrievanceItem
 */
export interface GrievanceItem {
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    grievanceNumber: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    groundCode: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    groundName: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    channelName: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    severity: GrievanceItemSeverityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof GrievanceItem
     */
    anonymous: boolean;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    status: GrievanceItemStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GrievanceItem
     */
    raisedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GrievanceItem
     */
    targetResolutionDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof GrievanceItem
     */
    resolvedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GrievanceItem
     */
    resolution?: string;
    /**
     * 
     * @type {number}
     * @memberof GrievanceItem
     */
    satisfactionRating?: number;
}


/**
 * @export
 */
export const GrievanceItemSeverityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type GrievanceItemSeverityEnum = typeof GrievanceItemSeverityEnum[keyof typeof GrievanceItemSeverityEnum];

/**
 * @export
 */
export const GrievanceItemStatusEnum = {
    Submitted: 'SUBMITTED',
    Assigned: 'ASSIGNED',
    UnderInvestigation: 'UNDER_INVESTIGATION',
    Resolved: 'RESOLVED',
    Appealed: 'APPEALED',
    Closed: 'CLOSED'
} as const;
export type GrievanceItemStatusEnum = typeof GrievanceItemStatusEnum[keyof typeof GrievanceItemStatusEnum];


/**
 * Check if a given object implements the GrievanceItem interface.
 */
export function instanceOfGrievanceItem(value: object): value is GrievanceItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('grievanceNumber' in value) || value['grievanceNumber'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('groundCode' in value) || value['groundCode'] === undefined) return false;
    if (!('groundName' in value) || value['groundName'] === undefined) return false;
    if (!('channelName' in value) || value['channelName'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('anonymous' in value) || value['anonymous'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('raisedAt' in value) || value['raisedAt'] === undefined) return false;
    if (!('targetResolutionDate' in value) || value['targetResolutionDate'] === undefined) return false;
    return true;
}

export function GrievanceItemFromJSON(json: any): GrievanceItem {
    return GrievanceItemFromJSONTyped(json, false);
}

export function GrievanceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrievanceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'grievanceNumber': json['grievanceNumber'],
        'title': json['title'],
        'groundCode': json['groundCode'],
        'groundName': json['groundName'],
        'channelName': json['channelName'],
        'severity': json['severity'],
        'anonymous': json['anonymous'],
        'status': json['status'],
        'raisedAt': (new Date(json['raisedAt'])),
        'targetResolutionDate': (new Date(json['targetResolutionDate'])),
        'resolvedAt': json['resolvedAt'] == null ? undefined : (new Date(json['resolvedAt'])),
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'satisfactionRating': json['satisfactionRating'] == null ? undefined : json['satisfactionRating'],
    };
}

export function GrievanceItemToJSON(json: any): GrievanceItem {
    return GrievanceItemToJSONTyped(json, false);
}

export function GrievanceItemToJSONTyped(value?: GrievanceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'grievanceNumber': value['grievanceNumber'],
        'title': value['title'],
        'groundCode': value['groundCode'],
        'groundName': value['groundName'],
        'channelName': value['channelName'],
        'severity': value['severity'],
        'anonymous': value['anonymous'],
        'status': value['status'],
        'raisedAt': ((value['raisedAt']).toISOString()),
        'targetResolutionDate': ((value['targetResolutionDate']).toISOString()),
        'resolvedAt': value['resolvedAt'] == null ? undefined : ((value['resolvedAt']).toISOString()),
        'resolution': value['resolution'],
        'satisfactionRating': value['satisfactionRating'],
    };
}

