/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrievanceChannelItem
 */
export interface GrievanceChannelItem {
    /**
     * 
     * @type {string}
     * @memberof GrievanceChannelItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceChannelItem
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof GrievanceChannelItem
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof GrievanceChannelItem
     */
    isConfidential: boolean;
}

/**
 * Check if a given object implements the GrievanceChannelItem interface.
 */
export function instanceOfGrievanceChannelItem(value: object): value is GrievanceChannelItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isConfidential' in value) || value['isConfidential'] === undefined) return false;
    return true;
}

export function GrievanceChannelItemFromJSON(json: any): GrievanceChannelItem {
    return GrievanceChannelItemFromJSONTyped(json, false);
}

export function GrievanceChannelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrievanceChannelItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'isConfidential': json['isConfidential'],
    };
}

export function GrievanceChannelItemToJSON(json: any): GrievanceChannelItem {
    return GrievanceChannelItemToJSONTyped(json, false);
}

export function GrievanceChannelItemToJSONTyped(value?: GrievanceChannelItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'isConfidential': value['isConfidential'],
    };
}

