/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InterviewScorecardItem } from './InterviewScorecardItem';
import {
    InterviewScorecardItemFromJSON,
    InterviewScorecardItemFromJSONTyped,
    InterviewScorecardItemToJSON,
    InterviewScorecardItemToJSONTyped,
} from './InterviewScorecardItem';

/**
 * 
 * @export
 * @interface InterviewItem
 */
export interface InterviewItem {
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    candidateName: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    vacancyTitle: string;
    /**
     * 
     * @type {number}
     * @memberof InterviewItem
     */
    interviewRound: number;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    interviewType: InterviewItemInterviewTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof InterviewItem
     */
    scheduledStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof InterviewItem
     */
    scheduledEnd: Date;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    locationOrLink?: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    meetingLink?: string;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    status: InterviewItemStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof InterviewItem
     */
    interviewerEmployeeIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InterviewItem
     */
    notes?: string;
    /**
     * 
     * @type {Array<InterviewScorecardItem>}
     * @memberof InterviewItem
     */
    scorecards: Array<InterviewScorecardItem>;
}


/**
 * @export
 */
export const InterviewItemInterviewTypeEnum = {
    PhoneScreen: 'PHONE_SCREEN',
    Technical: 'TECHNICAL',
    SystemDesign: 'SYSTEM_DESIGN',
    Behavioral: 'BEHAVIORAL',
    Hr: 'HR',
    Executive: 'EXECUTIVE'
} as const;
export type InterviewItemInterviewTypeEnum = typeof InterviewItemInterviewTypeEnum[keyof typeof InterviewItemInterviewTypeEnum];

/**
 * @export
 */
export const InterviewItemStatusEnum = {
    Scheduled: 'SCHEDULED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED',
    Rescheduled: 'RESCHEDULED'
} as const;
export type InterviewItemStatusEnum = typeof InterviewItemStatusEnum[keyof typeof InterviewItemStatusEnum];


/**
 * Check if a given object implements the InterviewItem interface.
 */
export function instanceOfInterviewItem(value: object): value is InterviewItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('candidateName' in value) || value['candidateName'] === undefined) return false;
    if (!('vacancyTitle' in value) || value['vacancyTitle'] === undefined) return false;
    if (!('interviewRound' in value) || value['interviewRound'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('interviewType' in value) || value['interviewType'] === undefined) return false;
    if (!('scheduledStart' in value) || value['scheduledStart'] === undefined) return false;
    if (!('scheduledEnd' in value) || value['scheduledEnd'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('interviewerEmployeeIds' in value) || value['interviewerEmployeeIds'] === undefined) return false;
    if (!('scorecards' in value) || value['scorecards'] === undefined) return false;
    return true;
}

export function InterviewItemFromJSON(json: any): InterviewItem {
    return InterviewItemFromJSONTyped(json, false);
}

export function InterviewItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterviewItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'applicationId': json['applicationId'],
        'candidateName': json['candidateName'],
        'vacancyTitle': json['vacancyTitle'],
        'interviewRound': json['interviewRound'],
        'title': json['title'],
        'interviewType': json['interviewType'],
        'scheduledStart': (new Date(json['scheduledStart'])),
        'scheduledEnd': (new Date(json['scheduledEnd'])),
        'locationOrLink': json['locationOrLink'] == null ? undefined : json['locationOrLink'],
        'meetingLink': json['meetingLink'] == null ? undefined : json['meetingLink'],
        'status': json['status'],
        'interviewerEmployeeIds': json['interviewerEmployeeIds'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'scorecards': ((json['scorecards'] as Array<any>).map(InterviewScorecardItemFromJSON)),
    };
}

export function InterviewItemToJSON(json: any): InterviewItem {
    return InterviewItemToJSONTyped(json, false);
}

export function InterviewItemToJSONTyped(value?: InterviewItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'applicationId': value['applicationId'],
        'candidateName': value['candidateName'],
        'vacancyTitle': value['vacancyTitle'],
        'interviewRound': value['interviewRound'],
        'title': value['title'],
        'interviewType': value['interviewType'],
        'scheduledStart': ((value['scheduledStart']).toISOString()),
        'scheduledEnd': ((value['scheduledEnd']).toISOString()),
        'locationOrLink': value['locationOrLink'],
        'meetingLink': value['meetingLink'],
        'status': value['status'],
        'interviewerEmployeeIds': value['interviewerEmployeeIds'],
        'notes': value['notes'],
        'scorecards': ((value['scorecards'] as Array<any>).map(InterviewScorecardItemToJSON)),
    };
}

