/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Jwk } from './Jwk';
import {
    JwkFromJSON,
    JwkFromJSONTyped,
    JwkToJSON,
    JwkToJSONTyped,
} from './Jwk';

/**
 * A JSON Web Key Set as defined by RFC 7517 §5.
 * @export
 * @interface JwkSet
 */
export interface JwkSet {
    /**
     * 
     * @type {Array<Jwk>}
     * @memberof JwkSet
     */
    keys: Array<Jwk>;
}

/**
 * Check if a given object implements the JwkSet interface.
 */
export function instanceOfJwkSet(value: object): value is JwkSet {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function JwkSetFromJSON(json: any): JwkSet {
    return JwkSetFromJSONTyped(json, false);
}

export function JwkSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwkSet {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(JwkFromJSON)),
    };
}

export function JwkSetToJSON(json: any): JwkSet {
    return JwkSetToJSONTyped(json, false);
}

export function JwkSetToJSONTyped(value?: JwkSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(JwkToJSON)),
    };
}

