/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaveBalanceItem } from './LeaveBalanceItem';
import {
    LeaveBalanceItemFromJSON,
    LeaveBalanceItemFromJSONTyped,
    LeaveBalanceItemToJSON,
    LeaveBalanceItemToJSONTyped,
} from './LeaveBalanceItem';

/**
 * 
 * @export
 * @interface LeaveBalancesResponse
 */
export interface LeaveBalancesResponse {
    /**
     * 
     * @type {string}
     * @memberof LeaveBalancesResponse
     */
    leaveYear: string;
    /**
     * 
     * @type {Array<LeaveBalanceItem>}
     * @memberof LeaveBalancesResponse
     */
    balances: Array<LeaveBalanceItem>;
}

/**
 * Check if a given object implements the LeaveBalancesResponse interface.
 */
export function instanceOfLeaveBalancesResponse(value: object): value is LeaveBalancesResponse {
    if (!('leaveYear' in value) || value['leaveYear'] === undefined) return false;
    if (!('balances' in value) || value['balances'] === undefined) return false;
    return true;
}

export function LeaveBalancesResponseFromJSON(json: any): LeaveBalancesResponse {
    return LeaveBalancesResponseFromJSONTyped(json, false);
}

export function LeaveBalancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaveBalancesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'leaveYear': json['leaveYear'],
        'balances': ((json['balances'] as Array<any>).map(LeaveBalanceItemFromJSON)),
    };
}

export function LeaveBalancesResponseToJSON(json: any): LeaveBalancesResponse {
    return LeaveBalancesResponseToJSONTyped(json, false);
}

export function LeaveBalancesResponseToJSONTyped(value?: LeaveBalancesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leaveYear': value['leaveYear'],
        'balances': ((value['balances'] as Array<any>).map(LeaveBalanceItemToJSON)),
    };
}

