/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaveApprovalDetails
 */
export interface LeaveApprovalDetails {
    /**
     * 
     * @type {string}
     * @memberof LeaveApprovalDetails
     */
    leaveTypeName: string;
    /**
     * 
     * @type {Date}
     * @memberof LeaveApprovalDetails
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof LeaveApprovalDetails
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof LeaveApprovalDetails
     */
    workingDays: number;
    /**
     * 
     * @type {string}
     * @memberof LeaveApprovalDetails
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof LeaveApprovalDetails
     */
    employeeBalanceDays: number;
    /**
     * 
     * @type {string}
     * @memberof LeaveApprovalDetails
     */
    teamCoverageWarning?: string;
}

/**
 * Check if a given object implements the LeaveApprovalDetails interface.
 */
export function instanceOfLeaveApprovalDetails(value: object): value is LeaveApprovalDetails {
    if (!('leaveTypeName' in value) || value['leaveTypeName'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('workingDays' in value) || value['workingDays'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('employeeBalanceDays' in value) || value['employeeBalanceDays'] === undefined) return false;
    return true;
}

export function LeaveApprovalDetailsFromJSON(json: any): LeaveApprovalDetails {
    return LeaveApprovalDetailsFromJSONTyped(json, false);
}

export function LeaveApprovalDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaveApprovalDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'leaveTypeName': json['leaveTypeName'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'workingDays': json['workingDays'],
        'reason': json['reason'],
        'employeeBalanceDays': json['employeeBalanceDays'],
        'teamCoverageWarning': json['teamCoverageWarning'] == null ? undefined : json['teamCoverageWarning'],
    };
}

export function LeaveApprovalDetailsToJSON(json: any): LeaveApprovalDetails {
    return LeaveApprovalDetailsToJSONTyped(json, false);
}

export function LeaveApprovalDetailsToJSONTyped(value?: LeaveApprovalDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leaveTypeName': value['leaveTypeName'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': ((value['endDate']).toISOString().substring(0,10)),
        'workingDays': value['workingDays'],
        'reason': value['reason'],
        'employeeBalanceDays': value['employeeBalanceDays'],
        'teamCoverageWarning': value['teamCoverageWarning'],
    };
}

