/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LetterRequestItem } from './LetterRequestItem';
import {
    LetterRequestItemFromJSON,
    LetterRequestItemFromJSONTyped,
    LetterRequestItemToJSON,
    LetterRequestItemToJSONTyped,
} from './LetterRequestItem';

/**
 * 
 * @export
 * @interface LetterRequestListResponse
 */
export interface LetterRequestListResponse {
    /**
     * 
     * @type {Array<LetterRequestItem>}
     * @memberof LetterRequestListResponse
     */
    requests: Array<LetterRequestItem>;
}

/**
 * Check if a given object implements the LetterRequestListResponse interface.
 */
export function instanceOfLetterRequestListResponse(value: object): value is LetterRequestListResponse {
    if (!('requests' in value) || value['requests'] === undefined) return false;
    return true;
}

export function LetterRequestListResponseFromJSON(json: any): LetterRequestListResponse {
    return LetterRequestListResponseFromJSONTyped(json, false);
}

export function LetterRequestListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterRequestListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requests': ((json['requests'] as Array<any>).map(LetterRequestItemFromJSON)),
    };
}

export function LetterRequestListResponseToJSON(json: any): LetterRequestListResponse {
    return LetterRequestListResponseToJSONTyped(json, false);
}

export function LetterRequestListResponseToJSONTyped(value?: LetterRequestListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requests': ((value['requests'] as Array<any>).map(LetterRequestItemToJSON)),
    };
}

