/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MraRelationshipScoreItem
 */
export interface MraRelationshipScoreItem {
    /**
     * 
     * @type {string}
     * @memberof MraRelationshipScoreItem
     */
    relationship: string;
    /**
     * 
     * @type {number}
     * @memberof MraRelationshipScoreItem
     */
    respondentCount: number;
    /**
     * 
     * @type {number}
     * @memberof MraRelationshipScoreItem
     */
    averageScore: number;
}

/**
 * Check if a given object implements the MraRelationshipScoreItem interface.
 */
export function instanceOfMraRelationshipScoreItem(value: object): value is MraRelationshipScoreItem {
    if (!('relationship' in value) || value['relationship'] === undefined) return false;
    if (!('respondentCount' in value) || value['respondentCount'] === undefined) return false;
    if (!('averageScore' in value) || value['averageScore'] === undefined) return false;
    return true;
}

export function MraRelationshipScoreItemFromJSON(json: any): MraRelationshipScoreItem {
    return MraRelationshipScoreItemFromJSONTyped(json, false);
}

export function MraRelationshipScoreItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MraRelationshipScoreItem {
    if (json == null) {
        return json;
    }
    return {
        
        'relationship': json['relationship'],
        'respondentCount': json['respondentCount'],
        'averageScore': json['averageScore'],
    };
}

export function MraRelationshipScoreItemToJSON(json: any): MraRelationshipScoreItem {
    return MraRelationshipScoreItemToJSONTyped(json, false);
}

export function MraRelationshipScoreItemToJSONTyped(value?: MraRelationshipScoreItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relationship': value['relationship'],
        'respondentCount': value['respondentCount'],
        'averageScore': value['averageScore'],
    };
}

