/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnboardingInstanceCreateRequest
 */
export interface OnboardingInstanceCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof OnboardingInstanceCreateRequest
     */
    employeeId: string;
    /**
     * 
     * @type {string}
     * @memberof OnboardingInstanceCreateRequest
     */
    profileId: string;
    /**
     * 
     * @type {Date}
     * @memberof OnboardingInstanceCreateRequest
     */
    joinDate: Date;
    /**
     * 
     * @type {string}
     * @memberof OnboardingInstanceCreateRequest
     */
    buddyEmployeeId?: string;
    /**
     * 
     * @type {string}
     * @memberof OnboardingInstanceCreateRequest
     */
    candidateId?: string;
}

/**
 * Check if a given object implements the OnboardingInstanceCreateRequest interface.
 */
export function instanceOfOnboardingInstanceCreateRequest(value: object): value is OnboardingInstanceCreateRequest {
    if (!('employeeId' in value) || value['employeeId'] === undefined) return false;
    if (!('profileId' in value) || value['profileId'] === undefined) return false;
    if (!('joinDate' in value) || value['joinDate'] === undefined) return false;
    return true;
}

export function OnboardingInstanceCreateRequestFromJSON(json: any): OnboardingInstanceCreateRequest {
    return OnboardingInstanceCreateRequestFromJSONTyped(json, false);
}

export function OnboardingInstanceCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingInstanceCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'employeeId': json['employeeId'],
        'profileId': json['profileId'],
        'joinDate': (new Date(json['joinDate'])),
        'buddyEmployeeId': json['buddyEmployeeId'] == null ? undefined : json['buddyEmployeeId'],
        'candidateId': json['candidateId'] == null ? undefined : json['candidateId'],
    };
}

export function OnboardingInstanceCreateRequestToJSON(json: any): OnboardingInstanceCreateRequest {
    return OnboardingInstanceCreateRequestToJSONTyped(json, false);
}

export function OnboardingInstanceCreateRequestToJSONTyped(value?: OnboardingInstanceCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'employeeId': value['employeeId'],
        'profileId': value['profileId'],
        'joinDate': ((value['joinDate']).toISOString().substring(0,10)),
        'buddyEmployeeId': value['buddyEmployeeId'],
        'candidateId': value['candidateId'],
    };
}

