/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayslipSummaryItem
 */
export interface PayslipSummaryItem {
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    payPeriodId: string;
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    periodCode: string;
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    periodName: string;
    /**
     * 
     * @type {Date}
     * @memberof PayslipSummaryItem
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof PayslipSummaryItem
     */
    endDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof PayslipSummaryItem
     */
    paymentDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof PayslipSummaryItem
     */
    basicSalary: number;
    /**
     * 
     * @type {number}
     * @memberof PayslipSummaryItem
     */
    grossPay: number;
    /**
     * 
     * @type {number}
     * @memberof PayslipSummaryItem
     */
    totalDeductions: number;
    /**
     * 
     * @type {number}
     * @memberof PayslipSummaryItem
     */
    netPay: number;
    /**
     * 
     * @type {string}
     * @memberof PayslipSummaryItem
     */
    paymentStatus: PayslipSummaryItemPaymentStatusEnum;
}


/**
 * @export
 */
export const PayslipSummaryItemPaymentStatusEnum = {
    Paid: 'PAID',
    Pending: 'PENDING',
    Processing: 'PROCESSING'
} as const;
export type PayslipSummaryItemPaymentStatusEnum = typeof PayslipSummaryItemPaymentStatusEnum[keyof typeof PayslipSummaryItemPaymentStatusEnum];


/**
 * Check if a given object implements the PayslipSummaryItem interface.
 */
export function instanceOfPayslipSummaryItem(value: object): value is PayslipSummaryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('payPeriodId' in value) || value['payPeriodId'] === undefined) return false;
    if (!('periodCode' in value) || value['periodCode'] === undefined) return false;
    if (!('periodName' in value) || value['periodName'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('paymentDate' in value) || value['paymentDate'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('basicSalary' in value) || value['basicSalary'] === undefined) return false;
    if (!('grossPay' in value) || value['grossPay'] === undefined) return false;
    if (!('totalDeductions' in value) || value['totalDeductions'] === undefined) return false;
    if (!('netPay' in value) || value['netPay'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    return true;
}

export function PayslipSummaryItemFromJSON(json: any): PayslipSummaryItem {
    return PayslipSummaryItemFromJSONTyped(json, false);
}

export function PayslipSummaryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayslipSummaryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'payPeriodId': json['payPeriodId'],
        'periodCode': json['periodCode'],
        'periodName': json['periodName'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'paymentDate': (new Date(json['paymentDate'])),
        'currency': json['currency'],
        'basicSalary': json['basicSalary'],
        'grossPay': json['grossPay'],
        'totalDeductions': json['totalDeductions'],
        'netPay': json['netPay'],
        'paymentStatus': json['paymentStatus'],
    };
}

export function PayslipSummaryItemToJSON(json: any): PayslipSummaryItem {
    return PayslipSummaryItemToJSONTyped(json, false);
}

export function PayslipSummaryItemToJSONTyped(value?: PayslipSummaryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payPeriodId': value['payPeriodId'],
        'periodCode': value['periodCode'],
        'periodName': value['periodName'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': ((value['endDate']).toISOString().substring(0,10)),
        'paymentDate': ((value['paymentDate']).toISOString().substring(0,10)),
        'currency': value['currency'],
        'basicSalary': value['basicSalary'],
        'grossPay': value['grossPay'],
        'totalDeductions': value['totalDeductions'],
        'netPay': value['netPay'],
        'paymentStatus': value['paymentStatus'],
    };
}

