/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShiftRosterDayItem
 */
export interface ShiftRosterDayItem {
    /**
     * 
     * @type {Date}
     * @memberof ShiftRosterDayItem
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    dayOfWeek: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    shiftCode: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    shiftName: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    endTime: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShiftRosterDayItem
     */
    isRestDay: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShiftRosterDayItem
     */
    isHoliday: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    holidayName?: string;
    /**
     * SCHEDULED, ON_DUTY, COMPLETED, REST_DAY, HOLIDAY, ON_LEAVE
     * @type {string}
     * @memberof ShiftRosterDayItem
     */
    dayStatus: string;
    /**
     * 
     * @type {number}
     * @memberof ShiftRosterDayItem
     */
    teamMembersOnDuty: number;
}

/**
 * Check if a given object implements the ShiftRosterDayItem interface.
 */
export function instanceOfShiftRosterDayItem(value: object): value is ShiftRosterDayItem {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('shiftCode' in value) || value['shiftCode'] === undefined) return false;
    if (!('shiftName' in value) || value['shiftName'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('isRestDay' in value) || value['isRestDay'] === undefined) return false;
    if (!('isHoliday' in value) || value['isHoliday'] === undefined) return false;
    if (!('dayStatus' in value) || value['dayStatus'] === undefined) return false;
    if (!('teamMembersOnDuty' in value) || value['teamMembersOnDuty'] === undefined) return false;
    return true;
}

export function ShiftRosterDayItemFromJSON(json: any): ShiftRosterDayItem {
    return ShiftRosterDayItemFromJSONTyped(json, false);
}

export function ShiftRosterDayItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShiftRosterDayItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'dayOfWeek': json['dayOfWeek'],
        'shiftCode': json['shiftCode'],
        'shiftName': json['shiftName'],
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'isRestDay': json['isRestDay'],
        'isHoliday': json['isHoliday'],
        'holidayName': json['holidayName'] == null ? undefined : json['holidayName'],
        'dayStatus': json['dayStatus'],
        'teamMembersOnDuty': json['teamMembersOnDuty'],
    };
}

export function ShiftRosterDayItemToJSON(json: any): ShiftRosterDayItem {
    return ShiftRosterDayItemToJSONTyped(json, false);
}

export function ShiftRosterDayItemToJSONTyped(value?: ShiftRosterDayItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
        'dayOfWeek': value['dayOfWeek'],
        'shiftCode': value['shiftCode'],
        'shiftName': value['shiftName'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'isRestDay': value['isRestDay'],
        'isHoliday': value['isHoliday'],
        'holidayName': value['holidayName'],
        'dayStatus': value['dayStatus'],
        'teamMembersOnDuty': value['teamMembersOnDuty'],
    };
}

