/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignatureSignerItem
 */
export interface SignatureSignerItem {
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    signerEmployeeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    signerName: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    signerEmail: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    role: string;
    /**
     * 
     * @type {number}
     * @memberof SignatureSignerItem
     */
    signingOrder: number;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    signatureType?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    signatureData?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureSignerItem
     */
    ipAddress?: string;
    /**
     * 
     * @type {Date}
     * @memberof SignatureSignerItem
     */
    signedAt?: Date;
}

/**
 * Check if a given object implements the SignatureSignerItem interface.
 */
export function instanceOfSignatureSignerItem(value: object): value is SignatureSignerItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('signerName' in value) || value['signerName'] === undefined) return false;
    if (!('signerEmail' in value) || value['signerEmail'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('signingOrder' in value) || value['signingOrder'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SignatureSignerItemFromJSON(json: any): SignatureSignerItem {
    return SignatureSignerItemFromJSONTyped(json, false);
}

export function SignatureSignerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureSignerItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'signerEmployeeId': json['signerEmployeeId'] == null ? undefined : json['signerEmployeeId'],
        'signerName': json['signerName'],
        'signerEmail': json['signerEmail'],
        'role': json['role'],
        'signingOrder': json['signingOrder'],
        'status': json['status'],
        'signatureType': json['signatureType'] == null ? undefined : json['signatureType'],
        'signatureData': json['signatureData'] == null ? undefined : json['signatureData'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'signedAt': json['signedAt'] == null ? undefined : (new Date(json['signedAt'])),
    };
}

export function SignatureSignerItemToJSON(json: any): SignatureSignerItem {
    return SignatureSignerItemToJSONTyped(json, false);
}

export function SignatureSignerItemToJSONTyped(value?: SignatureSignerItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'signerEmployeeId': value['signerEmployeeId'],
        'signerName': value['signerName'],
        'signerEmail': value['signerEmail'],
        'role': value['role'],
        'signingOrder': value['signingOrder'],
        'status': value['status'],
        'signatureType': value['signatureType'],
        'signatureData': value['signatureData'],
        'ipAddress': value['ipAddress'],
        'signedAt': value['signedAt'] == null ? undefined : ((value['signedAt']).toISOString()),
    };
}

