/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimesheetEntryInput } from './TimesheetEntryInput';
import {
    TimesheetEntryInputFromJSON,
    TimesheetEntryInputFromJSONTyped,
    TimesheetEntryInputToJSON,
    TimesheetEntryInputToJSONTyped,
} from './TimesheetEntryInput';

/**
 * 
 * @export
 * @interface TimesheetSaveRequest
 */
export interface TimesheetSaveRequest {
    /**
     * 
     * @type {string}
     * @memberof TimesheetSaveRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetSaveRequest
     */
    employeeId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimesheetSaveRequest
     */
    weekStartDate: Date;
    /**
     * 
     * @type {string}
     * @memberof TimesheetSaveRequest
     */
    comments?: string;
    /**
     * 
     * @type {Array<TimesheetEntryInput>}
     * @memberof TimesheetSaveRequest
     */
    entries: Array<TimesheetEntryInput>;
}

/**
 * Check if a given object implements the TimesheetSaveRequest interface.
 */
export function instanceOfTimesheetSaveRequest(value: object): value is TimesheetSaveRequest {
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function TimesheetSaveRequestFromJSON(json: any): TimesheetSaveRequest {
    return TimesheetSaveRequestFromJSONTyped(json, false);
}

export function TimesheetSaveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimesheetSaveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'employeeId': json['employeeId'] == null ? undefined : json['employeeId'],
        'weekStartDate': (new Date(json['weekStartDate'])),
        'comments': json['comments'] == null ? undefined : json['comments'],
        'entries': ((json['entries'] as Array<any>).map(TimesheetEntryInputFromJSON)),
    };
}

export function TimesheetSaveRequestToJSON(json: any): TimesheetSaveRequest {
    return TimesheetSaveRequestToJSONTyped(json, false);
}

export function TimesheetSaveRequestToJSONTyped(value?: TimesheetSaveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'employeeId': value['employeeId'],
        'weekStartDate': ((value['weekStartDate']).toISOString().substring(0,10)),
        'comments': value['comments'],
        'entries': ((value['entries'] as Array<any>).map(TimesheetEntryInputToJSON)),
    };
}

