/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraineeEvaluationSubmitRequest
 */
export interface TraineeEvaluationSubmitRequest {
    /**
     * 
     * @type {number}
     * @memberof TraineeEvaluationSubmitRequest
     */
    ratingScore: number;
    /**
     * 
     * @type {number}
     * @memberof TraineeEvaluationSubmitRequest
     */
    contentRating: number;
    /**
     * 
     * @type {number}
     * @memberof TraineeEvaluationSubmitRequest
     */
    instructorRating: number;
    /**
     * 
     * @type {string}
     * @memberof TraineeEvaluationSubmitRequest
     */
    feedbackComments?: string;
}

/**
 * Check if a given object implements the TraineeEvaluationSubmitRequest interface.
 */
export function instanceOfTraineeEvaluationSubmitRequest(value: object): value is TraineeEvaluationSubmitRequest {
    if (!('ratingScore' in value) || value['ratingScore'] === undefined) return false;
    if (!('contentRating' in value) || value['contentRating'] === undefined) return false;
    if (!('instructorRating' in value) || value['instructorRating'] === undefined) return false;
    return true;
}

export function TraineeEvaluationSubmitRequestFromJSON(json: any): TraineeEvaluationSubmitRequest {
    return TraineeEvaluationSubmitRequestFromJSONTyped(json, false);
}

export function TraineeEvaluationSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeEvaluationSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingScore': json['ratingScore'],
        'contentRating': json['contentRating'],
        'instructorRating': json['instructorRating'],
        'feedbackComments': json['feedbackComments'] == null ? undefined : json['feedbackComments'],
    };
}

export function TraineeEvaluationSubmitRequestToJSON(json: any): TraineeEvaluationSubmitRequest {
    return TraineeEvaluationSubmitRequestToJSONTyped(json, false);
}

export function TraineeEvaluationSubmitRequestToJSONTyped(value?: TraineeEvaluationSubmitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ratingScore': value['ratingScore'],
        'contentRating': value['contentRating'],
        'instructorRating': value['instructorRating'],
        'feedbackComments': value['feedbackComments'],
    };
}

