/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddJournalEntryRequest,
  ApiErrorResponse,
  CorrectiveActionItem,
  CorrectiveActionResponseRequest,
  DisciplinaryAppealItem,
  DisciplinaryAppealRequest,
  DisciplinaryIncidentDetailResponse,
  DisciplinaryIncidentItem,
  DisciplinaryIncidentListResponse,
  DisciplinaryIncidentReportRequest,
  IncidentJournalEntryItem,
  IncidentTypesResponse,
  IssueCorrectiveActionRequest,
} from '../models/index';
import {
    AddJournalEntryRequestFromJSON,
    AddJournalEntryRequestToJSON,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CorrectiveActionItemFromJSON,
    CorrectiveActionItemToJSON,
    CorrectiveActionResponseRequestFromJSON,
    CorrectiveActionResponseRequestToJSON,
    DisciplinaryAppealItemFromJSON,
    DisciplinaryAppealItemToJSON,
    DisciplinaryAppealRequestFromJSON,
    DisciplinaryAppealRequestToJSON,
    DisciplinaryIncidentDetailResponseFromJSON,
    DisciplinaryIncidentDetailResponseToJSON,
    DisciplinaryIncidentItemFromJSON,
    DisciplinaryIncidentItemToJSON,
    DisciplinaryIncidentListResponseFromJSON,
    DisciplinaryIncidentListResponseToJSON,
    DisciplinaryIncidentReportRequestFromJSON,
    DisciplinaryIncidentReportRequestToJSON,
    IncidentJournalEntryItemFromJSON,
    IncidentJournalEntryItemToJSON,
    IncidentTypesResponseFromJSON,
    IncidentTypesResponseToJSON,
    IssueCorrectiveActionRequestFromJSON,
    IssueCorrectiveActionRequestToJSON,
} from '../models/index';

export interface AddIncidentJournalEntryRequest {
    id: string;
    addJournalEntryRequest: AddJournalEntryRequest;
}

export interface AppealCorrectiveActionRequest {
    id: string;
    disciplinaryAppealRequest: DisciplinaryAppealRequest;
    idempotencyKey?: string;
}

export interface GetDisciplinaryIncidentByIdRequest {
    id: string;
}

export interface GetDisciplinaryIncidentsRequest {
    employeeId?: string;
    status?: string;
}

export interface IssueCorrectiveActionOperationRequest {
    id: string;
    issueCorrectiveActionRequest: IssueCorrectiveActionRequest;
    idempotencyKey?: string;
}

export interface ReportDisciplinaryIncidentRequest {
    disciplinaryIncidentReportRequest: DisciplinaryIncidentReportRequest;
    idempotencyKey?: string;
}

export interface RespondToCorrectiveActionRequest {
    id: string;
    correctiveActionResponseRequest: CorrectiveActionResponseRequest;
    idempotencyKey?: string;
}

/**
 * DisciplinaryApi - interface
 * 
 * @export
 * @interface DisciplinaryApiInterface
 */
export interface DisciplinaryApiInterface {
    /**
     * Appends a chronological entry to the incident investigation journal.
     * @summary Add investigation journal case note
     * @param {string} id 
     * @param {AddJournalEntryRequest} addJournalEntryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    addIncidentJournalEntryRaw(requestParameters: AddIncidentJournalEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentJournalEntryItem>>;

    /**
     * Appends a chronological entry to the incident investigation journal.
     * Add investigation journal case note
     */
    addIncidentJournalEntry(requestParameters: AddIncidentJournalEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentJournalEntryItem>;

    /**
     * Lodges a formal appeal against an issued disciplinary penalty or action.
     * @summary File appeal against corrective action
     * @param {string} id 
     * @param {DisciplinaryAppealRequest} disciplinaryAppealRequest 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    appealCorrectiveActionRaw(requestParameters: AppealCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryAppealItem>>;

    /**
     * Lodges a formal appeal against an issued disciplinary penalty or action.
     * File appeal against corrective action
     */
    appealCorrectiveAction(requestParameters: AppealCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryAppealItem>;

    /**
     * Returns incident case particulars, investigation journal entries, corrective actions, and appeals.
     * @summary Get disciplinary incident details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    getDisciplinaryIncidentByIdRaw(requestParameters: GetDisciplinaryIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentDetailResponse>>;

    /**
     * Returns incident case particulars, investigation journal entries, corrective actions, and appeals.
     * Get disciplinary incident details
     */
    getDisciplinaryIncidentById(requestParameters: GetDisciplinaryIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentDetailResponse>;

    /**
     * Returns disciplinary incidents filtered by employee, severity, or status.
     * @summary List disciplinary incidents
     * @param {string} [employeeId] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    getDisciplinaryIncidentsRaw(requestParameters: GetDisciplinaryIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentListResponse>>;

    /**
     * Returns disciplinary incidents filtered by employee, severity, or status.
     * List disciplinary incidents
     */
    getDisciplinaryIncidents(requestParameters: GetDisciplinaryIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentListResponse>;

    /**
     * Returns company-defined incident classifications and subcategories.
     * @summary List disciplinary incident types and subtypes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    getIncidentTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentTypesResponse>>;

    /**
     * Returns company-defined incident classifications and subcategories.
     * List disciplinary incident types and subtypes
     */
    getIncidentTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentTypesResponse>;

    /**
     * Issues a corrective action (Oral Warning, Written Warning, Show Cause Notice, Suspension, etc.) for an incident.
     * @summary Issue progressive corrective action
     * @param {string} id 
     * @param {IssueCorrectiveActionRequest} issueCorrectiveActionRequest 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    issueCorrectiveActionRaw(requestParameters: IssueCorrectiveActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorrectiveActionItem>>;

    /**
     * Issues a corrective action (Oral Warning, Written Warning, Show Cause Notice, Suspension, etc.) for an incident.
     * Issue progressive corrective action
     */
    issueCorrectiveAction(requestParameters: IssueCorrectiveActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorrectiveActionItem>;

    /**
     * Creates an incident report with witness accounts and initial severity rating.
     * @summary Report a disciplinary incident
     * @param {DisciplinaryIncidentReportRequest} disciplinaryIncidentReportRequest 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    reportDisciplinaryIncidentRaw(requestParameters: ReportDisciplinaryIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentItem>>;

    /**
     * Creates an incident report with witness accounts and initial severity rating.
     * Report a disciplinary incident
     */
    reportDisciplinaryIncident(requestParameters: ReportDisciplinaryIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentItem>;

    /**
     * Allows employee to submit a formal written response or explanation to a show cause notice or warning.
     * @summary Submit employee response to corrective action
     * @param {string} id 
     * @param {CorrectiveActionResponseRequest} correctiveActionResponseRequest 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisciplinaryApiInterface
     */
    respondToCorrectiveActionRaw(requestParameters: RespondToCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorrectiveActionItem>>;

    /**
     * Allows employee to submit a formal written response or explanation to a show cause notice or warning.
     * Submit employee response to corrective action
     */
    respondToCorrectiveAction(requestParameters: RespondToCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorrectiveActionItem>;

}

/**
 * 
 */
export class DisciplinaryApi extends runtime.BaseAPI implements DisciplinaryApiInterface {

    /**
     * Appends a chronological entry to the incident investigation journal.
     * Add investigation journal case note
     */
    async addIncidentJournalEntryRaw(requestParameters: AddIncidentJournalEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentJournalEntryItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addIncidentJournalEntry().'
            );
        }

        if (requestParameters['addJournalEntryRequest'] == null) {
            throw new runtime.RequiredError(
                'addJournalEntryRequest',
                'Required parameter "addJournalEntryRequest" was null or undefined when calling addIncidentJournalEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/incidents/{id}/journal`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddJournalEntryRequestToJSON(requestParameters['addJournalEntryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentJournalEntryItemFromJSON(jsonValue));
    }

    /**
     * Appends a chronological entry to the incident investigation journal.
     * Add investigation journal case note
     */
    async addIncidentJournalEntry(requestParameters: AddIncidentJournalEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentJournalEntryItem> {
        const response = await this.addIncidentJournalEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lodges a formal appeal against an issued disciplinary penalty or action.
     * File appeal against corrective action
     */
    async appealCorrectiveActionRaw(requestParameters: AppealCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryAppealItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appealCorrectiveAction().'
            );
        }

        if (requestParameters['disciplinaryAppealRequest'] == null) {
            throw new runtime.RequiredError(
                'disciplinaryAppealRequest',
                'Required parameter "disciplinaryAppealRequest" was null or undefined when calling appealCorrectiveAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/actions/{id}/appeal`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DisciplinaryAppealRequestToJSON(requestParameters['disciplinaryAppealRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisciplinaryAppealItemFromJSON(jsonValue));
    }

    /**
     * Lodges a formal appeal against an issued disciplinary penalty or action.
     * File appeal against corrective action
     */
    async appealCorrectiveAction(requestParameters: AppealCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryAppealItem> {
        const response = await this.appealCorrectiveActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns incident case particulars, investigation journal entries, corrective actions, and appeals.
     * Get disciplinary incident details
     */
    async getDisciplinaryIncidentByIdRaw(requestParameters: GetDisciplinaryIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDisciplinaryIncidentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/incidents/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisciplinaryIncidentDetailResponseFromJSON(jsonValue));
    }

    /**
     * Returns incident case particulars, investigation journal entries, corrective actions, and appeals.
     * Get disciplinary incident details
     */
    async getDisciplinaryIncidentById(requestParameters: GetDisciplinaryIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentDetailResponse> {
        const response = await this.getDisciplinaryIncidentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns disciplinary incidents filtered by employee, severity, or status.
     * List disciplinary incidents
     */
    async getDisciplinaryIncidentsRaw(requestParameters: GetDisciplinaryIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['employeeId'] != null) {
            queryParameters['employeeId'] = requestParameters['employeeId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/incidents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisciplinaryIncidentListResponseFromJSON(jsonValue));
    }

    /**
     * Returns disciplinary incidents filtered by employee, severity, or status.
     * List disciplinary incidents
     */
    async getDisciplinaryIncidents(requestParameters: GetDisciplinaryIncidentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentListResponse> {
        const response = await this.getDisciplinaryIncidentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns company-defined incident classifications and subcategories.
     * List disciplinary incident types and subtypes
     */
    async getIncidentTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentTypesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentTypesResponseFromJSON(jsonValue));
    }

    /**
     * Returns company-defined incident classifications and subcategories.
     * List disciplinary incident types and subtypes
     */
    async getIncidentTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentTypesResponse> {
        const response = await this.getIncidentTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Issues a corrective action (Oral Warning, Written Warning, Show Cause Notice, Suspension, etc.) for an incident.
     * Issue progressive corrective action
     */
    async issueCorrectiveActionRaw(requestParameters: IssueCorrectiveActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorrectiveActionItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling issueCorrectiveAction().'
            );
        }

        if (requestParameters['issueCorrectiveActionRequest'] == null) {
            throw new runtime.RequiredError(
                'issueCorrectiveActionRequest',
                'Required parameter "issueCorrectiveActionRequest" was null or undefined when calling issueCorrectiveAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/incidents/{id}/actions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IssueCorrectiveActionRequestToJSON(requestParameters['issueCorrectiveActionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorrectiveActionItemFromJSON(jsonValue));
    }

    /**
     * Issues a corrective action (Oral Warning, Written Warning, Show Cause Notice, Suspension, etc.) for an incident.
     * Issue progressive corrective action
     */
    async issueCorrectiveAction(requestParameters: IssueCorrectiveActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorrectiveActionItem> {
        const response = await this.issueCorrectiveActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates an incident report with witness accounts and initial severity rating.
     * Report a disciplinary incident
     */
    async reportDisciplinaryIncidentRaw(requestParameters: ReportDisciplinaryIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisciplinaryIncidentItem>> {
        if (requestParameters['disciplinaryIncidentReportRequest'] == null) {
            throw new runtime.RequiredError(
                'disciplinaryIncidentReportRequest',
                'Required parameter "disciplinaryIncidentReportRequest" was null or undefined when calling reportDisciplinaryIncident().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/incidents`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DisciplinaryIncidentReportRequestToJSON(requestParameters['disciplinaryIncidentReportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisciplinaryIncidentItemFromJSON(jsonValue));
    }

    /**
     * Creates an incident report with witness accounts and initial severity rating.
     * Report a disciplinary incident
     */
    async reportDisciplinaryIncident(requestParameters: ReportDisciplinaryIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisciplinaryIncidentItem> {
        const response = await this.reportDisciplinaryIncidentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows employee to submit a formal written response or explanation to a show cause notice or warning.
     * Submit employee response to corrective action
     */
    async respondToCorrectiveActionRaw(requestParameters: RespondToCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorrectiveActionItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling respondToCorrectiveAction().'
            );
        }

        if (requestParameters['correctiveActionResponseRequest'] == null) {
            throw new runtime.RequiredError(
                'correctiveActionResponseRequest',
                'Required parameter "correctiveActionResponseRequest" was null or undefined when calling respondToCorrectiveAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/disciplinary/actions/{id}/respond`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CorrectiveActionResponseRequestToJSON(requestParameters['correctiveActionResponseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorrectiveActionItemFromJSON(jsonValue));
    }

    /**
     * Allows employee to submit a formal written response or explanation to a show cause notice or warning.
     * Submit employee response to corrective action
     */
    async respondToCorrectiveAction(requestParameters: RespondToCorrectiveActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorrectiveActionItem> {
        const response = await this.respondToCorrectiveActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
