/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  EmployeeProfile,
  EmployeeUpdate,
  FormSchema,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    EmployeeProfileFromJSON,
    EmployeeProfileToJSON,
    EmployeeUpdateFromJSON,
    EmployeeUpdateToJSON,
    FormSchemaFromJSON,
    FormSchemaToJSON,
} from '../models/index';

export interface GetEmployeeEditFormRequest {
    id: string;
    acceptLanguage?: string;
}

export interface GetEmployeeProfileRequest {
    id: string;
}

export interface UpdateEmployeeProfileRequest {
    id: string;
    employeeUpdate: EmployeeUpdate;
    ifMatch?: string;
}

/**
 * EmployeesApi - interface
 * 
 * @export
 * @interface EmployeesApiInterface
 */
export interface EmployeesApiInterface {
    /**
     * The same schema as `/v1/forms/employee`, narrowed to this caller and this record: fields they may not see are absent, and fields they may see but not change arrive with `editable: false`.  Built from the same permission context as the payload and the update path, so what the client is offered and what the server will accept cannot drift apart. Deriving the form separately is how you end up with an input that saves nothing. 
     * @summary The edit form for one employee, with permissions applied
     * @param {string} id 
     * @param {string} [acceptLanguage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeesApiInterface
     */
    getEmployeeEditFormRaw(requestParameters: GetEmployeeEditFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormSchema>>;

    /**
     * The same schema as `/v1/forms/employee`, narrowed to this caller and this record: fields they may not see are absent, and fields they may see but not change arrive with `editable: false`.  Built from the same permission context as the payload and the update path, so what the client is offered and what the server will accept cannot drift apart. Deriving the form separately is how you end up with an input that saves nothing. 
     * The edit form for one employee, with permissions applied
     */
    getEmployeeEditForm(requestParameters: GetEmployeeEditFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormSchema>;

    /**
     * Two independent checks decide what comes back.  **Whether you see the record at all.** Your own record always; anyone\'s with `employee.view.all` or `employee.manage`; your reporting line — at any depth — with `employee.view`. Otherwise `404`, deliberately not `403`: a `403` confirms the record exists, which turns this endpoint into an oracle for enumerating employee ids.  **Which of its fields.** Applied server-side. A field you may not see is **absent from the payload**, not null — a null would tell you the field exists and you are not allowed it, and would have clients rendering disabled inputs for values they should not know about. A masked field arrives redacted, and the true value never leaves the server.  Sensitive fields — date of birth, home address, personal email, salary grade — are hidden by default and require an explicit grant, **including** for callers who hold `employee.manage`. Maintaining records and handling identity documents are separable duties. Your own sensitive fields are always readable to you. 
     * @summary An employee profile
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeesApiInterface
     */
    getEmployeeProfileRaw(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * Two independent checks decide what comes back.  **Whether you see the record at all.** Your own record always; anyone\'s with `employee.view.all` or `employee.manage`; your reporting line — at any depth — with `employee.view`. Otherwise `404`, deliberately not `403`: a `403` confirms the record exists, which turns this endpoint into an oracle for enumerating employee ids.  **Which of its fields.** Applied server-side. A field you may not see is **absent from the payload**, not null — a null would tell you the field exists and you are not allowed it, and would have clients rendering disabled inputs for values they should not know about. A masked field arrives redacted, and the true value never leaves the server.  Sensitive fields — date of birth, home address, personal email, salary grade — are hidden by default and require an explicit grant, **including** for callers who hold `employee.manage`. Maintaining records and handling identity documents are separable duties. Your own sensitive fields are always readable to you. 
     * An employee profile
     */
    getEmployeeProfile(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

    /**
     * A separate path from `/v1/employees/{id}` rather than making the client substitute its own id: the app opens this on launch, before it necessarily knows the employee id.  Returns `404 NO_EMPLOYEE_RECORD` for a user account that is not linked to an employee — a platform operator or an integration credential. 
     * @summary The caller\'s own employee profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeesApiInterface
     */
    getOwnEmployeeProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * A separate path from `/v1/employees/{id}` rather than making the client substitute its own id: the app opens this on launch, before it necessarily knows the employee id.  Returns `404 NO_EMPLOYEE_RECORD` for a user account that is not linked to an employee — a platform operator or an integration credential. 
     * The caller\'s own employee profile
     */
    getOwnEmployeeProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

    /**
     * PATCH rather than PUT because the caller may not be able to read every field. A PUT means \"here is the whole record\", which someone who cannot see the sensitive half is not in a position to send — they would have to echo back fields they never received, and the ones they omitted would be cleared.  A field the caller may not write is rejected with `403 FIELD_NOT_WRITABLE`, never silently dropped: a save that appears to succeed and quietly discards a change is worse than a refusal. Nothing is applied unless everything validates.  Writing is never the default. Without `employee.manage` you may change only your own contact details, preferred name and photo — not your name, date of birth or join date, which appear on statutory filings and change by request with evidence.  Send `If-Match` with the `version` you last read to avoid overwriting a concurrent edit. 
     * @summary Update an employee profile
     * @param {string} id 
     * @param {EmployeeUpdate} employeeUpdate 
     * @param {string} [ifMatch] The &#x60;version&#x60; from the profile you loaded, as a weak ETag. Omitted, the update is last-write-wins — two HR officers editing the same profile is common enough that omitting it loses one of them silently. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeesApiInterface
     */
    updateEmployeeProfileRaw(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * PATCH rather than PUT because the caller may not be able to read every field. A PUT means \"here is the whole record\", which someone who cannot see the sensitive half is not in a position to send — they would have to echo back fields they never received, and the ones they omitted would be cleared.  A field the caller may not write is rejected with `403 FIELD_NOT_WRITABLE`, never silently dropped: a save that appears to succeed and quietly discards a change is worse than a refusal. Nothing is applied unless everything validates.  Writing is never the default. Without `employee.manage` you may change only your own contact details, preferred name and photo — not your name, date of birth or join date, which appear on statutory filings and change by request with evidence.  Send `If-Match` with the `version` you last read to avoid overwriting a concurrent edit. 
     * Update an employee profile
     */
    updateEmployeeProfile(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

}

/**
 * 
 */
export class EmployeesApi extends runtime.BaseAPI implements EmployeesApiInterface {

    /**
     * The same schema as `/v1/forms/employee`, narrowed to this caller and this record: fields they may not see are absent, and fields they may see but not change arrive with `editable: false`.  Built from the same permission context as the payload and the update path, so what the client is offered and what the server will accept cannot drift apart. Deriving the form separately is how you end up with an input that saves nothing. 
     * The edit form for one employee, with permissions applied
     */
    async getEmployeeEditFormRaw(requestParameters: GetEmployeeEditFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmployeeEditForm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/employees/{id}/form`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormSchemaFromJSON(jsonValue));
    }

    /**
     * The same schema as `/v1/forms/employee`, narrowed to this caller and this record: fields they may not see are absent, and fields they may see but not change arrive with `editable: false`.  Built from the same permission context as the payload and the update path, so what the client is offered and what the server will accept cannot drift apart. Deriving the form separately is how you end up with an input that saves nothing. 
     * The edit form for one employee, with permissions applied
     */
    async getEmployeeEditForm(requestParameters: GetEmployeeEditFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormSchema> {
        const response = await this.getEmployeeEditFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Two independent checks decide what comes back.  **Whether you see the record at all.** Your own record always; anyone\'s with `employee.view.all` or `employee.manage`; your reporting line — at any depth — with `employee.view`. Otherwise `404`, deliberately not `403`: a `403` confirms the record exists, which turns this endpoint into an oracle for enumerating employee ids.  **Which of its fields.** Applied server-side. A field you may not see is **absent from the payload**, not null — a null would tell you the field exists and you are not allowed it, and would have clients rendering disabled inputs for values they should not know about. A masked field arrives redacted, and the true value never leaves the server.  Sensitive fields — date of birth, home address, personal email, salary grade — are hidden by default and require an explicit grant, **including** for callers who hold `employee.manage`. Maintaining records and handling identity documents are separable duties. Your own sensitive fields are always readable to you. 
     * An employee profile
     */
    async getEmployeeProfileRaw(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * Two independent checks decide what comes back.  **Whether you see the record at all.** Your own record always; anyone\'s with `employee.view.all` or `employee.manage`; your reporting line — at any depth — with `employee.view`. Otherwise `404`, deliberately not `403`: a `403` confirms the record exists, which turns this endpoint into an oracle for enumerating employee ids.  **Which of its fields.** Applied server-side. A field you may not see is **absent from the payload**, not null — a null would tell you the field exists and you are not allowed it, and would have clients rendering disabled inputs for values they should not know about. A masked field arrives redacted, and the true value never leaves the server.  Sensitive fields — date of birth, home address, personal email, salary grade — are hidden by default and require an explicit grant, **including** for callers who hold `employee.manage`. Maintaining records and handling identity documents are separable duties. Your own sensitive fields are always readable to you. 
     * An employee profile
     */
    async getEmployeeProfile(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.getEmployeeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A separate path from `/v1/employees/{id}` rather than making the client substitute its own id: the app opens this on launch, before it necessarily knows the employee id.  Returns `404 NO_EMPLOYEE_RECORD` for a user account that is not linked to an employee — a platform operator or an integration credential. 
     * The caller\'s own employee profile
     */
    async getOwnEmployeeProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/employees/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * A separate path from `/v1/employees/{id}` rather than making the client substitute its own id: the app opens this on launch, before it necessarily knows the employee id.  Returns `404 NO_EMPLOYEE_RECORD` for a user account that is not linked to an employee — a platform operator or an integration credential. 
     * The caller\'s own employee profile
     */
    async getOwnEmployeeProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.getOwnEmployeeProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * PATCH rather than PUT because the caller may not be able to read every field. A PUT means \"here is the whole record\", which someone who cannot see the sensitive half is not in a position to send — they would have to echo back fields they never received, and the ones they omitted would be cleared.  A field the caller may not write is rejected with `403 FIELD_NOT_WRITABLE`, never silently dropped: a save that appears to succeed and quietly discards a change is worse than a refusal. Nothing is applied unless everything validates.  Writing is never the default. Without `employee.manage` you may change only your own contact details, preferred name and photo — not your name, date of birth or join date, which appear on statutory filings and change by request with evidence.  Send `If-Match` with the `version` you last read to avoid overwriting a concurrent edit. 
     * Update an employee profile
     */
    async updateEmployeeProfileRaw(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmployeeProfile().'
            );
        }

        if (requestParameters['employeeUpdate'] == null) {
            throw new runtime.RequiredError(
                'employeeUpdate',
                'Required parameter "employeeUpdate" was null or undefined when calling updateEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeUpdateToJSON(requestParameters['employeeUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * PATCH rather than PUT because the caller may not be able to read every field. A PUT means \"here is the whole record\", which someone who cannot see the sensitive half is not in a position to send — they would have to echo back fields they never received, and the ones they omitted would be cleared.  A field the caller may not write is rejected with `403 FIELD_NOT_WRITABLE`, never silently dropped: a save that appears to succeed and quietly discards a change is worse than a refusal. Nothing is applied unless everything validates.  Writing is never the default. Without `employee.manage` you may change only your own contact details, preferred name and photo — not your name, date of birth or join date, which appear on statutory filings and change by request with evidence.  Send `If-Match` with the `version` you last read to avoid overwriting a concurrent edit. 
     * Update an employee profile
     */
    async updateEmployeeProfile(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.updateEmployeeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
