/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CancelExpenseClaimRequest,
  ExpenseCategoriesResponse,
  ExpenseClaimDetailResponse,
  ExpenseClaimItem,
  ExpenseClaimSubmitRequest,
  ExpenseClaimsResponse,
  ReceiptOcrRequest,
  ReceiptOcrResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CancelExpenseClaimRequestFromJSON,
    CancelExpenseClaimRequestToJSON,
    ExpenseCategoriesResponseFromJSON,
    ExpenseCategoriesResponseToJSON,
    ExpenseClaimDetailResponseFromJSON,
    ExpenseClaimDetailResponseToJSON,
    ExpenseClaimItemFromJSON,
    ExpenseClaimItemToJSON,
    ExpenseClaimSubmitRequestFromJSON,
    ExpenseClaimSubmitRequestToJSON,
    ExpenseClaimsResponseFromJSON,
    ExpenseClaimsResponseToJSON,
    ReceiptOcrRequestFromJSON,
    ReceiptOcrRequestToJSON,
    ReceiptOcrResponseFromJSON,
    ReceiptOcrResponseToJSON,
} from '../models/index';

export interface CancelExpenseClaimOperationRequest {
    id: string;
    idempotencyKey?: string;
    cancelExpenseClaimRequest?: CancelExpenseClaimRequest;
}

export interface GetMyExpenseClaimDetailsRequest {
    id: string;
}

export interface GetMyExpenseClaimsRequest {
    status?: string;
}

export interface ScanReceiptOcrRequest {
    receiptOcrRequest: ReceiptOcrRequest;
}

export interface SubmitExpenseClaimRequest {
    expenseClaimSubmitRequest: ExpenseClaimSubmitRequest;
    idempotencyKey?: string;
}

/**
 * ExpensesApi - interface
 * 
 * @export
 * @interface ExpensesApiInterface
 */
export interface ExpensesApiInterface {
    /**
     * Withdraws a submitted or draft expense claim that has not yet been approved or reimbursed.
     * @summary Cancel or withdraw a pending expense claim
     * @param {string} id 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {CancelExpenseClaimRequest} [cancelExpenseClaimRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    cancelExpenseClaimRaw(requestParameters: CancelExpenseClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimItem>>;

    /**
     * Withdraws a submitted or draft expense claim that has not yet been approved or reimbursed.
     * Cancel or withdraw a pending expense claim
     */
    cancelExpenseClaim(requestParameters: CancelExpenseClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimItem>;

    /**
     * Returns all active expense categories with per-claim spending limits, receipt requirements, and per-unit rates.
     * @summary Retrieve company expense categories and policy limits
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getExpenseCategoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseCategoriesResponse>>;

    /**
     * Returns all active expense categories with per-claim spending limits, receipt requirements, and per-unit rates.
     * Retrieve company expense categories and policy limits
     */
    getExpenseCategories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseCategoriesResponse>;

    /**
     * Returns full particulars, itemized claim lines, receipt attachments, and approval metadata.
     * @summary Retrieve expense claim details with itemized lines
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getMyExpenseClaimDetailsRaw(requestParameters: GetMyExpenseClaimDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimDetailResponse>>;

    /**
     * Returns full particulars, itemized claim lines, receipt attachments, and approval metadata.
     * Retrieve expense claim details with itemized lines
     */
    getMyExpenseClaimDetails(requestParameters: GetMyExpenseClaimDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimDetailResponse>;

    /**
     * Returns expense reimbursement claims submitted by the current authenticated employee with summary metrics.
     * @summary Retrieve employee expense claims
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getMyExpenseClaimsRaw(requestParameters: GetMyExpenseClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimsResponse>>;

    /**
     * Returns expense reimbursement claims submitted by the current authenticated employee with summary metrics.
     * Retrieve employee expense claims
     */
    getMyExpenseClaims(requestParameters: GetMyExpenseClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimsResponse>;

    /**
     * Extracts merchant name, transaction date, total amount, and suggested category from a receipt payload.
     * @summary Parse receipt image or text using OCR
     * @param {ReceiptOcrRequest} receiptOcrRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    scanReceiptOcrRaw(requestParameters: ScanReceiptOcrRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptOcrResponse>>;

    /**
     * Extracts merchant name, transaction date, total amount, and suggested category from a receipt payload.
     * Parse receipt image or text using OCR
     */
    scanReceiptOcr(requestParameters: ScanReceiptOcrRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptOcrResponse>;

    /**
     * Submits an expense claim with itemized receipts and lines for manager/finance approval.
     * @summary Submit a new multi-line expense claim
     * @param {ExpenseClaimSubmitRequest} expenseClaimSubmitRequest 
     * @param {string} [idempotencyKey] Client-generated key (UUIDv7) making the request safe to retry. Required on endpoints the offline outbox replays. Reusing a key with a different payload is rejected rather than silently returning the earlier result. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    submitExpenseClaimRaw(requestParameters: SubmitExpenseClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimDetailResponse>>;

    /**
     * Submits an expense claim with itemized receipts and lines for manager/finance approval.
     * Submit a new multi-line expense claim
     */
    submitExpenseClaim(requestParameters: SubmitExpenseClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimDetailResponse>;

}

/**
 * 
 */
export class ExpensesApi extends runtime.BaseAPI implements ExpensesApiInterface {

    /**
     * Withdraws a submitted or draft expense claim that has not yet been approved or reimbursed.
     * Cancel or withdraw a pending expense claim
     */
    async cancelExpenseClaimRaw(requestParameters: CancelExpenseClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelExpenseClaim().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/claims/{id}/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelExpenseClaimRequestToJSON(requestParameters['cancelExpenseClaimRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseClaimItemFromJSON(jsonValue));
    }

    /**
     * Withdraws a submitted or draft expense claim that has not yet been approved or reimbursed.
     * Cancel or withdraw a pending expense claim
     */
    async cancelExpenseClaim(requestParameters: CancelExpenseClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimItem> {
        const response = await this.cancelExpenseClaimRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all active expense categories with per-claim spending limits, receipt requirements, and per-unit rates.
     * Retrieve company expense categories and policy limits
     */
    async getExpenseCategoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseCategoriesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseCategoriesResponseFromJSON(jsonValue));
    }

    /**
     * Returns all active expense categories with per-claim spending limits, receipt requirements, and per-unit rates.
     * Retrieve company expense categories and policy limits
     */
    async getExpenseCategories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseCategoriesResponse> {
        const response = await this.getExpenseCategoriesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns full particulars, itemized claim lines, receipt attachments, and approval metadata.
     * Retrieve expense claim details with itemized lines
     */
    async getMyExpenseClaimDetailsRaw(requestParameters: GetMyExpenseClaimDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMyExpenseClaimDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/claims/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseClaimDetailResponseFromJSON(jsonValue));
    }

    /**
     * Returns full particulars, itemized claim lines, receipt attachments, and approval metadata.
     * Retrieve expense claim details with itemized lines
     */
    async getMyExpenseClaimDetails(requestParameters: GetMyExpenseClaimDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimDetailResponse> {
        const response = await this.getMyExpenseClaimDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns expense reimbursement claims submitted by the current authenticated employee with summary metrics.
     * Retrieve employee expense claims
     */
    async getMyExpenseClaimsRaw(requestParameters: GetMyExpenseClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/claims`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseClaimsResponseFromJSON(jsonValue));
    }

    /**
     * Returns expense reimbursement claims submitted by the current authenticated employee with summary metrics.
     * Retrieve employee expense claims
     */
    async getMyExpenseClaims(requestParameters: GetMyExpenseClaimsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimsResponse> {
        const response = await this.getMyExpenseClaimsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Extracts merchant name, transaction date, total amount, and suggested category from a receipt payload.
     * Parse receipt image or text using OCR
     */
    async scanReceiptOcrRaw(requestParameters: ScanReceiptOcrRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptOcrResponse>> {
        if (requestParameters['receiptOcrRequest'] == null) {
            throw new runtime.RequiredError(
                'receiptOcrRequest',
                'Required parameter "receiptOcrRequest" was null or undefined when calling scanReceiptOcr().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/ocr`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReceiptOcrRequestToJSON(requestParameters['receiptOcrRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptOcrResponseFromJSON(jsonValue));
    }

    /**
     * Extracts merchant name, transaction date, total amount, and suggested category from a receipt payload.
     * Parse receipt image or text using OCR
     */
    async scanReceiptOcr(requestParameters: ScanReceiptOcrRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptOcrResponse> {
        const response = await this.scanReceiptOcrRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits an expense claim with itemized receipts and lines for manager/finance approval.
     * Submit a new multi-line expense claim
     */
    async submitExpenseClaimRaw(requestParameters: SubmitExpenseClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseClaimDetailResponse>> {
        if (requestParameters['expenseClaimSubmitRequest'] == null) {
            throw new runtime.RequiredError(
                'expenseClaimSubmitRequest',
                'Required parameter "expenseClaimSubmitRequest" was null or undefined when calling submitExpenseClaim().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/expenses/claims`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExpenseClaimSubmitRequestToJSON(requestParameters['expenseClaimSubmitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseClaimDetailResponseFromJSON(jsonValue));
    }

    /**
     * Submits an expense claim with itemized receipts and lines for manager/finance approval.
     * Submit a new multi-line expense claim
     */
    async submitExpenseClaim(requestParameters: SubmitExpenseClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseClaimDetailResponse> {
        const response = await this.submitExpenseClaimRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
