/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ApplicationCreateRequest,
  ApplicationItem,
  ApplicationListResponse,
  ApplicationStageUpdateRequest,
  CandidateCreateRequest,
  CandidateItem,
  CandidateListResponse,
  InterviewItem,
  InterviewListResponse,
  InterviewScheduleRequest,
  InterviewScorecardItem,
  OfferCreateRequest,
  OfferDetail,
  ScorecardSubmitRequest,
  VacancyCreateRequest,
  VacancyItem,
  VacancyListResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ApplicationCreateRequestFromJSON,
    ApplicationCreateRequestToJSON,
    ApplicationItemFromJSON,
    ApplicationItemToJSON,
    ApplicationListResponseFromJSON,
    ApplicationListResponseToJSON,
    ApplicationStageUpdateRequestFromJSON,
    ApplicationStageUpdateRequestToJSON,
    CandidateCreateRequestFromJSON,
    CandidateCreateRequestToJSON,
    CandidateItemFromJSON,
    CandidateItemToJSON,
    CandidateListResponseFromJSON,
    CandidateListResponseToJSON,
    InterviewItemFromJSON,
    InterviewItemToJSON,
    InterviewListResponseFromJSON,
    InterviewListResponseToJSON,
    InterviewScheduleRequestFromJSON,
    InterviewScheduleRequestToJSON,
    InterviewScorecardItemFromJSON,
    InterviewScorecardItemToJSON,
    OfferCreateRequestFromJSON,
    OfferCreateRequestToJSON,
    OfferDetailFromJSON,
    OfferDetailToJSON,
    ScorecardSubmitRequestFromJSON,
    ScorecardSubmitRequestToJSON,
    VacancyCreateRequestFromJSON,
    VacancyCreateRequestToJSON,
    VacancyItemFromJSON,
    VacancyItemToJSON,
    VacancyListResponseFromJSON,
    VacancyListResponseToJSON,
} from '../models/index';

export interface CreateApplicationRequest {
    applicationCreateRequest: ApplicationCreateRequest;
}

export interface CreateApplicationOfferRequest {
    id: string;
    offerCreateRequest: OfferCreateRequest;
}

export interface CreateCandidateRequest {
    candidateCreateRequest: CandidateCreateRequest;
}

export interface CreateVacancyRequest {
    vacancyCreateRequest: VacancyCreateRequest;
}

export interface GetApplicationOfferRequest {
    id: string;
}

export interface GetApplicationsRequest {
    vacancyId?: string;
    stage?: string;
    status?: string;
}

export interface GetCandidatesRequest {
    query?: string;
}

export interface GetInterviewsRequest {
    applicationId?: string;
    interviewerEmployeeId?: string;
    status?: string;
}

export interface GetVacanciesRequest {
    status?: GetVacanciesStatusEnum;
    departmentId?: string;
}

export interface GetVacancyByIdRequest {
    id: string;
}

export interface ScheduleInterviewRequest {
    interviewScheduleRequest: InterviewScheduleRequest;
}

export interface SubmitInterviewScorecardRequest {
    id: string;
    scorecardSubmitRequest: ScorecardSubmitRequest;
}

export interface UpdateApplicationStageRequest {
    id: string;
    applicationStageUpdateRequest: ApplicationStageUpdateRequest;
}

/**
 * RecruitmentApi - interface
 * 
 * @export
 * @interface RecruitmentApiInterface
 */
export interface RecruitmentApiInterface {
    /**
     * Submits an application for a candidate to a specific job vacancy.
     * @summary Submit candidate application
     * @param {ApplicationCreateRequest} applicationCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    createApplicationRaw(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationItem>>;

    /**
     * Submits an application for a candidate to a specific job vacancy.
     * Submit candidate application
     */
    createApplication(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationItem>;

    /**
     * Creates a formal offer letter with compensation packages and joining terms.
     * @summary Create or extend employment offer
     * @param {string} id 
     * @param {OfferCreateRequest} offerCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    createApplicationOfferRaw(requestParameters: CreateApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDetail>>;

    /**
     * Creates a formal offer letter with compensation packages and joining terms.
     * Create or extend employment offer
     */
    createApplicationOffer(requestParameters: CreateApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDetail>;

    /**
     * Adds a new candidate to the ATS talent pool.
     * @summary Register candidate
     * @param {CandidateCreateRequest} candidateCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    createCandidateRaw(requestParameters: CreateCandidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CandidateItem>>;

    /**
     * Adds a new candidate to the ATS talent pool.
     * Register candidate
     */
    createCandidate(requestParameters: CreateCandidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CandidateItem>;

    /**
     * Creates a new open requisition vacancy posting.
     * @summary Create new job vacancy
     * @param {VacancyCreateRequest} vacancyCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    createVacancyRaw(requestParameters: CreateVacancyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyItem>>;

    /**
     * Creates a new open requisition vacancy posting.
     * Create new job vacancy
     */
    createVacancy(requestParameters: CreateVacancyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyItem>;

    /**
     * Retrieves employment offer terms for an application.
     * @summary Get employment offer details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getApplicationOfferRaw(requestParameters: GetApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDetail>>;

    /**
     * Retrieves employment offer terms for an application.
     * Get employment offer details
     */
    getApplicationOffer(requestParameters: GetApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDetail>;

    /**
     * Returns pipeline applications filtered by vacancy, stage, and active status.
     * @summary List candidate applications
     * @param {string} [vacancyId] 
     * @param {string} [stage] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getApplicationsRaw(requestParameters: GetApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationListResponse>>;

    /**
     * Returns pipeline applications filtered by vacancy, stage, and active status.
     * List candidate applications
     */
    getApplications(requestParameters: GetApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationListResponse>;

    /**
     * Searches candidates across talent database with optional search query.
     * @summary List candidate pool
     * @param {string} [query] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getCandidatesRaw(requestParameters: GetCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CandidateListResponse>>;

    /**
     * Searches candidates across talent database with optional search query.
     * List candidate pool
     */
    getCandidates(requestParameters: GetCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CandidateListResponse>;

    /**
     * Returns scheduled or completed interviews filtered by application or interviewer.
     * @summary List interviews
     * @param {string} [applicationId] 
     * @param {string} [interviewerEmployeeId] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getInterviewsRaw(requestParameters: GetInterviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewListResponse>>;

    /**
     * Returns scheduled or completed interviews filtered by application or interviewer.
     * List interviews
     */
    getInterviews(requestParameters: GetInterviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewListResponse>;

    /**
     * Returns job vacancies filtered by status and department.
     * @summary List job vacancies
     * @param {'DRAFT' | 'OPEN' | 'ON_HOLD' | 'CLOSED' | 'FILLED'} [status] 
     * @param {string} [departmentId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getVacanciesRaw(requestParameters: GetVacanciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyListResponse>>;

    /**
     * Returns job vacancies filtered by status and department.
     * List job vacancies
     */
    getVacancies(requestParameters: GetVacanciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyListResponse>;

    /**
     * Retrieves a specific vacancy by its unique identifier.
     * @summary Get vacancy details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    getVacancyByIdRaw(requestParameters: GetVacancyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyItem>>;

    /**
     * Retrieves a specific vacancy by its unique identifier.
     * Get vacancy details
     */
    getVacancyById(requestParameters: GetVacancyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyItem>;

    /**
     * Schedules an interview session with candidate and panel members.
     * @summary Schedule interview round
     * @param {InterviewScheduleRequest} interviewScheduleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    scheduleInterviewRaw(requestParameters: ScheduleInterviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewItem>>;

    /**
     * Schedules an interview session with candidate and panel members.
     * Schedule interview round
     */
    scheduleInterview(requestParameters: ScheduleInterviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewItem>;

    /**
     * Submits ratings, strengths, weaknesses, and hiring recommendation.
     * @summary Submit interview evaluation scorecard
     * @param {string} id 
     * @param {ScorecardSubmitRequest} scorecardSubmitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    submitInterviewScorecardRaw(requestParameters: SubmitInterviewScorecardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewScorecardItem>>;

    /**
     * Submits ratings, strengths, weaknesses, and hiring recommendation.
     * Submit interview evaluation scorecard
     */
    submitInterviewScorecard(requestParameters: SubmitInterviewScorecardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewScorecardItem>;

    /**
     * Transitions candidate application to next hiring stage.
     * @summary Update application stage
     * @param {string} id 
     * @param {ApplicationStageUpdateRequest} applicationStageUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApiInterface
     */
    updateApplicationStageRaw(requestParameters: UpdateApplicationStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationItem>>;

    /**
     * Transitions candidate application to next hiring stage.
     * Update application stage
     */
    updateApplicationStage(requestParameters: UpdateApplicationStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationItem>;

}

/**
 * 
 */
export class RecruitmentApi extends runtime.BaseAPI implements RecruitmentApiInterface {

    /**
     * Submits an application for a candidate to a specific job vacancy.
     * Submit candidate application
     */
    async createApplicationRaw(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationItem>> {
        if (requestParameters['applicationCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'applicationCreateRequest',
                'Required parameter "applicationCreateRequest" was null or undefined when calling createApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/applications`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationCreateRequestToJSON(requestParameters['applicationCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationItemFromJSON(jsonValue));
    }

    /**
     * Submits an application for a candidate to a specific job vacancy.
     * Submit candidate application
     */
    async createApplication(requestParameters: CreateApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationItem> {
        const response = await this.createApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a formal offer letter with compensation packages and joining terms.
     * Create or extend employment offer
     */
    async createApplicationOfferRaw(requestParameters: CreateApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createApplicationOffer().'
            );
        }

        if (requestParameters['offerCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'offerCreateRequest',
                'Required parameter "offerCreateRequest" was null or undefined when calling createApplicationOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/applications/{id}/offer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OfferCreateRequestToJSON(requestParameters['offerCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferDetailFromJSON(jsonValue));
    }

    /**
     * Creates a formal offer letter with compensation packages and joining terms.
     * Create or extend employment offer
     */
    async createApplicationOffer(requestParameters: CreateApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDetail> {
        const response = await this.createApplicationOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a new candidate to the ATS talent pool.
     * Register candidate
     */
    async createCandidateRaw(requestParameters: CreateCandidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CandidateItem>> {
        if (requestParameters['candidateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'candidateCreateRequest',
                'Required parameter "candidateCreateRequest" was null or undefined when calling createCandidate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/candidates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CandidateCreateRequestToJSON(requestParameters['candidateCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CandidateItemFromJSON(jsonValue));
    }

    /**
     * Adds a new candidate to the ATS talent pool.
     * Register candidate
     */
    async createCandidate(requestParameters: CreateCandidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CandidateItem> {
        const response = await this.createCandidateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new open requisition vacancy posting.
     * Create new job vacancy
     */
    async createVacancyRaw(requestParameters: CreateVacancyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyItem>> {
        if (requestParameters['vacancyCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'vacancyCreateRequest',
                'Required parameter "vacancyCreateRequest" was null or undefined when calling createVacancy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/vacancies`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VacancyCreateRequestToJSON(requestParameters['vacancyCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VacancyItemFromJSON(jsonValue));
    }

    /**
     * Creates a new open requisition vacancy posting.
     * Create new job vacancy
     */
    async createVacancy(requestParameters: CreateVacancyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyItem> {
        const response = await this.createVacancyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves employment offer terms for an application.
     * Get employment offer details
     */
    async getApplicationOfferRaw(requestParameters: GetApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfferDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getApplicationOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/applications/{id}/offer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferDetailFromJSON(jsonValue));
    }

    /**
     * Retrieves employment offer terms for an application.
     * Get employment offer details
     */
    async getApplicationOffer(requestParameters: GetApplicationOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfferDetail> {
        const response = await this.getApplicationOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns pipeline applications filtered by vacancy, stage, and active status.
     * List candidate applications
     */
    async getApplicationsRaw(requestParameters: GetApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['vacancyId'] != null) {
            queryParameters['vacancyId'] = requestParameters['vacancyId'];
        }

        if (requestParameters['stage'] != null) {
            queryParameters['stage'] = requestParameters['stage'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/applications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationListResponseFromJSON(jsonValue));
    }

    /**
     * Returns pipeline applications filtered by vacancy, stage, and active status.
     * List candidate applications
     */
    async getApplications(requestParameters: GetApplicationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationListResponse> {
        const response = await this.getApplicationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Searches candidates across talent database with optional search query.
     * List candidate pool
     */
    async getCandidatesRaw(requestParameters: GetCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CandidateListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/candidates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CandidateListResponseFromJSON(jsonValue));
    }

    /**
     * Searches candidates across talent database with optional search query.
     * List candidate pool
     */
    async getCandidates(requestParameters: GetCandidatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CandidateListResponse> {
        const response = await this.getCandidatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns scheduled or completed interviews filtered by application or interviewer.
     * List interviews
     */
    async getInterviewsRaw(requestParameters: GetInterviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['applicationId'] != null) {
            queryParameters['applicationId'] = requestParameters['applicationId'];
        }

        if (requestParameters['interviewerEmployeeId'] != null) {
            queryParameters['interviewerEmployeeId'] = requestParameters['interviewerEmployeeId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/interviews`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InterviewListResponseFromJSON(jsonValue));
    }

    /**
     * Returns scheduled or completed interviews filtered by application or interviewer.
     * List interviews
     */
    async getInterviews(requestParameters: GetInterviewsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewListResponse> {
        const response = await this.getInterviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns job vacancies filtered by status and department.
     * List job vacancies
     */
    async getVacanciesRaw(requestParameters: GetVacanciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['departmentId'] != null) {
            queryParameters['departmentId'] = requestParameters['departmentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/vacancies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VacancyListResponseFromJSON(jsonValue));
    }

    /**
     * Returns job vacancies filtered by status and department.
     * List job vacancies
     */
    async getVacancies(requestParameters: GetVacanciesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyListResponse> {
        const response = await this.getVacanciesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a specific vacancy by its unique identifier.
     * Get vacancy details
     */
    async getVacancyByIdRaw(requestParameters: GetVacancyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VacancyItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVacancyById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/vacancies/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VacancyItemFromJSON(jsonValue));
    }

    /**
     * Retrieves a specific vacancy by its unique identifier.
     * Get vacancy details
     */
    async getVacancyById(requestParameters: GetVacancyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VacancyItem> {
        const response = await this.getVacancyByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Schedules an interview session with candidate and panel members.
     * Schedule interview round
     */
    async scheduleInterviewRaw(requestParameters: ScheduleInterviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewItem>> {
        if (requestParameters['interviewScheduleRequest'] == null) {
            throw new runtime.RequiredError(
                'interviewScheduleRequest',
                'Required parameter "interviewScheduleRequest" was null or undefined when calling scheduleInterview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/interviews`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InterviewScheduleRequestToJSON(requestParameters['interviewScheduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InterviewItemFromJSON(jsonValue));
    }

    /**
     * Schedules an interview session with candidate and panel members.
     * Schedule interview round
     */
    async scheduleInterview(requestParameters: ScheduleInterviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewItem> {
        const response = await this.scheduleInterviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits ratings, strengths, weaknesses, and hiring recommendation.
     * Submit interview evaluation scorecard
     */
    async submitInterviewScorecardRaw(requestParameters: SubmitInterviewScorecardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InterviewScorecardItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling submitInterviewScorecard().'
            );
        }

        if (requestParameters['scorecardSubmitRequest'] == null) {
            throw new runtime.RequiredError(
                'scorecardSubmitRequest',
                'Required parameter "scorecardSubmitRequest" was null or undefined when calling submitInterviewScorecard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/interviews/{id}/scorecard`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScorecardSubmitRequestToJSON(requestParameters['scorecardSubmitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InterviewScorecardItemFromJSON(jsonValue));
    }

    /**
     * Submits ratings, strengths, weaknesses, and hiring recommendation.
     * Submit interview evaluation scorecard
     */
    async submitInterviewScorecard(requestParameters: SubmitInterviewScorecardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InterviewScorecardItem> {
        const response = await this.submitInterviewScorecardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Transitions candidate application to next hiring stage.
     * Update application stage
     */
    async updateApplicationStageRaw(requestParameters: UpdateApplicationStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateApplicationStage().'
            );
        }

        if (requestParameters['applicationStageUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'applicationStageUpdateRequest',
                'Required parameter "applicationStageUpdateRequest" was null or undefined when calling updateApplicationStage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/recruitment/applications/{id}/stage`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationStageUpdateRequestToJSON(requestParameters['applicationStageUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationItemFromJSON(jsonValue));
    }

    /**
     * Transitions candidate application to next hiring stage.
     * Update application stage
     */
    async updateApplicationStage(requestParameters: UpdateApplicationStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationItem> {
        const response = await this.updateApplicationStageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetVacanciesStatusEnum = {
    Draft: 'DRAFT',
    Open: 'OPEN',
    OnHold: 'ON_HOLD',
    Closed: 'CLOSED',
    Filled: 'FILLED'
} as const;
export type GetVacanciesStatusEnum = typeof GetVacanciesStatusEnum[keyof typeof GetVacanciesStatusEnum];
