/* tslint:disable */
/* eslint-disable */
/**
 * HR Platform API
 * Multi-tenant HR platform API.  **This specification is the contract.** Server interfaces and the Kotlin, Swift and TypeScript clients are all generated from it, and a breaking change to a published version fails CI. See `docs/03-architecture.md` §9.  ## Tenancy  Every request is resolved to exactly one tenant. Precedence, highest first:  1. The `tenant_id` claim in the bearer token — authoritative once authenticated. 2. The `X-Tenant-Code` header — for the unauthenticated login and org-resolve endpoints. 3. The request subdomain.  Supplying a token and a conflicting `X-Tenant-Code` is rejected with `TENANT_MISMATCH`.  ## Errors  Every non-2xx response uses one envelope. Clients localise from the machine-readable `code`, never from `message` — the server cannot reliably know the caller\'s locale, and we ship in six languages.  ## Pagination  Cursor-based everywhere. Offset pagination is not offered on tenant-scoped collections: it re-scans skipped rows and silently drops and duplicates records on concurrently-written tables such as attendance and audit.  ## Idempotency  Every unsafe method accepts an `Idempotency-Key` header and it is **required** for endpoints the mobile outbox can replay. A repeat of a key already processed returns the original response rather than applying the operation twice. 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ReferenceItem,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ReferenceItemFromJSON,
    ReferenceItemToJSON,
} from '../models/index';

export interface ListReferenceDataRequest {
    tables?: Array<string>;
}

export interface ListReferenceTableRequest {
    table: string;
    includeInactive?: boolean;
}

/**
 * ReferenceApi - interface
 * 
 * @export
 * @interface ReferenceApiInterface
 */
export interface ReferenceApiInterface {
    /**
     * The mobile clients sync these as a unit and cache them indefinitely — they change perhaps twice a year. Serving them individually would mean four round trips to render one form, which is the chattiness that makes an app feel slow regardless of how fast each call is. 
     * @summary Several reference taxonomies in one call
     * @param {Array<string>} [tables] Kebab-case taxonomy names, e.g. &#x60;blood-group&#x60;. Omit to fetch all of them.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferenceApiInterface
     */
    listReferenceDataRaw(requestParameters: ListReferenceDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<ReferenceItem>; }>>;

    /**
     * The mobile clients sync these as a unit and cache them indefinitely — they change perhaps twice a year. Serving them individually would mean four round trips to render one form, which is the chattiness that makes an app feel slow regardless of how fast each call is. 
     * Several reference taxonomies in one call
     */
    listReferenceData(requestParameters: ListReferenceDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<ReferenceItem>; }>;

    /**
     * Kebab-case taxonomy name, e.g. `employee-category`.
     * @summary One reference taxonomy
     * @param {string} table 
     * @param {boolean} [includeInactive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferenceApiInterface
     */
    listReferenceTableRaw(requestParameters: ListReferenceTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReferenceItem>>>;

    /**
     * Kebab-case taxonomy name, e.g. `employee-category`.
     * One reference taxonomy
     */
    listReferenceTable(requestParameters: ListReferenceTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReferenceItem>>;

}

/**
 * 
 */
export class ReferenceApi extends runtime.BaseAPI implements ReferenceApiInterface {

    /**
     * The mobile clients sync these as a unit and cache them indefinitely — they change perhaps twice a year. Serving them individually would mean four round trips to render one form, which is the chattiness that makes an app feel slow regardless of how fast each call is. 
     * Several reference taxonomies in one call
     */
    async listReferenceDataRaw(requestParameters: ListReferenceDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<ReferenceItem>; }>> {
        const queryParameters: any = {};

        if (requestParameters['tables'] != null) {
            queryParameters['tables'] = requestParameters['tables']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/reference`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The mobile clients sync these as a unit and cache them indefinitely — they change perhaps twice a year. Serving them individually would mean four round trips to render one form, which is the chattiness that makes an app feel slow regardless of how fast each call is. 
     * Several reference taxonomies in one call
     */
    async listReferenceData(requestParameters: ListReferenceDataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<ReferenceItem>; }> {
        const response = await this.listReferenceDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Kebab-case taxonomy name, e.g. `employee-category`.
     * One reference taxonomy
     */
    async listReferenceTableRaw(requestParameters: ListReferenceTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReferenceItem>>> {
        if (requestParameters['table'] == null) {
            throw new runtime.RequiredError(
                'table',
                'Required parameter "table" was null or undefined when calling listReferenceTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeInactive'] != null) {
            queryParameters['includeInactive'] = requestParameters['includeInactive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/reference/{table}`.replace(`{${"table"}}`, encodeURIComponent(String(requestParameters['table']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReferenceItemFromJSON));
    }

    /**
     * Kebab-case taxonomy name, e.g. `employee-category`.
     * One reference taxonomy
     */
    async listReferenceTable(requestParameters: ListReferenceTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReferenceItem>> {
        const response = await this.listReferenceTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
