//
// AddJournalEntryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddJournalEntryRequest: Codable, JSONEncodable, Hashable {

    public var entry: String

    public init(entry: String) {
        self.entry = entry
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entry
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entry, forKey: .entry)
    }
}

