//
// ApplicationListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApplicationListResponse: Codable, JSONEncodable, Hashable {

    public var items: [ApplicationItem]
    public var totalCount: Int

    public init(items: [ApplicationItem], totalCount: Int) {
        self.items = items
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

