//
// AppraisalSummaryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppraisalSummaryItem: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case notStarted = "NOT_STARTED"
        case selfReviewPending = "SELF_REVIEW_PENDING"
        case selfReviewSubmitted = "SELF_REVIEW_SUBMITTED"
        case managerReviewPending = "MANAGER_REVIEW_PENDING"
        case managerReviewSubmitted = "MANAGER_REVIEW_SUBMITTED"
        case inCalibration = "IN_CALIBRATION"
        case acknowledged = "ACKNOWLEDGED"
        case closed = "CLOSED"
    }
    public var id: UUID
    public var cycleId: UUID
    public var cycleName: String
    public var employeeId: UUID
    public var employeeName: String
    public var managerId: UUID
    public var managerName: String
    public var status: Status
    public var finalScore: Double?
    public var finalRating: String?
    public var selfReviewDeadline: Date
    public var managerReviewDeadline: Date
    public var employeeAcknowledgedAt: Date?

    public init(id: UUID, cycleId: UUID, cycleName: String, employeeId: UUID, employeeName: String, managerId: UUID, managerName: String, status: Status, finalScore: Double? = nil, finalRating: String? = nil, selfReviewDeadline: Date, managerReviewDeadline: Date, employeeAcknowledgedAt: Date? = nil) {
        self.id = id
        self.cycleId = cycleId
        self.cycleName = cycleName
        self.employeeId = employeeId
        self.employeeName = employeeName
        self.managerId = managerId
        self.managerName = managerName
        self.status = status
        self.finalScore = finalScore
        self.finalRating = finalRating
        self.selfReviewDeadline = selfReviewDeadline
        self.managerReviewDeadline = managerReviewDeadline
        self.employeeAcknowledgedAt = employeeAcknowledgedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case cycleId
        case cycleName
        case employeeId
        case employeeName
        case managerId
        case managerName
        case status
        case finalScore
        case finalRating
        case selfReviewDeadline
        case managerReviewDeadline
        case employeeAcknowledgedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(cycleId, forKey: .cycleId)
        try container.encode(cycleName, forKey: .cycleName)
        try container.encode(employeeId, forKey: .employeeId)
        try container.encode(employeeName, forKey: .employeeName)
        try container.encode(managerId, forKey: .managerId)
        try container.encode(managerName, forKey: .managerName)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(finalScore, forKey: .finalScore)
        try container.encodeIfPresent(finalRating, forKey: .finalRating)
        try container.encode(selfReviewDeadline, forKey: .selfReviewDeadline)
        try container.encode(managerReviewDeadline, forKey: .managerReviewDeadline)
        try container.encodeIfPresent(employeeAcknowledgedAt, forKey: .employeeAcknowledgedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AppraisalSummaryItem: Identifiable {}
