//
// AttendancePunchItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AttendancePunchItem: Codable, JSONEncodable, Hashable {

    public enum PunchType: String, Codable, CaseIterable {
        case _in = "IN"
        case out = "OUT"
        case breakIn = "BREAK_IN"
        case breakOut = "BREAK_OUT"
    }
    public enum GeofenceStatus: String, Codable, CaseIterable {
        case inside = "INSIDE"
        case outside = "OUTSIDE"
        case unknown = "UNKNOWN"
        case notApplicable = "NOT_APPLICABLE"
    }
    public var id: String
    public var punchType: PunchType
    public var punchedAt: Date
    public var source: String
    public var geofenceStatus: GeofenceStatus
    public var isMockLocation: Bool
    public var locationName: String?

    public init(id: String, punchType: PunchType, punchedAt: Date, source: String, geofenceStatus: GeofenceStatus, isMockLocation: Bool, locationName: String? = nil) {
        self.id = id
        self.punchType = punchType
        self.punchedAt = punchedAt
        self.source = source
        self.geofenceStatus = geofenceStatus
        self.isMockLocation = isMockLocation
        self.locationName = locationName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case punchType
        case punchedAt
        case source
        case geofenceStatus
        case isMockLocation
        case locationName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(punchType, forKey: .punchType)
        try container.encode(punchedAt, forKey: .punchedAt)
        try container.encode(source, forKey: .source)
        try container.encode(geofenceStatus, forKey: .geofenceStatus)
        try container.encode(isMockLocation, forKey: .isMockLocation)
        try container.encodeIfPresent(locationName, forKey: .locationName)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AttendancePunchItem: Identifiable {}
