//
// BenefitCategoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BenefitCategoryItem: Codable, JSONEncodable, Hashable {

    public enum BenefitKind: String, Codable, CaseIterable {
        case cash = "CASH"
        case nonCash = "NON_CASH"
        case reimbursement = "REIMBURSEMENT"
    }
    public var id: UUID
    public var code: String
    public var name: String
    public var description: String?
    public var benefitKind: BenefitKind
    public var isActive: Bool

    public init(id: UUID, code: String, name: String, description: String? = nil, benefitKind: BenefitKind, isActive: Bool) {
        self.id = id
        self.code = code
        self.name = name
        self.description = description
        self.benefitKind = benefitKind
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case name
        case description
        case benefitKind
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(benefitKind, forKey: .benefitKind)
        try container.encode(isActive, forKey: .isActive)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BenefitCategoryItem: Identifiable {}
