//
// BenefitPolicyItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BenefitPolicyItem: Codable, JSONEncodable, Hashable {

    public enum CoverageTier: String, Codable, CaseIterable {
        case individual = "INDIVIDUAL"
        case employeeAndSpouse = "EMPLOYEE_AND_SPOUSE"
        case family = "FAMILY"
    }
    public var id: UUID
    public var categoryId: UUID
    public var categoryCode: String
    public var categoryName: String
    public var code: String
    public var name: String
    public var description: String?
    public var coverageTier: CoverageTier
    public var annualLimit: Double
    public var currency: String
    public var coPayPercentage: Double
    public var deductibleAmount: Double
    public var minServiceMonths: Int
    public var eligibleGrades: String
    public var requiresReceipt: Bool
    public var isActive: Bool
    public var isEligible: Bool
    public var ineligibilityReason: String?

    public init(id: UUID, categoryId: UUID, categoryCode: String, categoryName: String, code: String, name: String, description: String? = nil, coverageTier: CoverageTier, annualLimit: Double, currency: String, coPayPercentage: Double, deductibleAmount: Double, minServiceMonths: Int, eligibleGrades: String, requiresReceipt: Bool, isActive: Bool, isEligible: Bool, ineligibilityReason: String? = nil) {
        self.id = id
        self.categoryId = categoryId
        self.categoryCode = categoryCode
        self.categoryName = categoryName
        self.code = code
        self.name = name
        self.description = description
        self.coverageTier = coverageTier
        self.annualLimit = annualLimit
        self.currency = currency
        self.coPayPercentage = coPayPercentage
        self.deductibleAmount = deductibleAmount
        self.minServiceMonths = minServiceMonths
        self.eligibleGrades = eligibleGrades
        self.requiresReceipt = requiresReceipt
        self.isActive = isActive
        self.isEligible = isEligible
        self.ineligibilityReason = ineligibilityReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case categoryId
        case categoryCode
        case categoryName
        case code
        case name
        case description
        case coverageTier
        case annualLimit
        case currency
        case coPayPercentage
        case deductibleAmount
        case minServiceMonths
        case eligibleGrades
        case requiresReceipt
        case isActive
        case isEligible
        case ineligibilityReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(categoryCode, forKey: .categoryCode)
        try container.encode(categoryName, forKey: .categoryName)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(coverageTier, forKey: .coverageTier)
        try container.encode(annualLimit, forKey: .annualLimit)
        try container.encode(currency, forKey: .currency)
        try container.encode(coPayPercentage, forKey: .coPayPercentage)
        try container.encode(deductibleAmount, forKey: .deductibleAmount)
        try container.encode(minServiceMonths, forKey: .minServiceMonths)
        try container.encode(eligibleGrades, forKey: .eligibleGrades)
        try container.encode(requiresReceipt, forKey: .requiresReceipt)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(isEligible, forKey: .isEligible)
        try container.encodeIfPresent(ineligibilityReason, forKey: .ineligibilityReason)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BenefitPolicyItem: Identifiable {}
