//
// DocumentTagItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DocumentTagItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var name: String
    public var colorHex: String?

    public init(id: UUID, name: String, colorHex: String? = nil) {
        self.id = id
        self.name = name
        self.colorHex = colorHex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case colorHex
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(colorHex, forKey: .colorHex)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DocumentTagItem: Identifiable {}
