//
// EmployeeProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A full employee record, **filtered to what the caller may see**.  Only &#x60;id&#x60; and &#x60;version&#x60; are guaranteed present. Every other property is absent when the caller lacks access to it — absent, not null, because a null would confirm the field exists and they are not allowed it, and would have clients rendering disabled inputs for values they should not know about. Clients must therefore treat every field as optional and render from what arrived, never from a fixed list.  A masked field is present as a redacted string (&#x60;••••4567&#x60;). The true value never leaves the server, so it is not in the HTTP cache, the client database, or any log capturing payloads.  &#x60;customFields&#x60; holds tenant-defined values, permission-checked individually under their own keys and described by &#x60;/v1/employees/{id}/form&#x60;. The container is omitted entirely when nothing in it is visible.  */
public struct EmployeeProfile: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pendingJoin = "PENDING_JOIN"
        case probation = "PROBATION"
        case active = "ACTIVE"
        case suspended = "SUSPENDED"
        case onNotice = "ON_NOTICE"
        case exited = "EXITED"
    }
    public var id: UUID
    /** Send back as `If-Match` on update to detect a concurrent edit. */
    public var version: Int64
    public var employeeCode: String?
    /** Read-only here. Changing it is the joiner/leaver process, which has its own approvals and side effects. */
    public var status: Status?
    public var displayName: String?
    public var firstName: String?
    public var middleName: String?
    public var lastName: String?
    public var preferredName: String?
    public var photoKey: String?
    public var titleId: UUID?
    public var dateOfBirth: Date?
    public var genderTypeId: UUID?
    public var maritalStatusId: UUID?
    public var bloodGroupId: UUID?
    public var nationalityId: UUID?
    public var religionId: UUID?
    public var raceId: UUID?
    public var workEmail: String?
    public var personalEmail: String?
    public var mobile: String?
    public var workPhone: String?
    /** Free-form because address structure is not universal. A schema with `street`, `city`, `state`, `zip` is a US postal address wearing a generic name, and it does not survive contact with a Sri Lankan or Japanese address. The keys a tenant uses come from their configured address format.  */
    public var permanentAddress: [String: AnyCodable]?
    /** Free-form because address structure is not universal. A schema with `street`, `city`, `state`, `zip` is a US postal address wearing a generic name, and it does not survive contact with a Sri Lankan or Japanese address. The keys a tenant uses come from their configured address format.  */
    public var currentAddress: [String: AnyCodable]?
    public var companyId: UUID?
    public var joinDate: Date?
    public var confirmationDate: Date?
    public var probationEndDate: Date?
    public var resignDate: Date?
    public var lastWorkingDate: Date?
    public var employmentTypeId: UUID?
    public var employeeCategoryId: UUID?
    public var employeeGroupId: UUID?
    public var statutoryClassificationId: UUID?
    public var departmentId: UUID?
    public var designationId: UUID?
    public var salaryGradeId: UUID?
    public var corporateTitleId: UUID?
    public var locationId: UUID?
    public var costCentreId: UUID?
    public var functionId: UUID?
    /** The solid reporting line. Approval routing follows this and only this. */
    public var supervisorId: UUID?
    /** Matrix reporting. Informational — never used for approval routing. */
    public var dottedLineSupervisorId: UUID?
    /** Completed years as at today, stopping at `lastWorkingDate` for a leaver. Drives service-based leave slabs and gratuity, both of which are money — hence a server-side value rather than something each client computes from `joinDate`.  */
    public var yearsOfService: Int?
    /** Tenant-defined values, keyed by field key. Omitted when none are visible. */
    public var customFields: [String: AnyCodable]?

    public init(id: UUID, version: Int64, employeeCode: String? = nil, status: Status? = nil, displayName: String? = nil, firstName: String? = nil, middleName: String? = nil, lastName: String? = nil, preferredName: String? = nil, photoKey: String? = nil, titleId: UUID? = nil, dateOfBirth: Date? = nil, genderTypeId: UUID? = nil, maritalStatusId: UUID? = nil, bloodGroupId: UUID? = nil, nationalityId: UUID? = nil, religionId: UUID? = nil, raceId: UUID? = nil, workEmail: String? = nil, personalEmail: String? = nil, mobile: String? = nil, workPhone: String? = nil, permanentAddress: [String: AnyCodable]? = nil, currentAddress: [String: AnyCodable]? = nil, companyId: UUID? = nil, joinDate: Date? = nil, confirmationDate: Date? = nil, probationEndDate: Date? = nil, resignDate: Date? = nil, lastWorkingDate: Date? = nil, employmentTypeId: UUID? = nil, employeeCategoryId: UUID? = nil, employeeGroupId: UUID? = nil, statutoryClassificationId: UUID? = nil, departmentId: UUID? = nil, designationId: UUID? = nil, salaryGradeId: UUID? = nil, corporateTitleId: UUID? = nil, locationId: UUID? = nil, costCentreId: UUID? = nil, functionId: UUID? = nil, supervisorId: UUID? = nil, dottedLineSupervisorId: UUID? = nil, yearsOfService: Int? = nil, customFields: [String: AnyCodable]? = nil) {
        self.id = id
        self.version = version
        self.employeeCode = employeeCode
        self.status = status
        self.displayName = displayName
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.preferredName = preferredName
        self.photoKey = photoKey
        self.titleId = titleId
        self.dateOfBirth = dateOfBirth
        self.genderTypeId = genderTypeId
        self.maritalStatusId = maritalStatusId
        self.bloodGroupId = bloodGroupId
        self.nationalityId = nationalityId
        self.religionId = religionId
        self.raceId = raceId
        self.workEmail = workEmail
        self.personalEmail = personalEmail
        self.mobile = mobile
        self.workPhone = workPhone
        self.permanentAddress = permanentAddress
        self.currentAddress = currentAddress
        self.companyId = companyId
        self.joinDate = joinDate
        self.confirmationDate = confirmationDate
        self.probationEndDate = probationEndDate
        self.resignDate = resignDate
        self.lastWorkingDate = lastWorkingDate
        self.employmentTypeId = employmentTypeId
        self.employeeCategoryId = employeeCategoryId
        self.employeeGroupId = employeeGroupId
        self.statutoryClassificationId = statutoryClassificationId
        self.departmentId = departmentId
        self.designationId = designationId
        self.salaryGradeId = salaryGradeId
        self.corporateTitleId = corporateTitleId
        self.locationId = locationId
        self.costCentreId = costCentreId
        self.functionId = functionId
        self.supervisorId = supervisorId
        self.dottedLineSupervisorId = dottedLineSupervisorId
        self.yearsOfService = yearsOfService
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case version
        case employeeCode
        case status
        case displayName
        case firstName
        case middleName
        case lastName
        case preferredName
        case photoKey
        case titleId
        case dateOfBirth
        case genderTypeId
        case maritalStatusId
        case bloodGroupId
        case nationalityId
        case religionId
        case raceId
        case workEmail
        case personalEmail
        case mobile
        case workPhone
        case permanentAddress
        case currentAddress
        case companyId
        case joinDate
        case confirmationDate
        case probationEndDate
        case resignDate
        case lastWorkingDate
        case employmentTypeId
        case employeeCategoryId
        case employeeGroupId
        case statutoryClassificationId
        case departmentId
        case designationId
        case salaryGradeId
        case corporateTitleId
        case locationId
        case costCentreId
        case functionId
        case supervisorId
        case dottedLineSupervisorId
        case yearsOfService
        case customFields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(version, forKey: .version)
        try container.encodeIfPresent(employeeCode, forKey: .employeeCode)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(middleName, forKey: .middleName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(preferredName, forKey: .preferredName)
        try container.encodeIfPresent(photoKey, forKey: .photoKey)
        try container.encodeIfPresent(titleId, forKey: .titleId)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(genderTypeId, forKey: .genderTypeId)
        try container.encodeIfPresent(maritalStatusId, forKey: .maritalStatusId)
        try container.encodeIfPresent(bloodGroupId, forKey: .bloodGroupId)
        try container.encodeIfPresent(nationalityId, forKey: .nationalityId)
        try container.encodeIfPresent(religionId, forKey: .religionId)
        try container.encodeIfPresent(raceId, forKey: .raceId)
        try container.encodeIfPresent(workEmail, forKey: .workEmail)
        try container.encodeIfPresent(personalEmail, forKey: .personalEmail)
        try container.encodeIfPresent(mobile, forKey: .mobile)
        try container.encodeIfPresent(workPhone, forKey: .workPhone)
        try container.encodeIfPresent(permanentAddress, forKey: .permanentAddress)
        try container.encodeIfPresent(currentAddress, forKey: .currentAddress)
        try container.encodeIfPresent(companyId, forKey: .companyId)
        try container.encodeIfPresent(joinDate, forKey: .joinDate)
        try container.encodeIfPresent(confirmationDate, forKey: .confirmationDate)
        try container.encodeIfPresent(probationEndDate, forKey: .probationEndDate)
        try container.encodeIfPresent(resignDate, forKey: .resignDate)
        try container.encodeIfPresent(lastWorkingDate, forKey: .lastWorkingDate)
        try container.encodeIfPresent(employmentTypeId, forKey: .employmentTypeId)
        try container.encodeIfPresent(employeeCategoryId, forKey: .employeeCategoryId)
        try container.encodeIfPresent(employeeGroupId, forKey: .employeeGroupId)
        try container.encodeIfPresent(statutoryClassificationId, forKey: .statutoryClassificationId)
        try container.encodeIfPresent(departmentId, forKey: .departmentId)
        try container.encodeIfPresent(designationId, forKey: .designationId)
        try container.encodeIfPresent(salaryGradeId, forKey: .salaryGradeId)
        try container.encodeIfPresent(corporateTitleId, forKey: .corporateTitleId)
        try container.encodeIfPresent(locationId, forKey: .locationId)
        try container.encodeIfPresent(costCentreId, forKey: .costCentreId)
        try container.encodeIfPresent(functionId, forKey: .functionId)
        try container.encodeIfPresent(supervisorId, forKey: .supervisorId)
        try container.encodeIfPresent(dottedLineSupervisorId, forKey: .dottedLineSupervisorId)
        try container.encodeIfPresent(yearsOfService, forKey: .yearsOfService)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeProfile: Identifiable {}
