//
// EmployeeLoanDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeLoanDetailResponse: Codable, JSONEncodable, Hashable {

    public var loan: EmployeeLoanItem
    public var schedule: [LoanRepaymentScheduleItem]

    public init(loan: EmployeeLoanItem, schedule: [LoanRepaymentScheduleItem]) {
        self.loan = loan
        self.schedule = schedule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loan
        case schedule
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(loan, forKey: .loan)
        try container.encode(schedule, forKey: .schedule)
    }
}

