//
// ExitNoticeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExitNoticeItem: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case draft = "DRAFT"
        case submitted = "SUBMITTED"
        case approved = "APPROVED"
        case rejected = "REJECTED"
        case withdrawn = "WITHDRAWN"
        case reversed = "REVERSED"
    }
    public var id: UUID
    public var noticeNumber: String
    public var employeeId: UUID
    public var employeeName: String
    public var employeeCode: String?
    public var exitTypeId: UUID
    public var exitTypeCode: String
    public var exitTypeName: String
    public var exitReasonId: UUID?
    public var exitReasonName: String?
    public var noticeDate: Date
    public var requestedLastWorkingDate: Date
    public var approvedLastWorkingDate: Date?
    public var remarks: String?
    public var status: Status
    public var approvedBy: UUID?
    public var approvedByName: String?
    public var approvedAt: Date?

    public init(id: UUID, noticeNumber: String, employeeId: UUID, employeeName: String, employeeCode: String? = nil, exitTypeId: UUID, exitTypeCode: String, exitTypeName: String, exitReasonId: UUID? = nil, exitReasonName: String? = nil, noticeDate: Date, requestedLastWorkingDate: Date, approvedLastWorkingDate: Date? = nil, remarks: String? = nil, status: Status, approvedBy: UUID? = nil, approvedByName: String? = nil, approvedAt: Date? = nil) {
        self.id = id
        self.noticeNumber = noticeNumber
        self.employeeId = employeeId
        self.employeeName = employeeName
        self.employeeCode = employeeCode
        self.exitTypeId = exitTypeId
        self.exitTypeCode = exitTypeCode
        self.exitTypeName = exitTypeName
        self.exitReasonId = exitReasonId
        self.exitReasonName = exitReasonName
        self.noticeDate = noticeDate
        self.requestedLastWorkingDate = requestedLastWorkingDate
        self.approvedLastWorkingDate = approvedLastWorkingDate
        self.remarks = remarks
        self.status = status
        self.approvedBy = approvedBy
        self.approvedByName = approvedByName
        self.approvedAt = approvedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case noticeNumber
        case employeeId
        case employeeName
        case employeeCode
        case exitTypeId
        case exitTypeCode
        case exitTypeName
        case exitReasonId
        case exitReasonName
        case noticeDate
        case requestedLastWorkingDate
        case approvedLastWorkingDate
        case remarks
        case status
        case approvedBy
        case approvedByName
        case approvedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(noticeNumber, forKey: .noticeNumber)
        try container.encode(employeeId, forKey: .employeeId)
        try container.encode(employeeName, forKey: .employeeName)
        try container.encodeIfPresent(employeeCode, forKey: .employeeCode)
        try container.encode(exitTypeId, forKey: .exitTypeId)
        try container.encode(exitTypeCode, forKey: .exitTypeCode)
        try container.encode(exitTypeName, forKey: .exitTypeName)
        try container.encodeIfPresent(exitReasonId, forKey: .exitReasonId)
        try container.encodeIfPresent(exitReasonName, forKey: .exitReasonName)
        try container.encode(noticeDate, forKey: .noticeDate)
        try container.encode(requestedLastWorkingDate, forKey: .requestedLastWorkingDate)
        try container.encodeIfPresent(approvedLastWorkingDate, forKey: .approvedLastWorkingDate)
        try container.encodeIfPresent(remarks, forKey: .remarks)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(approvedBy, forKey: .approvedBy)
        try container.encodeIfPresent(approvedByName, forKey: .approvedByName)
        try container.encodeIfPresent(approvedAt, forKey: .approvedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ExitNoticeItem: Identifiable {}
