//
// ExpenseClaimLineItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExpenseClaimLineItem: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "PENDING"
        case approved = "APPROVED"
        case rejected = "REJECTED"
    }
    public var id: UUID
    public var categoryId: UUID
    public var categoryCode: String
    public var categoryName: String
    public var expenseDate: Date
    public var description: String
    public var merchantName: String?
    public var unitQuantity: Double?
    public var amount: Double
    public var receiptKey: String?
    public var receiptUrl: String?
    public var status: Status
    public var approvedAmount: Double?
    public var rejectionReason: String?
    public var ocrExtractedSummary: String?

    public init(id: UUID, categoryId: UUID, categoryCode: String, categoryName: String, expenseDate: Date, description: String, merchantName: String? = nil, unitQuantity: Double? = nil, amount: Double, receiptKey: String? = nil, receiptUrl: String? = nil, status: Status, approvedAmount: Double? = nil, rejectionReason: String? = nil, ocrExtractedSummary: String? = nil) {
        self.id = id
        self.categoryId = categoryId
        self.categoryCode = categoryCode
        self.categoryName = categoryName
        self.expenseDate = expenseDate
        self.description = description
        self.merchantName = merchantName
        self.unitQuantity = unitQuantity
        self.amount = amount
        self.receiptKey = receiptKey
        self.receiptUrl = receiptUrl
        self.status = status
        self.approvedAmount = approvedAmount
        self.rejectionReason = rejectionReason
        self.ocrExtractedSummary = ocrExtractedSummary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case categoryId
        case categoryCode
        case categoryName
        case expenseDate
        case description
        case merchantName
        case unitQuantity
        case amount
        case receiptKey
        case receiptUrl
        case status
        case approvedAmount
        case rejectionReason
        case ocrExtractedSummary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(categoryCode, forKey: .categoryCode)
        try container.encode(categoryName, forKey: .categoryName)
        try container.encode(expenseDate, forKey: .expenseDate)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(merchantName, forKey: .merchantName)
        try container.encodeIfPresent(unitQuantity, forKey: .unitQuantity)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(receiptKey, forKey: .receiptKey)
        try container.encodeIfPresent(receiptUrl, forKey: .receiptUrl)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(approvedAmount, forKey: .approvedAmount)
        try container.encodeIfPresent(rejectionReason, forKey: .rejectionReason)
        try container.encodeIfPresent(ocrExtractedSummary, forKey: .ocrExtractedSummary)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ExpenseClaimLineItem: Identifiable {}
