//
// ExpenseClaimsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExpenseClaimsResponse: Codable, JSONEncodable, Hashable {

    public var totalClaimedAmount: Double
    public var totalApprovedAmount: Double
    public var totalReimbursedAmount: Double
    public var pendingCount: Int
    public var claims: [ExpenseClaimItem]

    public init(totalClaimedAmount: Double, totalApprovedAmount: Double, totalReimbursedAmount: Double, pendingCount: Int, claims: [ExpenseClaimItem]) {
        self.totalClaimedAmount = totalClaimedAmount
        self.totalApprovedAmount = totalApprovedAmount
        self.totalReimbursedAmount = totalReimbursedAmount
        self.pendingCount = pendingCount
        self.claims = claims
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalClaimedAmount
        case totalApprovedAmount
        case totalReimbursedAmount
        case pendingCount
        case claims
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalClaimedAmount, forKey: .totalClaimedAmount)
        try container.encode(totalApprovedAmount, forKey: .totalApprovedAmount)
        try container.encode(totalReimbursedAmount, forKey: .totalReimbursedAmount)
        try container.encode(pendingCount, forKey: .pendingCount)
        try container.encode(claims, forKey: .claims)
    }
}

