//
// ExpenseClaimLineInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExpenseClaimLineInput: Codable, JSONEncodable, Hashable {

    public var categoryId: UUID
    public var expenseDate: Date
    public var description: String
    public var merchantName: String?
    public var unitQuantity: Double?
    public var amount: Double
    public var receiptKey: String?
    public var receiptUrl: String?

    public init(categoryId: UUID, expenseDate: Date, description: String, merchantName: String? = nil, unitQuantity: Double? = nil, amount: Double, receiptKey: String? = nil, receiptUrl: String? = nil) {
        self.categoryId = categoryId
        self.expenseDate = expenseDate
        self.description = description
        self.merchantName = merchantName
        self.unitQuantity = unitQuantity
        self.amount = amount
        self.receiptKey = receiptKey
        self.receiptUrl = receiptUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId
        case expenseDate
        case description
        case merchantName
        case unitQuantity
        case amount
        case receiptKey
        case receiptUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(expenseDate, forKey: .expenseDate)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(merchantName, forKey: .merchantName)
        try container.encodeIfPresent(unitQuantity, forKey: .unitQuantity)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(receiptKey, forKey: .receiptKey)
        try container.encodeIfPresent(receiptUrl, forKey: .receiptUrl)
    }
}

