//
// GrievanceChannelsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GrievanceChannelsResponse: Codable, JSONEncodable, Hashable {

    public var channels: [GrievanceChannelItem]

    public init(channels: [GrievanceChannelItem]) {
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channels, forKey: .channels)
    }
}

