//
// GrievanceGroundItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GrievanceGroundItem: Codable, JSONEncodable, Hashable {

    public enum Severity: String, Codable, CaseIterable {
        case low = "LOW"
        case medium = "MEDIUM"
        case high = "HIGH"
        case critical = "CRITICAL"
    }
    public var id: UUID
    public var groupId: UUID
    public var groupName: String?
    public var code: String
    public var name: String
    public var description: String?
    public var severity: Severity
    public var defaultHandlerRole: String
    public var slaDays: Int

    public init(id: UUID, groupId: UUID, groupName: String? = nil, code: String, name: String, description: String? = nil, severity: Severity, defaultHandlerRole: String, slaDays: Int) {
        self.id = id
        self.groupId = groupId
        self.groupName = groupName
        self.code = code
        self.name = name
        self.description = description
        self.severity = severity
        self.defaultHandlerRole = defaultHandlerRole
        self.slaDays = slaDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case groupId
        case groupName
        case code
        case name
        case description
        case severity
        case defaultHandlerRole
        case slaDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(groupId, forKey: .groupId)
        try container.encodeIfPresent(groupName, forKey: .groupName)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(severity, forKey: .severity)
        try container.encode(defaultHandlerRole, forKey: .defaultHandlerRole)
        try container.encode(slaDays, forKey: .slaDays)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GrievanceGroundItem: Identifiable {}
