//
// HomeCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeCard: Codable, JSONEncodable, Hashable {

    public var id: String
    /** Card kind identifier. Open string rather than closed enum so new cards do not crash older clients. Known values: PENDING_APPROVALS, MILESTONES, ANNOUNCEMENTS, QUICK_ACTIONS, EXPIRING_DOCUMENTS.  */
    public var type: String
    public var title: String
    /** Lower number displays first. */
    public var priority: Int
    /** Card-specific data structure. */
    public var payload: [String: AnyCodable]

    public init(id: String, type: String, title: String, priority: Int, payload: [String: AnyCodable]) {
        self.id = id
        self.type = type
        self.title = title
        self.priority = priority
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case title
        case priority
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(priority, forKey: .priority)
        try container.encode(payload, forKey: .payload)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension HomeCard: Identifiable {}
