//
// InterviewScorecardItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InterviewScorecardItem: Codable, JSONEncodable, Hashable {

    public enum OverallRecommendation: String, Codable, CaseIterable {
        case strongHire = "STRONG_HIRE"
        case hire = "HIRE"
        case neutral = "NEUTRAL"
        case noHire = "NO_HIRE"
        case strongNoHire = "STRONG_NO_HIRE"
    }
    public var id: UUID
    public var interviewId: UUID
    public var interviewerEmployeeId: UUID
    public var interviewerName: String
    public var overallRecommendation: OverallRecommendation
    public var technicalSkillRating: Double?
    public var communicationRating: Double?
    public var problemSolvingRating: Double?
    public var culturalFitRating: Double?
    public var strengths: String?
    public var weaknesses: String?
    public var summaryNotes: String?
    public var submittedAt: Date

    public init(id: UUID, interviewId: UUID, interviewerEmployeeId: UUID, interviewerName: String, overallRecommendation: OverallRecommendation, technicalSkillRating: Double? = nil, communicationRating: Double? = nil, problemSolvingRating: Double? = nil, culturalFitRating: Double? = nil, strengths: String? = nil, weaknesses: String? = nil, summaryNotes: String? = nil, submittedAt: Date) {
        self.id = id
        self.interviewId = interviewId
        self.interviewerEmployeeId = interviewerEmployeeId
        self.interviewerName = interviewerName
        self.overallRecommendation = overallRecommendation
        self.technicalSkillRating = technicalSkillRating
        self.communicationRating = communicationRating
        self.problemSolvingRating = problemSolvingRating
        self.culturalFitRating = culturalFitRating
        self.strengths = strengths
        self.weaknesses = weaknesses
        self.summaryNotes = summaryNotes
        self.submittedAt = submittedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case interviewId
        case interviewerEmployeeId
        case interviewerName
        case overallRecommendation
        case technicalSkillRating
        case communicationRating
        case problemSolvingRating
        case culturalFitRating
        case strengths
        case weaknesses
        case summaryNotes
        case submittedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(interviewId, forKey: .interviewId)
        try container.encode(interviewerEmployeeId, forKey: .interviewerEmployeeId)
        try container.encode(interviewerName, forKey: .interviewerName)
        try container.encode(overallRecommendation, forKey: .overallRecommendation)
        try container.encodeIfPresent(technicalSkillRating, forKey: .technicalSkillRating)
        try container.encodeIfPresent(communicationRating, forKey: .communicationRating)
        try container.encodeIfPresent(problemSolvingRating, forKey: .problemSolvingRating)
        try container.encodeIfPresent(culturalFitRating, forKey: .culturalFitRating)
        try container.encodeIfPresent(strengths, forKey: .strengths)
        try container.encodeIfPresent(weaknesses, forKey: .weaknesses)
        try container.encodeIfPresent(summaryNotes, forKey: .summaryNotes)
        try container.encode(submittedAt, forKey: .submittedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension InterviewScorecardItem: Identifiable {}
