//
// InterviewScheduleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InterviewScheduleRequest: Codable, JSONEncodable, Hashable {

    public enum InterviewType: String, Codable, CaseIterable {
        case phoneScreen = "PHONE_SCREEN"
        case technical = "TECHNICAL"
        case systemDesign = "SYSTEM_DESIGN"
        case behavioral = "BEHAVIORAL"
        case hr = "HR"
        case executive = "EXECUTIVE"
    }
    public var applicationId: UUID
    public var interviewRound: Int
    public var title: String
    public var interviewType: InterviewType
    public var scheduledStart: Date
    public var scheduledEnd: Date
    public var locationOrLink: String?
    public var meetingLink: String?
    public var interviewerEmployeeIds: [UUID]
    public var notes: String?

    public init(applicationId: UUID, interviewRound: Int, title: String, interviewType: InterviewType, scheduledStart: Date, scheduledEnd: Date, locationOrLink: String? = nil, meetingLink: String? = nil, interviewerEmployeeIds: [UUID], notes: String? = nil) {
        self.applicationId = applicationId
        self.interviewRound = interviewRound
        self.title = title
        self.interviewType = interviewType
        self.scheduledStart = scheduledStart
        self.scheduledEnd = scheduledEnd
        self.locationOrLink = locationOrLink
        self.meetingLink = meetingLink
        self.interviewerEmployeeIds = interviewerEmployeeIds
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationId
        case interviewRound
        case title
        case interviewType
        case scheduledStart
        case scheduledEnd
        case locationOrLink
        case meetingLink
        case interviewerEmployeeIds
        case notes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(applicationId, forKey: .applicationId)
        try container.encode(interviewRound, forKey: .interviewRound)
        try container.encode(title, forKey: .title)
        try container.encode(interviewType, forKey: .interviewType)
        try container.encode(scheduledStart, forKey: .scheduledStart)
        try container.encode(scheduledEnd, forKey: .scheduledEnd)
        try container.encodeIfPresent(locationOrLink, forKey: .locationOrLink)
        try container.encodeIfPresent(meetingLink, forKey: .meetingLink)
        try container.encode(interviewerEmployeeIds, forKey: .interviewerEmployeeIds)
        try container.encodeIfPresent(notes, forKey: .notes)
    }
}

