//
// LeaveApprovalDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaveApprovalDetails: Codable, JSONEncodable, Hashable {

    public var leaveTypeName: String
    public var startDate: Date
    public var endDate: Date
    public var workingDays: Double
    public var reason: String
    public var employeeBalanceDays: Double
    public var teamCoverageWarning: String?

    public init(leaveTypeName: String, startDate: Date, endDate: Date, workingDays: Double, reason: String, employeeBalanceDays: Double, teamCoverageWarning: String? = nil) {
        self.leaveTypeName = leaveTypeName
        self.startDate = startDate
        self.endDate = endDate
        self.workingDays = workingDays
        self.reason = reason
        self.employeeBalanceDays = employeeBalanceDays
        self.teamCoverageWarning = teamCoverageWarning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leaveTypeName
        case startDate
        case endDate
        case workingDays
        case reason
        case employeeBalanceDays
        case teamCoverageWarning
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(leaveTypeName, forKey: .leaveTypeName)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encode(workingDays, forKey: .workingDays)
        try container.encode(reason, forKey: .reason)
        try container.encode(employeeBalanceDays, forKey: .employeeBalanceDays)
        try container.encodeIfPresent(teamCoverageWarning, forKey: .teamCoverageWarning)
    }
}

