//
// LeaveEligibilityRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaveEligibilityRequest: Codable, JSONEncodable, Hashable {

    public enum DayPortion: String, Codable, CaseIterable {
        case fullDay = "FULL_DAY"
        case firstHalf = "FIRST_HALF"
        case secondHalf = "SECOND_HALF"
    }
    public var leaveTypeId: String
    public var startDate: Date
    public var endDate: Date
    public var dayPortion: DayPortion?

    public init(leaveTypeId: String, startDate: Date, endDate: Date, dayPortion: DayPortion? = nil) {
        self.leaveTypeId = leaveTypeId
        self.startDate = startDate
        self.endDate = endDate
        self.dayPortion = dayPortion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leaveTypeId
        case startDate
        case endDate
        case dayPortion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(leaveTypeId, forKey: .leaveTypeId)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encodeIfPresent(dayPortion, forKey: .dayPortion)
    }
}

