//
// LeaveEligibilityResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaveEligibilityResponse: Codable, JSONEncodable, Hashable {

    public var eligible: Bool
    public var workingDaysRequested: Double
    public var balanceAvailable: Double
    public var remainingAfter: Double
    public var reasons: [String]
    public var days: [LeaveApplicationDayItem]?

    public init(eligible: Bool, workingDaysRequested: Double, balanceAvailable: Double, remainingAfter: Double, reasons: [String], days: [LeaveApplicationDayItem]? = nil) {
        self.eligible = eligible
        self.workingDaysRequested = workingDaysRequested
        self.balanceAvailable = balanceAvailable
        self.remainingAfter = remainingAfter
        self.reasons = reasons
        self.days = days
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eligible
        case workingDaysRequested
        case balanceAvailable
        case remainingAfter
        case reasons
        case days
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eligible, forKey: .eligible)
        try container.encode(workingDaysRequested, forKey: .workingDaysRequested)
        try container.encode(balanceAvailable, forKey: .balanceAvailable)
        try container.encode(remainingAfter, forKey: .remainingAfter)
        try container.encode(reasons, forKey: .reasons)
        try container.encodeIfPresent(days, forKey: .days)
    }
}

