//
// LoanTypeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoanTypeItem: Codable, JSONEncodable, Hashable {

    public enum InterestMethod: String, Codable, CaseIterable {
        case zeroInterest = "ZERO_INTEREST"
        case reducingBalance = "REDUCING_BALANCE"
        case flatRate = "FLAT_RATE"
    }
    public var id: UUID
    public var code: String
    public var name: String
    public var description: String?
    public var interestMethod: InterestMethod
    public var annualInterestRate: Double
    public var minTenureMonths: Int
    public var maxTenureMonths: Int
    public var minPrincipal: Double
    public var maxPrincipal: Double
    public var salaryMultipleLimit: Double
    public var minServiceMonths: Int
    public var maxActiveLoans: Int

    public init(id: UUID, code: String, name: String, description: String? = nil, interestMethod: InterestMethod, annualInterestRate: Double, minTenureMonths: Int, maxTenureMonths: Int, minPrincipal: Double, maxPrincipal: Double, salaryMultipleLimit: Double, minServiceMonths: Int, maxActiveLoans: Int) {
        self.id = id
        self.code = code
        self.name = name
        self.description = description
        self.interestMethod = interestMethod
        self.annualInterestRate = annualInterestRate
        self.minTenureMonths = minTenureMonths
        self.maxTenureMonths = maxTenureMonths
        self.minPrincipal = minPrincipal
        self.maxPrincipal = maxPrincipal
        self.salaryMultipleLimit = salaryMultipleLimit
        self.minServiceMonths = minServiceMonths
        self.maxActiveLoans = maxActiveLoans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case name
        case description
        case interestMethod
        case annualInterestRate
        case minTenureMonths
        case maxTenureMonths
        case minPrincipal
        case maxPrincipal
        case salaryMultipleLimit
        case minServiceMonths
        case maxActiveLoans
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(interestMethod, forKey: .interestMethod)
        try container.encode(annualInterestRate, forKey: .annualInterestRate)
        try container.encode(minTenureMonths, forKey: .minTenureMonths)
        try container.encode(maxTenureMonths, forKey: .maxTenureMonths)
        try container.encode(minPrincipal, forKey: .minPrincipal)
        try container.encode(maxPrincipal, forKey: .maxPrincipal)
        try container.encode(salaryMultipleLimit, forKey: .salaryMultipleLimit)
        try container.encode(minServiceMonths, forKey: .minServiceMonths)
        try container.encode(maxActiveLoans, forKey: .maxActiveLoans)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension LoanTypeItem: Identifiable {}
