//
// MeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeResponse: Codable, JSONEncodable, Hashable {

    public var userId: UUID
    public var employeeId: UUID?
    public var username: String
    public var displayName: String?
    public var email: String?
    public var photoUrl: String?
    public var locale: String?
    public var timezone: String?
    public var tenant: TenantSummary
    /** Role keys held by the user, e.g. `ADMIN`, `HR_ADMIN`. */
    public var roles: [String]
    /** Effective permission keys. The UI hides what the caller cannot do; the API enforces it regardless. */
    public var permissions: [String]
    public var enabledModules: [String]
    public var mustChangePassword: Bool?
    public var mfaEnabled: Bool?

    public init(userId: UUID, employeeId: UUID? = nil, username: String, displayName: String? = nil, email: String? = nil, photoUrl: String? = nil, locale: String? = nil, timezone: String? = nil, tenant: TenantSummary, roles: [String], permissions: [String], enabledModules: [String], mustChangePassword: Bool? = nil, mfaEnabled: Bool? = nil) {
        self.userId = userId
        self.employeeId = employeeId
        self.username = username
        self.displayName = displayName
        self.email = email
        self.photoUrl = photoUrl
        self.locale = locale
        self.timezone = timezone
        self.tenant = tenant
        self.roles = roles
        self.permissions = permissions
        self.enabledModules = enabledModules
        self.mustChangePassword = mustChangePassword
        self.mfaEnabled = mfaEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case employeeId
        case username
        case displayName
        case email
        case photoUrl
        case locale
        case timezone
        case tenant
        case roles
        case permissions
        case enabledModules
        case mustChangePassword
        case mfaEnabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(employeeId, forKey: .employeeId)
        try container.encode(username, forKey: .username)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(photoUrl, forKey: .photoUrl)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encode(tenant, forKey: .tenant)
        try container.encode(roles, forKey: .roles)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(enabledModules, forKey: .enabledModules)
        try container.encodeIfPresent(mustChangePassword, forKey: .mustChangePassword)
        try container.encodeIfPresent(mfaEnabled, forKey: .mfaEnabled)
    }
}

