//
// OnboardingTaskCompleteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OnboardingTaskCompleteRequest: Codable, JSONEncodable, Hashable {

    public var notes: String?
    public var attachmentUrl: String?

    public init(notes: String? = nil, attachmentUrl: String? = nil) {
        self.notes = notes
        self.attachmentUrl = attachmentUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notes
        case attachmentUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(attachmentUrl, forKey: .attachmentUrl)
    }
}

