//
// OnboardingProfileItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OnboardingProfileItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var code: String
    public var name: String
    public var departmentId: UUID?
    public var departmentName: String?
    public var description: String?
    public var active: Bool

    public init(id: UUID, code: String, name: String, departmentId: UUID? = nil, departmentName: String? = nil, description: String? = nil, active: Bool) {
        self.id = id
        self.code = code
        self.name = name
        self.departmentId = departmentId
        self.departmentName = departmentName
        self.description = description
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case name
        case departmentId
        case departmentName
        case description
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(departmentId, forKey: .departmentId)
        try container.encodeIfPresent(departmentName, forKey: .departmentName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(active, forKey: .active)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OnboardingProfileItem: Identifiable {}
