//
// PayslipSummaryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PayslipSummaryItem: Codable, JSONEncodable, Hashable {

    public enum PaymentStatus: String, Codable, CaseIterable {
        case paid = "PAID"
        case pending = "PENDING"
        case processing = "PROCESSING"
    }
    public var id: UUID
    public var payPeriodId: UUID
    public var periodCode: String
    public var periodName: String
    public var startDate: Date
    public var endDate: Date
    public var paymentDate: Date
    public var currency: String
    public var basicSalary: Double
    public var grossPay: Double
    public var totalDeductions: Double
    public var netPay: Double
    public var paymentStatus: PaymentStatus

    public init(id: UUID, payPeriodId: UUID, periodCode: String, periodName: String, startDate: Date, endDate: Date, paymentDate: Date, currency: String, basicSalary: Double, grossPay: Double, totalDeductions: Double, netPay: Double, paymentStatus: PaymentStatus) {
        self.id = id
        self.payPeriodId = payPeriodId
        self.periodCode = periodCode
        self.periodName = periodName
        self.startDate = startDate
        self.endDate = endDate
        self.paymentDate = paymentDate
        self.currency = currency
        self.basicSalary = basicSalary
        self.grossPay = grossPay
        self.totalDeductions = totalDeductions
        self.netPay = netPay
        self.paymentStatus = paymentStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case payPeriodId
        case periodCode
        case periodName
        case startDate
        case endDate
        case paymentDate
        case currency
        case basicSalary
        case grossPay
        case totalDeductions
        case netPay
        case paymentStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(payPeriodId, forKey: .payPeriodId)
        try container.encode(periodCode, forKey: .periodCode)
        try container.encode(periodName, forKey: .periodName)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encode(paymentDate, forKey: .paymentDate)
        try container.encode(currency, forKey: .currency)
        try container.encode(basicSalary, forKey: .basicSalary)
        try container.encode(grossPay, forKey: .grossPay)
        try container.encode(totalDeductions, forKey: .totalDeductions)
        try container.encode(netPay, forKey: .netPay)
        try container.encode(paymentStatus, forKey: .paymentStatus)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PayslipSummaryItem: Identifiable {}
