//
// PendingApprovalsPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PendingApprovalsPayload: Codable, JSONEncodable, Hashable {

    public var totalCount: Int
    public var countIsApproximate: Bool
    public var countedEntities: [CountedEntity]
    public var leaveCount: Int
    public var attendanceCount: Int
    public var claimsCount: Int
    public var actionUri: String

    public init(totalCount: Int, countIsApproximate: Bool, countedEntities: [CountedEntity], leaveCount: Int, attendanceCount: Int, claimsCount: Int, actionUri: String) {
        self.totalCount = totalCount
        self.countIsApproximate = countIsApproximate
        self.countedEntities = countedEntities
        self.leaveCount = leaveCount
        self.attendanceCount = attendanceCount
        self.claimsCount = claimsCount
        self.actionUri = actionUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case countIsApproximate
        case countedEntities
        case leaveCount
        case attendanceCount
        case claimsCount
        case actionUri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(countIsApproximate, forKey: .countIsApproximate)
        try container.encode(countedEntities, forKey: .countedEntities)
        try container.encode(leaveCount, forKey: .leaveCount)
        try container.encode(attendanceCount, forKey: .attendanceCount)
        try container.encode(claimsCount, forKey: .claimsCount)
        try container.encode(actionUri, forKey: .actionUri)
    }
}

