//
// SalaryHistoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SalaryHistoryItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var employeeId: UUID
    public var careerMovementId: UUID?
    public var effectiveFrom: Date
    public var effectiveTo: Date?
    public var baseSalary: Double
    public var currency: String
    public var changePercentage: Double?
    public var revisionReason: String
    public var isCurrent: Bool

    public init(id: UUID, employeeId: UUID, careerMovementId: UUID? = nil, effectiveFrom: Date, effectiveTo: Date? = nil, baseSalary: Double, currency: String, changePercentage: Double? = nil, revisionReason: String, isCurrent: Bool) {
        self.id = id
        self.employeeId = employeeId
        self.careerMovementId = careerMovementId
        self.effectiveFrom = effectiveFrom
        self.effectiveTo = effectiveTo
        self.baseSalary = baseSalary
        self.currency = currency
        self.changePercentage = changePercentage
        self.revisionReason = revisionReason
        self.isCurrent = isCurrent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case employeeId
        case careerMovementId
        case effectiveFrom
        case effectiveTo
        case baseSalary
        case currency
        case changePercentage
        case revisionReason
        case isCurrent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(employeeId, forKey: .employeeId)
        try container.encodeIfPresent(careerMovementId, forKey: .careerMovementId)
        try container.encode(effectiveFrom, forKey: .effectiveFrom)
        try container.encodeIfPresent(effectiveTo, forKey: .effectiveTo)
        try container.encode(baseSalary, forKey: .baseSalary)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(changePercentage, forKey: .changePercentage)
        try container.encode(revisionReason, forKey: .revisionReason)
        try container.encode(isCurrent, forKey: .isCurrent)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SalaryHistoryItem: Identifiable {}
