//
// ScorecardSubmitRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScorecardSubmitRequest: Codable, JSONEncodable, Hashable {

    public enum OverallRecommendation: String, Codable, CaseIterable {
        case strongHire = "STRONG_HIRE"
        case hire = "HIRE"
        case neutral = "NEUTRAL"
        case noHire = "NO_HIRE"
        case strongNoHire = "STRONG_NO_HIRE"
    }
    public var overallRecommendation: OverallRecommendation
    public var technicalSkillRating: Double?
    public var communicationRating: Double?
    public var problemSolvingRating: Double?
    public var culturalFitRating: Double?
    public var strengths: String?
    public var weaknesses: String?
    public var summaryNotes: String?

    public init(overallRecommendation: OverallRecommendation, technicalSkillRating: Double? = nil, communicationRating: Double? = nil, problemSolvingRating: Double? = nil, culturalFitRating: Double? = nil, strengths: String? = nil, weaknesses: String? = nil, summaryNotes: String? = nil) {
        self.overallRecommendation = overallRecommendation
        self.technicalSkillRating = technicalSkillRating
        self.communicationRating = communicationRating
        self.problemSolvingRating = problemSolvingRating
        self.culturalFitRating = culturalFitRating
        self.strengths = strengths
        self.weaknesses = weaknesses
        self.summaryNotes = summaryNotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overallRecommendation
        case technicalSkillRating
        case communicationRating
        case problemSolvingRating
        case culturalFitRating
        case strengths
        case weaknesses
        case summaryNotes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(overallRecommendation, forKey: .overallRecommendation)
        try container.encodeIfPresent(technicalSkillRating, forKey: .technicalSkillRating)
        try container.encodeIfPresent(communicationRating, forKey: .communicationRating)
        try container.encodeIfPresent(problemSolvingRating, forKey: .problemSolvingRating)
        try container.encodeIfPresent(culturalFitRating, forKey: .culturalFitRating)
        try container.encodeIfPresent(strengths, forKey: .strengths)
        try container.encodeIfPresent(weaknesses, forKey: .weaknesses)
        try container.encodeIfPresent(summaryNotes, forKey: .summaryNotes)
    }
}

