//
// SignatureAuditLogItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignatureAuditLogItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var action: String
    public var actorId: UUID?
    public var actorName: String
    public var ipAddress: String?
    public var details: String?
    public var timestamp: Date

    public init(id: UUID, action: String, actorId: UUID? = nil, actorName: String, ipAddress: String? = nil, details: String? = nil, timestamp: Date) {
        self.id = id
        self.action = action
        self.actorId = actorId
        self.actorName = actorName
        self.ipAddress = ipAddress
        self.details = details
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case action
        case actorId
        case actorName
        case ipAddress
        case details
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(actorId, forKey: .actorId)
        try container.encode(actorName, forKey: .actorName)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encode(timestamp, forKey: .timestamp)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SignatureAuditLogItem: Identifiable {}
