//
// TimesheetSaveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimesheetSaveRequest: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var employeeId: UUID?
    public var weekStartDate: Date
    public var comments: String?
    public var entries: [TimesheetEntryInput]

    public init(id: UUID? = nil, employeeId: UUID? = nil, weekStartDate: Date, comments: String? = nil, entries: [TimesheetEntryInput]) {
        self.id = id
        self.employeeId = employeeId
        self.weekStartDate = weekStartDate
        self.comments = comments
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case employeeId
        case weekStartDate
        case comments
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(employeeId, forKey: .employeeId)
        try container.encode(weekStartDate, forKey: .weekStartDate)
        try container.encodeIfPresent(comments, forKey: .comments)
        try container.encode(entries, forKey: .entries)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TimesheetSaveRequest: Identifiable {}
