//
// TimesheetProjectCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimesheetProjectCreateRequest: Codable, JSONEncodable, Hashable {

    public var clientId: UUID
    public var projectCode: String
    public var projectName: String
    public var description: String?
    public var billable: Bool = true
    public var budgetHours: Double?

    public init(clientId: UUID, projectCode: String, projectName: String, description: String? = nil, billable: Bool = true, budgetHours: Double? = nil) {
        self.clientId = clientId
        self.projectCode = projectCode
        self.projectName = projectName
        self.description = description
        self.billable = billable
        self.budgetHours = budgetHours
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId
        case projectCode
        case projectName
        case description
        case billable
        case budgetHours
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(projectCode, forKey: .projectCode)
        try container.encode(projectName, forKey: .projectName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(billable, forKey: .billable)
        try container.encodeIfPresent(budgetHours, forKey: .budgetHours)
    }
}

