//
// TrainingScheduleListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrainingScheduleListResponse: Codable, JSONEncodable, Hashable {

    public var schedules: [TrainingScheduleItem]

    public init(schedules: [TrainingScheduleItem]) {
        self.schedules = schedules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schedules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schedules, forKey: .schedules)
    }
}

