//
// TrainingScheduleItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrainingScheduleItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var courseId: UUID
    public var courseTitle: String
    public var trainerId: UUID?
    public var trainerName: String?
    public var batchCode: String
    public var startDate: Date
    public var endDate: Date
    public var venueName: String?
    public var virtualMeetingUrl: String?
    public var totalSeats: Int
    public var enrolledSeats: Int
    public var status: String
    public var costPerParticipant: Double

    public init(id: UUID, courseId: UUID, courseTitle: String, trainerId: UUID? = nil, trainerName: String? = nil, batchCode: String, startDate: Date, endDate: Date, venueName: String? = nil, virtualMeetingUrl: String? = nil, totalSeats: Int, enrolledSeats: Int, status: String, costPerParticipant: Double) {
        self.id = id
        self.courseId = courseId
        self.courseTitle = courseTitle
        self.trainerId = trainerId
        self.trainerName = trainerName
        self.batchCode = batchCode
        self.startDate = startDate
        self.endDate = endDate
        self.venueName = venueName
        self.virtualMeetingUrl = virtualMeetingUrl
        self.totalSeats = totalSeats
        self.enrolledSeats = enrolledSeats
        self.status = status
        self.costPerParticipant = costPerParticipant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case courseId
        case courseTitle
        case trainerId
        case trainerName
        case batchCode
        case startDate
        case endDate
        case venueName
        case virtualMeetingUrl
        case totalSeats
        case enrolledSeats
        case status
        case costPerParticipant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(courseId, forKey: .courseId)
        try container.encode(courseTitle, forKey: .courseTitle)
        try container.encodeIfPresent(trainerId, forKey: .trainerId)
        try container.encodeIfPresent(trainerName, forKey: .trainerName)
        try container.encode(batchCode, forKey: .batchCode)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encodeIfPresent(venueName, forKey: .venueName)
        try container.encodeIfPresent(virtualMeetingUrl, forKey: .virtualMeetingUrl)
        try container.encode(totalSeats, forKey: .totalSeats)
        try container.encode(enrolledSeats, forKey: .enrolledSeats)
        try container.encode(status, forKey: .status)
        try container.encode(costPerParticipant, forKey: .costPerParticipant)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TrainingScheduleItem: Identifiable {}
