#!/usr/bin/env node
/**
 * Renders a kustomize overlay's environment-specific values from Terraform outputs.
 *
 * ## Why this exists
 *
 * Before this script, role ARNs, the Redis host and the ECR registry were transcribed by hand
 * from `terraform output` into committed YAML, and the prod overlay carried `000000000000`
 * placeholders. That is a mistake waiting to happen: a placeholder that reaches a cluster fails
 * at pod-start with an IAM error nobody associates with a copy-paste from three weeks ago.
 *
 * ## What it does NOT do
 *
 * It writes no secrets. Every credential reaches the cluster through the External Secrets
 * Operator, from Secrets Manager. This script only handles values that are configuration —
 * hostnames, ARNs, bucket names — and it refuses to write anything that looks like a credential
 * (see FORBIDDEN_KEYS).
 *
 * ## Output is gitignored
 *
 * Deliberately, and unlike the generated API clients. These files contain account ids and
 * internal hostnames: not secret, but reconnaissance value, and inconsistent with gitignoring
 * `*.auto.tfvars` for exactly the same reason.
 *
 * The consequence is that `kustomize build` fails on a fresh checkout until this has been run.
 * That is the correct failure mode — a missing file is louder than a stale placeholder.
 *
 *   terraform -chdir=infra/terraform/environments/staging output -json > /tmp/tf.json
 *   node infra/scripts/render-overlay.mjs \
 *     --environment staging \
 *     --terraform-output /tmp/tf.json \
 *     --image 1234.dkr.ecr.ap-southeast-1.amazonaws.com/hr-backend@sha256:abc...
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')

/** Terraform outputs this script requires. A missing one is a hard failure, not a blank value. */
const REQUIRED_OUTPUTS = [
  'backend_service_account_role_arn',
  'external_secrets_role_arn',
  'redis_host',
  'kafka_bootstrap_servers',
  'opensearch_endpoint',
  's3_buckets',
]

/**
 * Substrings that must never appear in a rendered key.
 *
 * A guard against someone later adding a convenient `database_password` output and this script
 * cheerfully writing it into a ConfigMap — which is readable by anything with namespace access
 * and shows up in plain text in `kubectl describe`.
 */
const FORBIDDEN_KEYS = ['password', 'secret_string', 'token', 'private_key', 'credential']

function parseArguments(argv) {
  const args = {}
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i]?.replace(/^--/, '')
    if (key) args[key] = argv[i + 1]
  }
  return args
}

function fail(message) {
  console.error(`render-overlay: ${message}`)
  process.exit(1)
}

const args = parseArguments(process.argv.slice(2))
const environment = args.environment
const terraformOutputPath = args['terraform-output']
const image = args.image

if (!environment) fail('--environment is required (staging | prod)')
if (!terraformOutputPath) fail('--terraform-output is required (path to `terraform output -json`)')
if (!image) fail('--image is required (a digest reference, not a tag)')

// A tag can move; a digest cannot. Deploying `:latest` makes a rollback ambiguous and a rollout
// non-reproducible, so this is enforced rather than merely recommended.
if (!image.includes('@sha256:')) {
  fail(`--image must be a digest reference (repo@sha256:...), got "${image}"`)
}

let outputs
try {
  outputs = JSON.parse(readFileSync(terraformOutputPath, 'utf8'))
} catch (error) {
  fail(`could not read Terraform output JSON: ${error.message}`)
}

const missing = REQUIRED_OUTPUTS.filter((key) => outputs[key]?.value === undefined)
if (missing.length > 0) {
  fail(
    `Terraform output is missing: ${missing.join(', ')}\n` +
      '  Has `terraform apply` run for this environment?',
  )
}

for (const key of Object.keys(outputs)) {
  if (FORBIDDEN_KEYS.some((forbidden) => key.toLowerCase().includes(forbidden))) {
    fail(
      `Terraform output "${key}" looks like a credential.\n` +
        '  Secrets must reach the cluster via the External Secrets Operator, never a ConfigMap.\n' +
        '  Remove the output, or add it to the allow-list if the name is misleading.',
    )
  }
}

const value = (key) => outputs[key].value

const outputDirectory = join(REPO_ROOT, 'infra', 'k8s', 'overlays', environment, 'generated')
mkdirSync(outputDirectory, { recursive: true })

const banner = `# GENERATED by infra/scripts/render-overlay.mjs — do not edit.
# Source: terraform output for environment "${environment}".
# Regenerate rather than patching by hand; edits here are silently overwritten.`

// ---------------------------------------------------------------------------
// Non-secret configuration
// ---------------------------------------------------------------------------
const configPatch = `${banner}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-backend-config
data:
  springProfiles: "${environment}"
  redisHost: "${value('redis_host')}"
  kafkaBootstrapServers: "${value('kafka_bootstrap_servers')}"
  opensearchEndpoint: "${value('opensearch_endpoint')}"
  otlpEndpoint: "http://otel-collector.observability:4317"
  documentsBucket: "${value('s3_buckets').documents}"
  payslipsBucket: "${value('s3_buckets').payslips}"
  attachmentsBucket: "${value('s3_buckets').attachments}"
  payrollSnapshotsBucket: "${value('s3_buckets')['payroll-snapshots']}"
`

// ---------------------------------------------------------------------------
// IRSA annotations
//
// Two service accounts, two roles, deliberately separate: the backend can read
// and write objects; the External Secrets Operator can read secrets. Neither
// can do the other's job.
// ---------------------------------------------------------------------------
const serviceAccountPatch = `${banner}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-backend
  annotations:
    eks.amazonaws.com/role-arn: ${value('backend_service_account_role_arn')}
`

const externalSecretsPatch = `${banner}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: ${value('external_secrets_role_arn')}
`

// ---------------------------------------------------------------------------
// Image
//
// A kustomize component rather than an edit to kustomization.yaml, so the
// committed file stays free of environment-specific values.
// ---------------------------------------------------------------------------
const imageComponent = `${banner}
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: hr-backend
    newName: ${image.split('@')[0]}
    digest: ${image.split('@')[1]}
`

const files = {
  'config-patch.yaml': configPatch,
  'serviceaccount-patch.yaml': serviceAccountPatch,
  'external-secrets-serviceaccount-patch.yaml': externalSecretsPatch,
  'kustomization.yaml': imageComponent,
}

for (const [name, contents] of Object.entries(files)) {
  writeFileSync(join(outputDirectory, name), contents)
}

console.log(`render-overlay: wrote ${Object.keys(files).length} files to infra/k8s/overlays/${environment}/generated/`)
console.log(`  image:  ${image}`)
console.log(`  redis:  ${value('redis_host')}`)
console.log(`  backend role: ${value('backend_service_account_role_arn')}`)
