apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: hr-platform
  app.kubernetes.io/managed-by: kustomize
