/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param employeeId 
 * @param workDate 
 * @param shiftId 
 * @param isRestDay 
 */
@Serializable

data class AssignShiftPayload (

    @Contextual @SerialName(value = "employeeId")
    val employeeId: java.util.UUID,

    @Contextual @SerialName(value = "workDate")
    val workDate: java.time.LocalDate,

    @Contextual @SerialName(value = "shiftId")
    val shiftId: java.util.UUID? = null,

    @SerialName(value = "isRestDay")
    val isRestDay: kotlin.Boolean? = null

) {


}

