/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.BenefitClaimItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalClaimedAmount 
 * @param totalApprovedAmount 
 * @param totalPaidAmount 
 * @param pendingCount 
 * @param claims 
 */
@Serializable

data class BenefitClaimsResponse (

    @Contextual @SerialName(value = "totalClaimedAmount")
    val totalClaimedAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "totalApprovedAmount")
    val totalApprovedAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "totalPaidAmount")
    val totalPaidAmount: java.math.BigDecimal,

    @SerialName(value = "pendingCount")
    val pendingCount: kotlin.Int,

    @SerialName(value = "claims")
    val claims: kotlin.collections.List<BenefitClaimItem>

) {


}

