/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param name 
 * @param countryCode 
 * @param defaultCurrency 
 * @param legalName 
 * @param timezone 
 * @param locale 
 * @param dataRegion 
 * @param isolationTier 
 * @param subscriptionPlan 
 * @param adminEmail 
 * @param modules 
 */
@Serializable

data class CreateTenantPayload (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "countryCode")
    val countryCode: kotlin.String,

    @SerialName(value = "defaultCurrency")
    val defaultCurrency: kotlin.String,

    @SerialName(value = "legalName")
    val legalName: kotlin.String? = null,

    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @SerialName(value = "dataRegion")
    val dataRegion: kotlin.String? = null,

    @SerialName(value = "isolationTier")
    val isolationTier: CreateTenantPayload.IsolationTier? = null,

    @SerialName(value = "subscriptionPlan")
    val subscriptionPlan: kotlin.String? = null,

    @SerialName(value = "adminEmail")
    val adminEmail: kotlin.String? = null,

    @SerialName(value = "modules")
    val modules: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

) {

    /**
     * 
     *
     * Values: SHARED,DEDICATED_SCHEMA,DEDICATED_DATABASE
     */
    @Serializable
    enum class IsolationTier(val value: kotlin.String) {
        @SerialName(value = "SHARED") SHARED("SHARED"),
        @SerialName(value = "DEDICATED_SCHEMA") DEDICATED_SCHEMA("DEDICATED_SCHEMA"),
        @SerialName(value = "DEDICATED_DATABASE") DEDICATED_DATABASE("DEDICATED_DATABASE");
    }

}

