/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param serialNumber 
 * @param vendor 
 * @param modelName 
 * @param ipAddress 
 * @param port 
 * @param locationName 
 * @param direction 
 */
@Serializable

data class CreateBiometricDevicePayload (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "serialNumber")
    val serialNumber: kotlin.String,

    @SerialName(value = "vendor")
    val vendor: kotlin.String? = null,

    @SerialName(value = "modelName")
    val modelName: kotlin.String? = null,

    @SerialName(value = "ipAddress")
    val ipAddress: kotlin.String? = null,

    @SerialName(value = "port")
    val port: kotlin.Int? = null,

    @SerialName(value = "locationName")
    val locationName: kotlin.String? = null,

    @SerialName(value = "direction")
    val direction: kotlin.String? = null

) {


}

