/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param incidentNumber 
 * @param employeeId 
 * @param employeeName 
 * @param reportedByEmployeeId 
 * @param reportedByEmployeeName 
 * @param typeCode 
 * @param typeName 
 * @param incidentDate 
 * @param description 
 * @param severity 
 * @param status 
 * @param createdAt 
 * @param subtypeName 
 * @param location 
 */
@Serializable

data class DisciplinaryIncidentItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "incidentNumber")
    val incidentNumber: kotlin.String,

    @Contextual @SerialName(value = "employeeId")
    val employeeId: java.util.UUID,

    @SerialName(value = "employeeName")
    val employeeName: kotlin.String,

    @Contextual @SerialName(value = "reportedByEmployeeId")
    val reportedByEmployeeId: java.util.UUID,

    @SerialName(value = "reportedByEmployeeName")
    val reportedByEmployeeName: kotlin.String,

    @SerialName(value = "typeCode")
    val typeCode: kotlin.String,

    @SerialName(value = "typeName")
    val typeName: kotlin.String,

    @Contextual @SerialName(value = "incidentDate")
    val incidentDate: java.time.LocalDate,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "severity")
    val severity: DisciplinaryIncidentItem.Severity,

    @SerialName(value = "status")
    val status: DisciplinaryIncidentItem.Status,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "subtypeName")
    val subtypeName: kotlin.String? = null,

    @SerialName(value = "location")
    val location: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: LOW,MEDIUM,HIGH,CRITICAL
     */
    @Serializable
    enum class Severity(val value: kotlin.String) {
        @SerialName(value = "LOW") LOW("LOW"),
        @SerialName(value = "MEDIUM") MEDIUM("MEDIUM"),
        @SerialName(value = "HIGH") HIGH("HIGH"),
        @SerialName(value = "CRITICAL") CRITICAL("CRITICAL");
    }
    /**
     * 
     *
     * Values: REPORTED,UNDER_INVESTIGATION,ACTION_PROPOSED,ACTION_ISSUED,APPEALED,CONCLUDED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "REPORTED") REPORTED("REPORTED"),
        @SerialName(value = "UNDER_INVESTIGATION") UNDER_INVESTIGATION("UNDER_INVESTIGATION"),
        @SerialName(value = "ACTION_PROPOSED") ACTION_PROPOSED("ACTION_PROPOSED"),
        @SerialName(value = "ACTION_ISSUED") ACTION_ISSUED("ACTION_ISSUED"),
        @SerialName(value = "APPEALED") APPEALED("APPEALED"),
        @SerialName(value = "CONCLUDED") CONCLUDED("CONCLUDED");
    }

}

