/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param accessLevel 
 * @param description 
 * @param icon 
 * @param parentFolderId 
 */
@Serializable

data class DocumentFolderCreateRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "accessLevel")
    val accessLevel: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "icon")
    val icon: kotlin.String? = null,

    @Contextual @SerialName(value = "parentFolderId")
    val parentFolderId: java.util.UUID? = null

) {


}

