/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.CompanyDocumentItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param documents 
 */
@Serializable

data class DocumentListResponse (

    @SerialName(value = "documents")
    val documents: kotlin.collections.List<CompanyDocumentItem>

) {


}

