/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.EmployeeLoanItem
import com.hr.client.model.LoanRepaymentScheduleItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param loan 
 * @param schedule 
 */
@Serializable

data class EmployeeLoanDetailResponse (

    @SerialName(value = "loan")
    val loan: EmployeeLoanItem,

    @SerialName(value = "schedule")
    val schedule: kotlin.collections.List<LoanRepaymentScheduleItem>

) {


}

