/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param loanCode 
 * @param loanTypeId 
 * @param loanTypeCode 
 * @param loanTypeName 
 * @param principalAmount 
 * @param interestMethod 
 * @param annualInterestRate 
 * @param tenureMonths 
 * @param monthlyInstallment 
 * @param totalInterest 
 * @param totalRepayable 
 * @param totalRepaid 
 * @param remainingBalance 
 * @param reason 
 * @param status 
 * @param disbursedDate 
 * @param settledDate 
 */
@Serializable

data class EmployeeLoanItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "loanCode")
    val loanCode: kotlin.String,

    @Contextual @SerialName(value = "loanTypeId")
    val loanTypeId: java.util.UUID,

    @SerialName(value = "loanTypeCode")
    val loanTypeCode: kotlin.String,

    @SerialName(value = "loanTypeName")
    val loanTypeName: kotlin.String,

    @Contextual @SerialName(value = "principalAmount")
    val principalAmount: java.math.BigDecimal,

    @SerialName(value = "interestMethod")
    val interestMethod: EmployeeLoanItem.InterestMethod,

    @Contextual @SerialName(value = "annualInterestRate")
    val annualInterestRate: java.math.BigDecimal,

    @SerialName(value = "tenureMonths")
    val tenureMonths: kotlin.Int,

    @Contextual @SerialName(value = "monthlyInstallment")
    val monthlyInstallment: java.math.BigDecimal,

    @Contextual @SerialName(value = "totalInterest")
    val totalInterest: java.math.BigDecimal,

    @Contextual @SerialName(value = "totalRepayable")
    val totalRepayable: java.math.BigDecimal,

    @Contextual @SerialName(value = "totalRepaid")
    val totalRepaid: java.math.BigDecimal,

    @Contextual @SerialName(value = "remainingBalance")
    val remainingBalance: java.math.BigDecimal,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "status")
    val status: EmployeeLoanItem.Status,

    @Contextual @SerialName(value = "disbursedDate")
    val disbursedDate: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "settledDate")
    val settledDate: java.time.LocalDate? = null

) {

    /**
     * 
     *
     * Values: ZERO_INTEREST,REDUCING_BALANCE,FLAT_RATE
     */
    @Serializable
    enum class InterestMethod(val value: kotlin.String) {
        @SerialName(value = "ZERO_INTEREST") ZERO_INTEREST("ZERO_INTEREST"),
        @SerialName(value = "REDUCING_BALANCE") REDUCING_BALANCE("REDUCING_BALANCE"),
        @SerialName(value = "FLAT_RATE") FLAT_RATE("FLAT_RATE");
    }
    /**
     * 
     *
     * Values: SUBMITTED,APPROVED,ACTIVE,SETTLED,REJECTED,CANCELLED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "SUBMITTED") SUBMITTED("SUBMITTED"),
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "SETTLED") SETTLED("SETTLED"),
        @SerialName(value = "REJECTED") REJECTED("REJECTED"),
        @SerialName(value = "CANCELLED") CANCELLED("CANCELLED");
    }

}

