/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.BenefitDependentItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param policyId 
 * @param policyCode 
 * @param policyName 
 * @param categoryName 
 * @param coverageTier 
 * @param policyNumber 
 * @param enrollmentYear 
 * @param startDate 
 * @param endDate 
 * @param annualEntitlement 
 * @param usedAmount 
 * @param pendingAmount 
 * @param remainingBalance 
 * @param currency 
 * @param status 
 * @param dependents 
 */
@Serializable

data class EmployeeBenefitEnrollmentItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "policyId")
    val policyId: java.util.UUID,

    @SerialName(value = "policyCode")
    val policyCode: kotlin.String,

    @SerialName(value = "policyName")
    val policyName: kotlin.String,

    @SerialName(value = "categoryName")
    val categoryName: kotlin.String,

    @SerialName(value = "coverageTier")
    val coverageTier: EmployeeBenefitEnrollmentItem.CoverageTier,

    @SerialName(value = "policyNumber")
    val policyNumber: kotlin.String,

    @SerialName(value = "enrollmentYear")
    val enrollmentYear: kotlin.Int,

    @Contextual @SerialName(value = "startDate")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "endDate")
    val endDate: java.time.LocalDate,

    @Contextual @SerialName(value = "annualEntitlement")
    val annualEntitlement: java.math.BigDecimal,

    @Contextual @SerialName(value = "usedAmount")
    val usedAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "pendingAmount")
    val pendingAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "remainingBalance")
    val remainingBalance: java.math.BigDecimal,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "status")
    val status: EmployeeBenefitEnrollmentItem.Status,

    @SerialName(value = "dependents")
    val dependents: kotlin.collections.List<BenefitDependentItem>

) {

    /**
     * 
     *
     * Values: INDIVIDUAL,EMPLOYEE_AND_SPOUSE,FAMILY
     */
    @Serializable
    enum class CoverageTier(val value: kotlin.String) {
        @SerialName(value = "INDIVIDUAL") INDIVIDUAL("INDIVIDUAL"),
        @SerialName(value = "EMPLOYEE_AND_SPOUSE") EMPLOYEE_AND_SPOUSE("EMPLOYEE_AND_SPOUSE"),
        @SerialName(value = "FAMILY") FAMILY("FAMILY");
    }
    /**
     * 
     *
     * Values: ACTIVE,SUSPENDED,EXPIRED,TERMINATED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "SUSPENDED") SUSPENDED("SUSPENDED"),
        @SerialName(value = "EXPIRED") EXPIRED("EXPIRED"),
        @SerialName(value = "TERMINATED") TERMINATED("TERMINATED");
    }

}

