/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param exitTypeId 
 * @param requestedLastWorkingDate 
 * @param exitReasonId 
 * @param noticeDate 
 * @param remarks 
 */
@Serializable

data class ExitNoticeCreateRequest (

    @Contextual @SerialName(value = "exitTypeId")
    val exitTypeId: java.util.UUID,

    @Contextual @SerialName(value = "requestedLastWorkingDate")
    val requestedLastWorkingDate: java.time.LocalDate,

    @Contextual @SerialName(value = "exitReasonId")
    val exitReasonId: java.util.UUID? = null,

    @Contextual @SerialName(value = "noticeDate")
    val noticeDate: java.time.LocalDate? = null,

    @SerialName(value = "remarks")
    val remarks: kotlin.String? = null

) {


}

