/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param categoryId 
 * @param expenseDate 
 * @param description 
 * @param amount 
 * @param merchantName 
 * @param unitQuantity 
 * @param receiptKey 
 * @param receiptUrl 
 */
@Serializable

data class ExpenseClaimLineInput (

    @Contextual @SerialName(value = "categoryId")
    val categoryId: java.util.UUID,

    @Contextual @SerialName(value = "expenseDate")
    val expenseDate: java.time.LocalDate,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    @SerialName(value = "merchantName")
    val merchantName: kotlin.String? = null,

    @Contextual @SerialName(value = "unitQuantity")
    val unitQuantity: java.math.BigDecimal? = null,

    @SerialName(value = "receiptKey")
    val receiptKey: kotlin.String? = null,

    @SerialName(value = "receiptUrl")
    val receiptUrl: kotlin.String? = null

) {


}

