/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param claimNumber 
 * @param title 
 * @param claimDate 
 * @param currency 
 * @param totalAmount 
 * @param status 
 * @param lineCount 
 * @param approvedAmount 
 * @param rejectionReason 
 * @param approvedAt 
 * @param reimbursedAt 
 * @param remarks 
 */
@Serializable

data class ExpenseClaimItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "claimNumber")
    val claimNumber: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @Contextual @SerialName(value = "claimDate")
    val claimDate: java.time.LocalDate,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @Contextual @SerialName(value = "totalAmount")
    val totalAmount: java.math.BigDecimal,

    @SerialName(value = "status")
    val status: ExpenseClaimItem.Status,

    @SerialName(value = "lineCount")
    val lineCount: kotlin.Int,

    @Contextual @SerialName(value = "approvedAmount")
    val approvedAmount: java.math.BigDecimal? = null,

    @SerialName(value = "rejectionReason")
    val rejectionReason: kotlin.String? = null,

    @Contextual @SerialName(value = "approvedAt")
    val approvedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "reimbursedAt")
    val reimbursedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "remarks")
    val remarks: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: DRAFT,SUBMITTED,UNDER_REVIEW,APPROVED,REJECTED,REIMBURSED,CANCELLED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "DRAFT") DRAFT("DRAFT"),
        @SerialName(value = "SUBMITTED") SUBMITTED("SUBMITTED"),
        @SerialName(value = "UNDER_REVIEW") UNDER_REVIEW("UNDER_REVIEW"),
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "REJECTED") REJECTED("REJECTED"),
        @SerialName(value = "REIMBURSED") REIMBURSED("REIMBURSED"),
        @SerialName(value = "CANCELLED") CANCELLED("CANCELLED");
    }

}

