/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param goalId 
 * @param rating 
 * @param comments 
 */
@Serializable

data class GoalRatingInput (

    @Contextual @SerialName(value = "goalId")
    val goalId: java.util.UUID,

    @Contextual @SerialName(value = "rating")
    val rating: java.math.BigDecimal,

    @SerialName(value = "comments")
    val comments: kotlin.String? = null

) {


}

