/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param groupId 
 * @param code 
 * @param name 
 * @param severity 
 * @param defaultHandlerRole 
 * @param slaDays 
 * @param groupName 
 * @param description 
 */
@Serializable

data class GrievanceGroundItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "groupId")
    val groupId: java.util.UUID,

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "severity")
    val severity: GrievanceGroundItem.Severity,

    @SerialName(value = "defaultHandlerRole")
    val defaultHandlerRole: kotlin.String,

    @SerialName(value = "slaDays")
    val slaDays: kotlin.Int,

    @SerialName(value = "groupName")
    val groupName: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: LOW,MEDIUM,HIGH,CRITICAL
     */
    @Serializable
    enum class Severity(val value: kotlin.String) {
        @SerialName(value = "LOW") LOW("LOW"),
        @SerialName(value = "MEDIUM") MEDIUM("MEDIUM"),
        @SerialName(value = "HIGH") HIGH("HIGH"),
        @SerialName(value = "CRITICAL") CRITICAL("CRITICAL");
    }

}

