/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param grievanceId 
 * @param reason 
 * @param appealedAt 
 * @param status 
 * @param outcome 
 * @param reviewedAt 
 */
@Serializable

data class GrievanceAppealItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "grievanceId")
    val grievanceId: java.util.UUID,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @Contextual @SerialName(value = "appealedAt")
    val appealedAt: java.time.OffsetDateTime,

    @SerialName(value = "status")
    val status: GrievanceAppealItem.Status,

    @SerialName(value = "outcome")
    val outcome: kotlin.String? = null,

    @Contextual @SerialName(value = "reviewedAt")
    val reviewedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: PENDING,UPHELD,MODIFIED,DISMISSED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "PENDING") PENDING("PENDING"),
        @SerialName(value = "UPHELD") UPHELD("UPHELD"),
        @SerialName(value = "MODIFIED") MODIFIED("MODIFIED"),
        @SerialName(value = "DISMISSED") DISMISSED("DISMISSED");
    }

}

