/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.InterviewScorecardItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param applicationId 
 * @param candidateName 
 * @param vacancyTitle 
 * @param interviewRound 
 * @param title 
 * @param interviewType 
 * @param scheduledStart 
 * @param scheduledEnd 
 * @param status 
 * @param interviewerEmployeeIds 
 * @param scorecards 
 * @param locationOrLink 
 * @param meetingLink 
 * @param notes 
 */
@Serializable

data class InterviewItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "applicationId")
    val applicationId: java.util.UUID,

    @SerialName(value = "candidateName")
    val candidateName: kotlin.String,

    @SerialName(value = "vacancyTitle")
    val vacancyTitle: kotlin.String,

    @SerialName(value = "interviewRound")
    val interviewRound: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "interviewType")
    val interviewType: InterviewItem.InterviewType,

    @Contextual @SerialName(value = "scheduledStart")
    val scheduledStart: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "scheduledEnd")
    val scheduledEnd: java.time.OffsetDateTime,

    @SerialName(value = "status")
    val status: InterviewItem.Status,

    @SerialName(value = "interviewerEmployeeIds")
    val interviewerEmployeeIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "scorecards")
    val scorecards: kotlin.collections.List<InterviewScorecardItem>,

    @SerialName(value = "locationOrLink")
    val locationOrLink: kotlin.String? = null,

    @SerialName(value = "meetingLink")
    val meetingLink: kotlin.String? = null,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: PHONE_SCREEN,TECHNICAL,SYSTEM_DESIGN,BEHAVIORAL,HR,EXECUTIVE
     */
    @Serializable
    enum class InterviewType(val value: kotlin.String) {
        @SerialName(value = "PHONE_SCREEN") PHONE_SCREEN("PHONE_SCREEN"),
        @SerialName(value = "TECHNICAL") TECHNICAL("TECHNICAL"),
        @SerialName(value = "SYSTEM_DESIGN") SYSTEM_DESIGN("SYSTEM_DESIGN"),
        @SerialName(value = "BEHAVIORAL") BEHAVIORAL("BEHAVIORAL"),
        @SerialName(value = "HR") HR("HR"),
        @SerialName(value = "EXECUTIVE") EXECUTIVE("EXECUTIVE");
    }
    /**
     * 
     *
     * Values: SCHEDULED,COMPLETED,CANCELLED,RESCHEDULED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "SCHEDULED") SCHEDULED("SCHEDULED"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "CANCELLED") CANCELLED("CANCELLED"),
        @SerialName(value = "RESCHEDULED") RESCHEDULED("RESCHEDULED");
    }

}

