/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.Jwk

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A JSON Web Key Set as defined by RFC 7517 §5.
 *
 * @param propertyKeys 
 */
@Serializable

data class JwkSet (

    @SerialName(value = "keys")
    val propertyKeys: kotlin.collections.List<Jwk>

) {


}

