/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param leaveTypeId 
 * @param startDate 
 * @param endDate 
 * @param reason 
 * @param dayPortion 
 */
@Serializable

data class LeaveApplicationRequest (

    @SerialName(value = "leaveTypeId")
    val leaveTypeId: kotlin.String,

    @Contextual @SerialName(value = "startDate")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "endDate")
    val endDate: java.time.LocalDate,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "dayPortion")
    val dayPortion: LeaveApplicationRequest.DayPortion? = null

) {

    /**
     * 
     *
     * Values: FULL_DAY,FIRST_HALF,SECOND_HALF
     */
    @Serializable
    enum class DayPortion(val value: kotlin.String) {
        @SerialName(value = "FULL_DAY") FULL_DAY("FULL_DAY"),
        @SerialName(value = "FIRST_HALF") FIRST_HALF("FIRST_HALF"),
        @SerialName(value = "SECOND_HALF") SECOND_HALF("SECOND_HALF");
    }

}

