/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.HomeCard

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cards 
 * @param syncCursor Opaque sync cursor for the home scope.
 */
@Serializable

data class MobileHomeResponse (

    @SerialName(value = "cards")
    val cards: kotlin.collections.List<HomeCard>,

    /* Opaque sync cursor for the home scope. */
    @SerialName(value = "syncCursor")
    val syncCursor: kotlin.String? = null

) {


}

