/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.PayslipComparisonLine

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currentPeriodCode 
 * @param priorPeriodCode 
 * @param currentGross 
 * @param priorGross 
 * @param grossVariance 
 * @param grossVariancePercent 
 * @param currentNet 
 * @param priorNet 
 * @param netVariance 
 * @param netVariancePercent 
 * @param lines 
 */
@Serializable

data class PayslipComparisonResponse (

    @SerialName(value = "currentPeriodCode")
    val currentPeriodCode: kotlin.String,

    @SerialName(value = "priorPeriodCode")
    val priorPeriodCode: kotlin.String,

    @Contextual @SerialName(value = "currentGross")
    val currentGross: java.math.BigDecimal,

    @Contextual @SerialName(value = "priorGross")
    val priorGross: java.math.BigDecimal,

    @Contextual @SerialName(value = "grossVariance")
    val grossVariance: java.math.BigDecimal,

    @Contextual @SerialName(value = "grossVariancePercent")
    val grossVariancePercent: java.math.BigDecimal,

    @Contextual @SerialName(value = "currentNet")
    val currentNet: java.math.BigDecimal,

    @Contextual @SerialName(value = "priorNet")
    val priorNet: java.math.BigDecimal,

    @Contextual @SerialName(value = "netVariance")
    val netVariance: java.math.BigDecimal,

    @Contextual @SerialName(value = "netVariancePercent")
    val netVariancePercent: java.math.BigDecimal,

    @SerialName(value = "lines")
    val lines: kotlin.collections.List<PayslipComparisonLine>

) {


}

