/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemCode 
 * @param itemName 
 * @param category 
 * @param currentAmount 
 * @param priorAmount 
 * @param varianceAmount 
 * @param variancePercent 
 */
@Serializable

data class PayslipComparisonLine (

    @SerialName(value = "itemCode")
    val itemCode: kotlin.String,

    @SerialName(value = "itemName")
    val itemName: kotlin.String,

    @SerialName(value = "category")
    val category: kotlin.String,

    @Contextual @SerialName(value = "currentAmount")
    val currentAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "priorAmount")
    val priorAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "varianceAmount")
    val varianceAmount: java.math.BigDecimal,

    @Contextual @SerialName(value = "variancePercent")
    val variancePercent: java.math.BigDecimal

) {


}

