/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param startAt Local wall-clock time. A `startAt` after `endAt` is a window crossing midnight.
 * @param endAt 
 * @param timezone IANA zone name, not an offset. An offset is wrong twice a year wherever daylight saving applies, and the symptom is notifications arriving an hour into the night for months. Rejected with `VALIDATION_FAILED` if the server cannot resolve it. 
 * @param days Weekdays the window applies to, 1 = Monday. Empty means every day. For a window crossing midnight the day is the one the window *opened* on, so `[5]` with 22:00–07:00 covers Friday night into Saturday morning. 
 * @param enabled 
 */
@Serializable

data class QuietHoursSettings (

    /* Local wall-clock time. A `startAt` after `endAt` is a window crossing midnight. */
    @SerialName(value = "startAt")
    val startAt: kotlin.String,

    @SerialName(value = "endAt")
    val endAt: kotlin.String,

    /* IANA zone name, not an offset. An offset is wrong twice a year wherever daylight saving applies, and the symptom is notifications arriving an hour into the night for months. Rejected with `VALIDATION_FAILED` if the server cannot resolve it.  */
    @SerialName(value = "timezone")
    val timezone: kotlin.String,

    /* Weekdays the window applies to, 1 = Monday. Empty means every day. For a window crossing midnight the day is the one the window *opened* on, so `[5]` with 22:00–07:00 covers Friday night into Saturday morning.  */
    @SerialName(value = "days")
    val days: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = true

) {


}

