/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param employeeId 
 * @param employeeCode 
 * @param employeeName 
 * @param department 
 * @param punchedAt 
 * @param punchType 
 * @param source 
 * @param geofenceStatus 
 * @param isMockLocation 
 * @param recordedOffline 
 * @param syncedAt 
 * @param deviceId 
 * @param locationName 
 */
@Serializable

data class RawPunchAdmin (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "employeeId")
    val employeeId: java.util.UUID,

    @SerialName(value = "employeeCode")
    val employeeCode: kotlin.String,

    @SerialName(value = "employeeName")
    val employeeName: kotlin.String,

    @SerialName(value = "department")
    val department: kotlin.String,

    @Contextual @SerialName(value = "punchedAt")
    val punchedAt: java.time.OffsetDateTime,

    @SerialName(value = "punchType")
    val punchType: kotlin.String,

    @SerialName(value = "source")
    val source: kotlin.String,

    @SerialName(value = "geofenceStatus")
    val geofenceStatus: kotlin.String,

    @SerialName(value = "isMockLocation")
    val isMockLocation: kotlin.Boolean,

    @SerialName(value = "recordedOffline")
    val recordedOffline: kotlin.Boolean,

    @Contextual @SerialName(value = "syncedAt")
    val syncedAt: java.time.OffsetDateTime,

    @SerialName(value = "deviceId")
    val deviceId: kotlin.String? = null,

    @SerialName(value = "locationName")
    val locationName: kotlin.String? = null

) {


}

