/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param message 
 */
@Serializable

data class ResetPasswordResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "message")
    val message: kotlin.String

) {


}

