/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param name 
 * @param authMethods Which sign-in methods this organisation offers, so the client renders the right form.
 * @param logoUrl 
 * @param brandColor 
 * @param locale 
 * @param ssoRedirectUrl 
 */
@Serializable

data class ResolveTenantResponse (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* Which sign-in methods this organisation offers, so the client renders the right form. */
    @SerialName(value = "authMethods")
    val authMethods: kotlin.collections.List<ResolveTenantResponse.AuthMethods>,

    @Contextual @SerialName(value = "logoUrl")
    val logoUrl: java.net.URI? = null,

    @SerialName(value = "brandColor")
    val brandColor: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @Contextual @SerialName(value = "ssoRedirectUrl")
    val ssoRedirectUrl: java.net.URI? = null

) {

    /**
     * Which sign-in methods this organisation offers, so the client renders the right form.
     *
     * Values: PASSWORD,SSO_SAML,SSO_OIDC
     */
    @Serializable
    enum class AuthMethods(val value: kotlin.String) {
        @SerialName(value = "PASSWORD") PASSWORD("PASSWORD"),
        @SerialName(value = "SSO_SAML") SSO_SAML("SSO_SAML"),
        @SerialName(value = "SSO_OIDC") SSO_OIDC("SSO_OIDC");
    }

}

