/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.RosterEmployeeItem
import com.hr.client.model.RosterWeekDay
import com.hr.client.model.ShiftScheduleItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param days 
 * @param schedules 
 * @param employees 
 */
@Serializable

data class RosterResponse (

    @SerialName(value = "days")
    val days: kotlin.collections.List<RosterWeekDay>,

    @SerialName(value = "schedules")
    val schedules: kotlin.collections.Map<kotlin.String, kotlin.collections.List<ShiftScheduleItem>>,

    @SerialName(value = "employees")
    val employees: kotlin.collections.List<RosterEmployeeItem>

) {


}

