/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param overallRecommendation 
 * @param technicalSkillRating 
 * @param communicationRating 
 * @param problemSolvingRating 
 * @param culturalFitRating 
 * @param strengths 
 * @param weaknesses 
 * @param summaryNotes 
 */
@Serializable

data class ScorecardSubmitRequest (

    @SerialName(value = "overallRecommendation")
    val overallRecommendation: ScorecardSubmitRequest.OverallRecommendation,

    @Contextual @SerialName(value = "technicalSkillRating")
    val technicalSkillRating: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "communicationRating")
    val communicationRating: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "problemSolvingRating")
    val problemSolvingRating: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "culturalFitRating")
    val culturalFitRating: java.math.BigDecimal? = null,

    @SerialName(value = "strengths")
    val strengths: kotlin.String? = null,

    @SerialName(value = "weaknesses")
    val weaknesses: kotlin.String? = null,

    @SerialName(value = "summaryNotes")
    val summaryNotes: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: STRONG_HIRE,HIRE,NEUTRAL,NO_HIRE,STRONG_NO_HIRE
     */
    @Serializable
    enum class OverallRecommendation(val value: kotlin.String) {
        @SerialName(value = "STRONG_HIRE") STRONG_HIRE("STRONG_HIRE"),
        @SerialName(value = "HIRE") HIRE("HIRE"),
        @SerialName(value = "NEUTRAL") NEUTRAL("NEUTRAL"),
        @SerialName(value = "NO_HIRE") NO_HIRE("NO_HIRE"),
        @SerialName(value = "STRONG_NO_HIRE") STRONG_NO_HIRE("STRONG_NO_HIRE");
    }

}

