/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param requestId 
 * @param status 
 * @param message 
 */
@Serializable

data class ShiftSwapResponse (

    @SerialName(value = "requestId")
    val requestId: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String

) {


}

