/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param signerName 
 * @param signerEmail 
 * @param role 
 * @param signingOrder 
 * @param signerEmployeeId 
 */
@Serializable

data class SignatureSignerInput (

    @SerialName(value = "signerName")
    val signerName: kotlin.String,

    @SerialName(value = "signerEmail")
    val signerEmail: kotlin.String,

    @SerialName(value = "role")
    val role: kotlin.String,

    @SerialName(value = "signingOrder")
    val signingOrder: kotlin.Int,

    @Contextual @SerialName(value = "signerEmployeeId")
    val signerEmployeeId: java.util.UUID? = null

) {


}

