/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.SignatureRequestItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param requests 
 */
@Serializable

data class SignatureRequestListResponse (

    @SerialName(value = "requests")
    val requests: kotlin.collections.List<SignatureRequestItem>

) {


}

