/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.TeamCoverageMemberItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param date 
 * @param totalScheduled 
 * @param totalOnDuty 
 * @param members 
 */
@Serializable

data class TeamCoverageResponse (

    @Contextual @SerialName(value = "date")
    val date: java.time.LocalDate,

    @SerialName(value = "totalScheduled")
    val totalScheduled: kotlin.Int,

    @SerialName(value = "totalOnDuty")
    val totalOnDuty: kotlin.Int,

    @SerialName(value = "members")
    val members: kotlin.collections.List<TeamCoverageMemberItem>

) {


}

