/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param employeeId 
 * @param employeeCode 
 * @param employeeName 
 * @param leaveTypeId 
 * @param leaveTypeName 
 * @param portion 
 * @param status 
 */
@Serializable

data class TeamMemberLeave (

    @Contextual @SerialName(value = "employeeId")
    val employeeId: java.util.UUID,

    @SerialName(value = "employeeCode")
    val employeeCode: kotlin.String,

    @SerialName(value = "employeeName")
    val employeeName: kotlin.String,

    @SerialName(value = "leaveTypeId")
    val leaveTypeId: kotlin.String,

    @SerialName(value = "leaveTypeName")
    val leaveTypeName: kotlin.String,

    @SerialName(value = "portion")
    val portion: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String

) {


}

