/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param targetWeekStartDate 
 * @param employeeId 
 */
@Serializable

data class TimesheetCopyPreviousRequest (

    @Contextual @SerialName(value = "targetWeekStartDate")
    val targetWeekStartDate: java.time.LocalDate,

    @Contextual @SerialName(value = "employeeId")
    val employeeId: java.util.UUID? = null

) {


}

