/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param projectId 
 * @param activityCode 
 * @param activityName 
 * @param billable 
 * @param status 
 */
@Serializable

data class TimesheetActivityItem (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "projectId")
    val projectId: java.util.UUID,

    @SerialName(value = "activityCode")
    val activityCode: kotlin.String,

    @SerialName(value = "activityName")
    val activityName: kotlin.String,

    @SerialName(value = "billable")
    val billable: kotlin.Boolean,

    @SerialName(value = "status")
    val status: kotlin.String

) {


}

