/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param courseId 
 * @param batchCode 
 * @param startDate 
 * @param endDate 
 * @param totalSeats 
 * @param trainerId 
 * @param venueName 
 * @param virtualMeetingUrl 
 * @param costPerParticipant 
 */
@Serializable

data class TrainingScheduleCreateRequest (

    @Contextual @SerialName(value = "courseId")
    val courseId: java.util.UUID,

    @SerialName(value = "batchCode")
    val batchCode: kotlin.String,

    @Contextual @SerialName(value = "startDate")
    val startDate: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "endDate")
    val endDate: java.time.OffsetDateTime,

    @SerialName(value = "totalSeats")
    val totalSeats: kotlin.Int,

    @Contextual @SerialName(value = "trainerId")
    val trainerId: java.util.UUID? = null,

    @SerialName(value = "venueName")
    val venueName: kotlin.String? = null,

    @SerialName(value = "virtualMeetingUrl")
    val virtualMeetingUrl: kotlin.String? = null,

    @Contextual @SerialName(value = "costPerParticipant")
    val costPerParticipant: java.math.BigDecimal? = null

) {


}

