/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model

import com.hr.client.model.VacancyItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param totalCount 
 */
@Serializable

data class VacancyListResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<VacancyItem>,

    @SerialName(value = "totalCount")
    val totalCount: kotlin.Int

) {


}

