/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hr.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param jobCode 
 * @param title 
 * @param location 
 * @param employmentType 
 * @param experienceLevel 
 * @param currency 
 * @param description 
 * @param openPositions 
 * @param departmentId 
 * @param minSalary 
 * @param maxSalary 
 * @param requirements 
 * @param targetHireDate 
 * @param closingDate 
 */
@Serializable

data class VacancyCreateRequest (

    @SerialName(value = "jobCode")
    val jobCode: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "location")
    val location: kotlin.String,

    @SerialName(value = "employmentType")
    val employmentType: kotlin.String,

    @SerialName(value = "experienceLevel")
    val experienceLevel: kotlin.String,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "openPositions")
    val openPositions: kotlin.Int,

    @Contextual @SerialName(value = "departmentId")
    val departmentId: java.util.UUID? = null,

    @Contextual @SerialName(value = "minSalary")
    val minSalary: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "maxSalary")
    val maxSalary: java.math.BigDecimal? = null,

    @SerialName(value = "requirements")
    val requirements: kotlin.String? = null,

    @Contextual @SerialName(value = "targetHireDate")
    val targetHireDate: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "closingDate")
    val closingDate: java.time.LocalDate? = null

) {


}

